In [8]:
import pandas as pd
import numpy as np

data1 = pd.read_csv('weather.csv')
data2={
    "first":["Sam","Karen","Paul","Chris",np.nan,None,'NA'],
    "last":["Peri","Shuffer","Baget","Pottin",np.nan,np.nan,'Missing'],
    "email":["SP@gmail","KS@yahoo","PB@facebook","CP@gmail",None,np.nan,"anonymous@gmail"],
    "age":['33','33','63','36',None,None,'Missing']
}
data3={
    "first":["Tony", "Steve"],
    "last":["Stark", "Rogers"],
    "email":["iron@gmail", "captain@gamil"]
}

df = pd.DataFrame(data1)
df = df[['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation']]
df_people=pd.DataFrame(data2)
df_avengers=pd.DataFrame(data3)

In [54]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,"(loc1, loc2)",loc1,loc2
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,[Albury],Albury,None
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,[Albury],Albury,None
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,[Albury],Albury,None
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,[Albury],Albury,None
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,[Albury],Albury,None

## <mark> GroupBy
    
    df.groupby(
        by=['col1', 'col2'],
        axis: 0,
        as_index: True,
        sort: True,
        group_keys: True,
        observed: False,
        dropna: True,
    )

#### groupby object's attributes

    pandas.core.groupby.all
        .any
        .bfill
        .count
        .cumcount
        .ffill
        .first
        .head
        .last
        .max
        .mean
        .median
        .min
        .ngroup
        .nth
        .ohlc
        .prod
        .rank
        .pct_change
        .size
        .sem
        .std
        .sum
        .var
        .tail
    
    pandas.core.groupby..DataFrameGroupBy.agg
        .all
        .any
        .bfill
        .corr
        .count
        .cov
        .cummax
        .cummin
        .cumprod
        .cumsum
        .describe
        .diff
        .ffill
        .fillna
        .filter
        .hist
        .idxmax
        .idxmin
        .mad
        .pct_change
        .plot
        .quantile
        .rank
        .resample
        .shift
        .size
        .skew
        .take
        .tshift

In [9]:
df.sample()

             Date Location  MinTemp  MaxTemp  Rainfall  Evaporation
71153  31-01-2011  Mildura     23.9     39.9       0.0          8.0

In [10]:
df.groupby(['Location'])

In [11]:
location_groups = df.groupby(['Location'])
location_groups

In [18]:
df_sydney = location_groups.get_group('Sydney')
type(df_sydney)

pandas.core.frame.DataFrame

#### groupby aggregations

In [39]:
df.groupby(['Location']).sum()[:3]

          MinTemp  MaxTemp  Rainfall  Evaporation
Location
Adelaide  40141.2  73047.6    4841.6       9832.7
Albany    38547.5  59932.0    6827.8      11586.7
Albury    28868.2  68579.2    5763.4          0.0

In [30]:
# groupwise sum of values for a particular feature ex. Rainfall
location_groups['Rainfall'].sum()[27:30]

Location
NorfolkIsland    9270.4
Nuriootpa        4175.2
PearceRAAF       4610.0
Name: Rainfall, dtype: float64

In [27]:
# groupwise max values for a particular feature ex. Rainfall
location_groups['Rainfall'].max()[:3]

Location
Adelaide     75.2
Albany       49.4
Albury      104.2
Name: Rainfall, dtype: float64

In [31]:
# groupwise max values for a particular feature ex. Rainfall
location_groups['Rainfall'].median().loc['Dartmoor']

0.2

In [40]:
location_groups['Evaporation'].agg(['min', 'mean', 'max', 'sum'])[5:7]

          min     mean   max     sum
Location
Ballarat  NaN      NaN   NaN     0.0
Bendigo   0.0  3.85173  15.4  4564.3

In [41]:
location_groups['Evaporation'].agg(['min', 'mean', 'max', 'sum']).loc['Dartmoor']

min        0.000000
mean       3.424808
max       16.400000
sum     8904.500000
Name: Dartmoor, dtype: float64

In [ ]:
# location_groups["Location"].apply(lambda x: x.str.contains("Python").sum())

## <mark> Windowing

## <mark> Concatenating/Appending
    
    pd.concat(
        objs: [df1, df2],
        axis: 0-rowwise, 1-columnwise
        join: 'outer'-default, 'inner'
        ignore_index: False,
        keys=None,    # resulting hierarchical index
        levels=None,  # resulting hierarchical index
        names=None,   # resulting hierarchical index
        verify_integrity: 'bool' = False,
        sort: False,
        copy: True,
    )
    
https://pandas.pydata.org/pandas-docs/version/0.23/merging.html

In [84]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A2'],
                    'B': ['B0', 'B2'],
                    'C': ['C0', 'C2'],
                    'D': ['D0', 'D2']},
                    index=[11, 12])

df2 = pd.DataFrame({'A': ['A4', 'A6'],
                    'B': ['B4', 'B6'],
                    'C': ['C4', 'C6'],
                    'D': ['D4', 'D6']},
                    index=[50, 60])

df3 = pd.DataFrame({'B': ['B8', 'B10'],
                    'C': ['C8', 'C10'],
                    'F': ['F8', 'F10']},
                    index=[80, 50])

In [85]:
pd.concat([df1, df2], keys=['x', 'y'])

       A   B   C   D
x 11  A0  B0  C0  D0
  12  A2  B2  C2  D2
y 50  A4  B4  C4  D4
  60  A6  B6  C6  D6

In [86]:
pd.concat([df1, df2], keys=['x', 'y'], ignore_index=True)

    A   B   C   D
0  A0  B0  C0  D0
1  A2  B2  C2  D2
2  A4  B4  C4  D4
3  A6  B6  C6  D6

In [87]:
pd.concat([df1, df2], keys=['x', 'y']).loc['y']

     A   B   C   D
50  A4  B4  C4  D4
60  A6  B6  C6  D6

In [88]:
pd.concat([df1, df3], axis=1)

      A    B    C    D    B    C    F
11   A0   B0   C0   D0  NaN  NaN  NaN
12   A2   B2   C2   D2  NaN  NaN  NaN
80  NaN  NaN  NaN  NaN   B8   C8   F8
50  NaN  NaN  NaN  NaN  B10  C10  F10

In [89]:
pd.concat([df2, df3], join='inner', axis=1)

     A   B   C   D    B    C    F
50  A4  B4  C4  D4  B10  C10  F10

In [90]:
pd.concat([df2, df3], join='inner')

      B    C
50   B4   C4
60   B6   C6
80   B8   C8
50  B10  C10

In [94]:
# we can pass dictionary mapped to dataframes
pieces = {'x': df1, 'y': df2}
result = pd.concat(pieces)
result

       A   B   C   D
x 11  A0  B0  C0  D0
  12  A2  B2  C2  D2
y 50  A4  B4  C4  D4
  60  A6  B6  C6  D6

In [92]:
# append method is deprecated
df1.append([df2])

C:\Users\AdmiN\AppData\Local\Temp\ipykernel_5580\1573043551.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append([df2])

     A   B   C   D
11  A0  B0  C0  D0
12  A2  B2  C2  D2
50  A4  B4  C4  D4
60  A6  B6  C6  D6

### <mark> Joining/Merging

pandas has full-featured, high performance in-memory join operations idiomatically very similar to relational databases like SQL. pandas provides a single function, merge(), as the entry point for all standard database join operations between DataFrame objects
    
one-to-one joins: for example when joining two DataFrame objects on their indexes (which must contain unique values).
many-to-one joins: for example when joining an index (unique) to one or more columns in a different DataFrame.
many-to-many joins: joining columns on columns.
    
    pd.merge(
        left: df1,
        right: df2,
        how: 'inner, left, right, outer',
        on: [key1, key2],
    
        left_on: 'IndexLabel | None' = None,
        right_on: 'IndexLabel | None' = None,
        left_index: False,
        right_index: False,
    
        sort: False,
        suffixes: ('_x', '_y'),
        copy: True,
        indicator: str|False,  #merge indicator
        validate: None,
    )

In [110]:
import pandas as pd
df1 = pd.DataFrame({'id': ['K0', 'K0', 'K1', 'K2'],
                    'call_id': ['K0', 'K1', 'K0', 'K1'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']},
                    index=['bd', 'ju', 'vf', 'yh']
                  )

df2 = pd.DataFrame({'id': ['K0', 'K1', 'K1', 'K2'],
                    'call_id': ['K0', 'K0', 'K0', 'K0'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=['gb', 'ju', 'uj', 'yh']
                  )

In [111]:
pd.merge(df1, df2, how='left', on=['id', 'call_id'], 
         indicator='indicator_column',
         # left_index=True,
        )

# Can only pass argument "on" OR "left_index" and "right_index", not a combination of both.

   id call_id   A   B    C    D indicator_column
0  K0      K0  A0  B0   C0   D0             both
1  K0      K1  A1  B1  NaN  NaN        left_only
2  K1      K0  A2  B2   C1   D1             both
3  K1      K0  A2  B2   C2   D2             both
4  K2      K1  A3  B3  NaN  NaN        left_only

In [112]:
pd.merge(df1, df2, how='inner', on=['id', 'call_id'])

   id call_id   A   B   C   D
0  K0      K0  A0  B0  C0  D0
1  K1      K0  A2  B2  C1  D1
2  K1      K0  A2  B2  C2  D2

In [114]:
'''Joining on INDEX
DataFrame.join() is a convenient method for combining the columns of 
two potentially differently-indexed DataFrames into a single result DataFrame.
'''

df3 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']},
                    index=['bd', 'ju', 'vf', 'yh']
                  )
df4 = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=['gb', 'ju', 'uj', 'yh']
                  )

result = df3.join(df4)
result

     A   B    C    D
bd  A0  B0  NaN  NaN
ju  A1  B1   C1   D1
vf  A2  B2  NaN  NaN
yh  A3  B3   C3   D3