# DataFrame:

- Its a tabular datastructre having rows and column in 2 d format
- can passed with(list, dict, series, dataframes) as argument

In [4]:
# 1Creating the df from dict

dict1={"crickter":["Virat","Ghyale","ABD"],"100":[1000,2000,3000],"Teams":["IND","WI","SA"]}

In [5]:
dict1

{'crickter': ['Virat', 'Ghyale', 'ABD'],
 '100': [1000, 2000, 3000],
 'Teams': ['IND', 'WI', 'SA']}

In [1]:
import pandas as pd

pd.DataFrame(
    
    data=None,
    index: 'Optional[Axes]' = None,
    columns: 'Optional[Axes]' = None,
    dtype: 'Optional[Dtype]' = None,
    copy: 'bool' = False,
)

**Two-dimensional, size-mutable, potentially heterogeneous tabular data.**

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as **A DICT LIKE CONTAINER FOR SERIES OBJECTS.** The primary
pandas data structure.

data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order.

In [6]:
df_c=pd.DataFrame(dict1)

# for creating dataframe from dict

In [7]:
df_c

  crickter   100 Teams
0    Virat  1000   IND
1   Ghyale  2000    WI
2      ABD  3000    SA

In [10]:
# 2Creating the df from lits of tupples

In [11]:
List_t=[(1,2),(3,4),(5,6)]

List_t

[(1, 2), (3, 4), (5, 6)]

In [12]:
df_t=pd.DataFrame(List_t)

df_t

   0  1
0  1  2
1  3  4
2  5  6

In [13]:
# 3_ from list

In [14]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [8]:
asd=pd.DataFrame([1,2,3])
asd

   0
0  1
1  2
2  3

In [11]:
# Creating dataframe from csv file
import pandas as pd
titanic=pd.read_csv("C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\DATASETS\\titanic_train.csv")

In [3]:
type(titanic)

pandas.core.frame.DataFrame

In [13]:
df_titanic=pd.DataFrame(titanic)

In [14]:
type(df_titanic)

pandas.core.frame.DataFrame

In [15]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
# Creating dataframe from xlxs file

titanic2=pd.read_excel("C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\DATASETS\\Mock3.xlsx")

In [17]:
titanic2

,Velocity Corporate Training Center - Python and Data Science Batch,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,MOCK INTERVIEW - II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr No,Student Name,Group,Batch,Interview Time,Interviewer,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Deokar saurabh,4,A,11:00:00,Afreen,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Divyshri Mishra,4,A,11:15:00,Afreen,AB,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,79,Anil Tandale,17,D,13:30:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,80,Akshata dadmal,17,D,13:45:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,81,Simran Ade,18,D,14:00:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,82,Dhananjay Aghav,5,D,14:15:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,83,Rahul Patil,6,D,14:30:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
type(titanic2)

pandas.core.frame.DataFrame

In [19]:
df=pd.DataFrame(titanic2)

In [30]:
df

,Velocity Corporate Training Center - Python and Data Science Batch,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,MOCK INTERVIEW - II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr No,Student Name,Group,Batch,Interview Time,Interviewer,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Deokar saurabh,4,A,11:00:00,Afreen,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Divyshri Mishra,4,A,11:15:00,Afreen,AB,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,79,Anil Tandale,17,D,13:30:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,80,Akshata dadmal,17,D,13:45:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,81,Simran Ade,18,D,14:00:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,82,Dhananjay Aghav,5,D,14:15:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,83,Rahul Patil,6,D,14:30:00,Chetan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Accessing the records in dataframe

In [36]:
#df.head()

In [37]:
#df.head(15)

In [39]:
#df.tail()

In [40]:
#df.tail(3)

In [41]:
df.shape

(96, 26)

In [43]:
"""Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.
"""

df.describe()

,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
"""Print a concise summary of a DataFrame.

This method prints information about a DataFrame including
the index dtype and columns, non-null values and memory usage.
"""
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [21]:
df_titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [23]:
df_titanic["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [25]:
df_titanic[["Name","Ticket","Age"]].head(10)

                                                Name            Ticket   Age
0                            Braund, Mr. Owen Harris         A/5 21171  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...          PC 17599  38.0
2                             Heikkinen, Miss. Laina  STON/O2. 3101282  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)            113803  35.0
4                           Allen, Mr. William Henry            373450  35.0
5                                   Moran, Mr. James            330877   NaN
6                            McCarthy, Mr. Timothy J             17463  54.0
7                     Palsson, Master. Gosta Leonard            349909   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)            347742  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)            237736  14.0

In [26]:
# all columns name
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
df_titanic.index

RangeIndex(start=0, stop=891, step=1)

# Slicing

In [29]:
df_titanic[["Name","Ticket","Age"]][0:10:2]
#[start:stop:step]

                                                Name            Ticket   Age
0                            Braund, Mr. Owen Harris         A/5 21171  22.0
2                             Heikkinen, Miss. Laina  STON/O2. 3101282  26.0
4                           Allen, Mr. William Henry            373450  35.0
6                            McCarthy, Mr. Timothy J             17463  54.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)            347742  27.0

In [30]:
df_titanic[3:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S

In [31]:
# using iter function for every row display
for index,row in df_titanic.iterrows():
    print(index,row)

0 PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object
1 PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object
2 PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object
3 PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object
4 PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object
5 PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object
6 PassengerId                          7
Survived                             0
Pclass                               1
Name           McCarthy, Mr. Timothy J
Sex                               male
Age                               54.0
SibSp                                0
Parch                                0
Ticket                           17463
Fare                           51.8625
Cabin                              E46
Embarked                             S
Name: 6, dtype: object
7 PassengerId                                 8
Survived                                    0
Pclass                                      3
Name           Palsson, Master. Gosta Leonard
Sex                                      male
Age                                       2.0
SibSp                                       3
Parch                                       1
Ticket                                 349909
Fare                                   21.075
Cabin                                     NaN
Embarked                                    S
Name: 7, dtype: object
8 PassengerId                                                    9
Survived                                                       1
Pclass                                                         3
Name           Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Sex                                                       female
Age                                                         27.0
SibSp                                                          0
Parch                                                          2
Ticket                                                    347742
Fare                                                     11.1333
Cabin                                                        NaN
Embarked                                                       S
Name: 8, dtype: object
9 PassengerId                                     10
Survived                                         1
Pclass                                           2
Name           Nasser, Mrs. Nicholas (Adele Achem)
Sex                                         female
Age                                           14.0
SibSp                                            1
Parch                                            0
Ticket                                      237736
Fare                                       30.0708
Cabin                                          NaN
Embarked                                         C
Name: 9, dtype: object
10 PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object
11 PassengerId                          12
Survived                              1
Pclass                                1
Name           Bonnell, Miss. Elizabeth
Sex                              female
Age                                58.0
SibSp                                 0
Parch                                 0
Ticket                           113783
Fare                              26.55
Cabin                              C103
Embarked                              S
Name: 11, dtype: object
12 PassengerId                                13
Survived                                    0
Pclass                                      3
Name           Saundercock, Mr. William Henry
Sex                                      male
Age                                      20.0
SibSp                                       0
Parch                                       0
Ticket                              A/5. 2151
Fare                                     8.05
Cabin                                     NaN
Embarked                                    S
Name: 12, dtype: object
13 PassengerId                             14
Survived                                 0
Pclass                                   3
Name           Andersson, Mr. Anders Johan
Sex                                   male
Age                                   39.0
SibSp                                    1
Parch                                    5
Ticket                              347082
Fare                                31.275
Cabin                                  NaN
Embarked                                 S
Name: 13, dtype: object
14 PassengerId                                      15
Survived                                          0
Pclass                                            3
Name           Vestrom, Miss. Hulda Amanda Adolfina
Sex                                          female
Age                                            14.0
SibSp                                             0
Parch                                             0
Ticket                                       350406
Fare                                         7.8542
Cabin                                           NaN
Embarked                                          S
Name: 14, dtype: object
15 PassengerId                                  16
Survived                                      1
Pclass                                        2
Name           Hewlett, Mrs. (Mary D Kingcome)
Sex                                      female
Age                                        55.0
SibSp                                         0
Parch                                         0
Ticket                                   248706
Fare                                       16.0
Cabin                                       NaN
Embarked                                      S
Name: 15, dtype: object
16 PassengerId                      17
Survived                          0
Pclass                            3
Name           Rice, Master. Eugene
Sex                            male
Age                             2.0
SibSp                             4
Parch                             1
Ticket                       382652
Fare                         29.125
Cabin                           NaN
Embarked                          Q
Name: 16, dtype: object
17 PassengerId                              18
Survived                                  1
Pclass                                    2
Name           Williams, Mr. Charles Eugene
Sex                                    male
Age                                     NaN
SibSp                                     0
Parch                                     0
Ticket                               244373
Fare                                   13.0
Cabin                                   NaN
Embarked                                  S
Name: 17, dtype: object
18 PassengerId                                                   19
Survived                                                       0
Pclass                                                         3
Name           Vander Planke, Mrs. Julius (Emelia Maria Vande...
Sex                                                       female
Age                                                         31.0
SibSp                                                          1
Parch                                                          0
Ticket                                                    345763
Fare                                                        18.0
Cabin                                                        NaN
Embarked                                                       S
Name: 18, dtype: object
19 PassengerId                         20
Survived                             1
Pclass                               3
Name           Masselmani, Mrs. Fatima
Sex                             female
Age                                NaN
SibSp                                0
Parch                                0
Ticket                            2649
Fare                             7.225
Cabin                              NaN
Embarked                             C
Name: 19, dtype: object
20 PassengerId                      21
Survived                          0
Pclass                            2
Name           Fynney, Mr. Joseph J
Sex                            male
Age                            35.0
SibSp                             0
Parch                             0
Ticket                       239865
Fare                           26.0
Cabin                           NaN
Embarked                          S
Name: 20, dtype: object
21 PassengerId                       22
Survived                           1
Pclass                             2
Name           Beesley, Mr. Lawrence
Sex                             male
Age                             34.0
SibSp                              0
Parch                              0
Ticket                        248698
Fare                            13.0
Cabin                            D56
Embarked                           S
Name: 21, dtype: object
22 PassengerId                             23
Survived                                 1
Pclass                                   3
Name           McGowan, Miss. Anna "Annie"
Sex                                 female
Age                                   15.0
SibSp                                    0
Parch                                    0
Ticket                              330923
Fare                                8.0292
Cabin                                  NaN
Embarked                                 Q
Name: 22, dtype: object
23 PassengerId                              24
Survived                                  1
Pclass                                    1
Name           Sloper, Mr. William Thompson
Sex                                    male
Age                                    28.0
SibSp                                     0
Parch                                     0
Ticket                               113788
Fare                                   35.5
Cabin                                    A6
Embarked                                  S
Name: 23, dtype: object
24 PassengerId                               25
Survived                                   0
Pclass                                     3
Name           Palsson, Miss. Torborg Danira
Sex                                   female
Age                                      8.0
SibSp                                      3
Parch                                      1
Ticket                                349909
Fare                                  21.075
Cabin                                    NaN
Embarked                                   S
Name: 24, dtype: object
25 PassengerId                                                   26
Survived                                                       1
Pclass                                                         3
Name           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          5
Ticket                                                    347077
Fare                                                     31.3875
Cabin                                                        NaN
Embarked                                                       S
Name: 25, dtype: object
26 PassengerId                         27
Survived                             0
Pclass                               3
Name           Emir, Mr. Farred Chehab
Sex                               male
Age                                NaN
SibSp                                0
Parch                                0
Ticket                            2631
Fare                             7.225
Cabin                              NaN
Embarked                             C
Name: 26, dtype: object
27 PassengerId                                28
Survived                                    0
Pclass                                      1
Name           Fortune, Mr. Charles Alexander
Sex                                      male
Age                                      19.0
SibSp                                       3
Parch                                       2
Ticket                                  19950
Fare                                    263.0
Cabin                             C23 C25 C27
Embarked                                    S
Name: 27, dtype: object
28 PassengerId                               29
Survived                                   1
Pclass                                     3
Name           O'Dwyer, Miss. Ellen "Nellie"
Sex                                   female
Age                                      NaN
SibSp                                      0
Parch                                      0
Ticket                                330959
Fare                                  7.8792
Cabin                                    NaN
Embarked                                   Q
Name: 28, dtype: object
29 PassengerId                     30
Survived                         0
Pclass                           3
Name           Todoroff, Mr. Lalio
Sex                           male
Age                            NaN
SibSp                            0
Parch                            0
Ticket                      349216
Fare                        7.8958
Cabin                          NaN
Embarked                         S
Name: 29, dtype: object
30 PassengerId                          31
Survived                              0
Pclass                                1
Name           Uruchurtu, Don. Manuel E
Sex                                male
Age                                40.0
SibSp                                 0
Parch                                 0
Ticket                         PC 17601
Fare                            27.7208
Cabin                               NaN
Embarked                              C
Name: 30, dtype: object
31 PassengerId                                                32
Survived                                                    1
Pclass                                                      1
Name           Spencer, Mrs. William Augustus (Marie Eugenie)
Sex                                                    female
Age                                                       NaN
SibSp                                                       1
Parch                                                       0
Ticket                                               PC 17569
Fare                                                 146.5208
Cabin                                                     B78
Embarked                                                    C
Name: 31, dtype: object
32 PassengerId                          33
Survived                              1
Pclass                                3
Name           Glynn, Miss. Mary Agatha
Sex                              female
Age                                 NaN
SibSp                                 0
Parch                                 0
Ticket                           335677
Fare                               7.75
Cabin                               NaN
Embarked                              Q
Name: 32, dtype: object
33 PassengerId                       34
Survived                           0
Pclass                             2
Name           Wheadon, Mr. Edward H
Sex                             male
Age                             66.0
SibSp                              0
Parch                              0
Ticket                    C.A. 24579
Fare                            10.5
Cabin                            NaN
Embarked                           S
Name: 33, dtype: object
34 PassengerId                         35
Survived                             0
Pclass                               1
Name           Meyer, Mr. Edgar Joseph
Sex                               male
Age                               28.0
SibSp                                1
Parch                                0
Ticket                        PC 17604
Fare                           82.1708
Cabin                              NaN
Embarked                             C
Name: 34, dtype: object

Name: 116, dtype: object
117 PassengerId                                118
Survived                                     0
Pclass                                       2
Name           Turpin, Mr. William John Robert
Sex                                       male
Age                                       29.0
SibSp                                        1
Parch                                        0
Ticket                                   11668
Fare                                      21.0
Cabin                                      NaN
Embarked                                     S
Name: 117, dtype: object
118 PassengerId                         119
Survived                              0
Pclass                                1
Name           Baxter, Mr. Quigg Edmond
Sex                                male
Age                                24.0
SibSp                                 0
Parch                                 1
Ticket                         PC 17558
Fare                           247.5208
Cabin                           B58 B60
Embarked                              C
Name: 118, dtype: object
119 PassengerId                                  120
Survived                                       0
Pclass                                         3
Name           Andersson, Miss. Ellis Anna Maria
Sex                                       female
Age                                          2.0
SibSp                                          4
Parch                                          2
Ticket                                    347082
Fare                                      31.275
Cabin                                        NaN
Embarked                                       S
Name: 119, dtype: object
120 PassengerId                            121
Survived                                 0
Pclass                                   2
Name           Hickman, Mr. Stanley George
Sex                                   male
Age                                   21.0
SibSp                                    2
Parch                                    0
Ticket                        S.O.C. 14879
Fare                                  73.5
Cabin                                  NaN
Embarked                                 S
Name: 120, dtype: object
121 PassengerId                           122
Survived                                0
Pclass                                  3
Name           Moore, Mr. Leonard Charles
Sex                                  male
Age                                   NaN
SibSp                                   0
Parch                                   0
Ticket                          A4. 54510
Fare                                 8.05
Cabin                                 NaN
Embarked                                S
Name: 121, dtype: object
122 PassengerId                     123
Survived                          0
Pclass                            2
Name           Nasser, Mr. Nicholas
Sex                            male
Age                            32.5
SibSp                             1
Parch                             0
Ticket                       237736
Fare                        30.0708
Cabin                           NaN
Embarked                          C
Name: 122, dtype: object
123 PassengerId                    124
Survived                         1
Pclass                           2
Name           Webber, Miss. Susan
Sex                         female
Age                           32.5
SibSp                            0
Parch                            0
Ticket                       27267
Fare                          13.0
Cabin                         E101
Embarked                         S
Name: 123, dtype: object
124 PassengerId                            125
Survived                                 0
Pclass                                   1
Name           White, Mr. Percival Wayland
Sex                                   male
Age                                   54.0
SibSp                                    0
Parch                                    1
Ticket                               35281
Fare                               77.2875
Cabin                                  D26
Embarked                                 S
Name: 124, dtype: object
125 PassengerId                             126
Survived                                  1
Pclass                                    3
Name           Nicola-Yarred, Master. Elias
Sex                                    male
Age                                    12.0
SibSp                                     1
Parch                                     0
Ticket                                 2651
Fare                                11.2417
Cabin                                   NaN
Embarked                                  C
Name: 125, dtype: object
126 PassengerId                    127
Survived                         0
Pclass                           3
Name           McMahon, Mr. Martin
Sex                           male
Age                            NaN
SibSp                            0
Parch                            0
Ticket                      370372
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 126, dtype: object
127 PassengerId                          128
Survived                               1
Pclass                                 3
Name           Madsen, Mr. Fridtjof Arne
Sex                                 male
Age                                 24.0
SibSp                                  0
Parch                                  0
Ticket                           C 17369
Fare                              7.1417
Cabin                                NaN
Embarked                               S
Name: 127, dtype: object
128 PassengerId                  129
Survived                       1
Pclass                         3
Name           Peter, Miss. Anna
Sex                       female
Age                          NaN
SibSp                          1
Parch                          1
Ticket                      2668
Fare                     22.3583
Cabin                      F E69
Embarked                       C
Name: 128, dtype: object
129 PassengerId                   130
Survived                        0
Pclass                          3
Name           Ekstrom, Mr. Johan
Sex                          male
Age                          45.0
SibSp                           0
Parch                           0
Ticket                     347061
Fare                        6.975
Cabin                         NaN
Embarked                        S
Name: 129, dtype: object
130 PassengerId                     131
Survived                          0
Pclass                            3
Name           Drazenoic, Mr. Jozef
Sex                            male
Age                            33.0
SibSp                             0
Parch                             0
Ticket                       349241
Fare                         7.8958
Cabin                           NaN
Embarked                          C
Name: 130, dtype: object
131 PassengerId                               132
Survived                                    0
Pclass                                      3
Name           Coelho, Mr. Domingos Fernandeo
Sex                                      male
Age                                      20.0
SibSp                                       0
Parch                                       0
Ticket                     SOTON/O.Q. 3101307
Fare                                     7.05
Cabin                                     NaN
Embarked                                    S
Name: 131, dtype: object
132 PassengerId                                               133
Survived                                                    0
Pclass                                                      3
Name           Robins, Mrs. Alexander A (Grace Charity Laury)
Sex                                                    female
Age                                                      47.0
SibSp                                                       1
Parch                                                       0
Ticket                                              A/5. 3337
Fare                                                     14.5
Cabin                                                     NaN
Embarked                                                    S
Name: 132, dtype: object
133 PassengerId                                              134
Survived                                                   1
Pclass                                                     2
Name           Weisz, Mrs. Leopold (Mathilde Francoise Pede)
Sex                                                   female
Age                                                     29.0
SibSp                                                      1
Parch                                                      0
Ticket                                                228414
Fare                                                    26.0
Cabin                                                    NaN
Embarked                                                   S
Name: 133, dtype: object
134 PassengerId                               135
Survived                                    0
Pclass                                      2
Name           Sobey, Mr. Samuel James Hayden
Sex                                      male
Age                                      25.0
SibSp                                       0
Parch                                       0
Ticket                             C.A. 29178
Fare                                     13.0
Cabin                                     NaN
Embarked                                    S
Name: 134, dtype: object
135 PassengerId                   136
Survived                        0
Pclass                          2
Name           Richard, Mr. Emile
Sex                          male
Age                          23.0
SibSp                           0
Parch                           0
Ticket              SC/PARIS 2133
Fare                      15.0458
Cabin                         NaN
Embarked                        C
Name: 135, dtype: object
136 PassengerId                             137
Survived                                  1
Pclass                                    1
Name           Newsom, Miss. Helen Monypeny
Sex                                  female
Age                                    19.0
SibSp                                     0
Parch                                     2
Ticket                                11752
Fare                                26.2833
Cabin                                   D47
Embarked                                  S
Name: 136, dtype: object
137 PassengerId                            138
Survived                                 0
Pclass                                   1
Name           Futrelle, Mr. Jacques Heath
Sex                                   male
Age                                   37.0
SibSp                                    1
Parch                                    0
Ticket                              113803
Fare                                  53.1
Cabin                                 C123
Embarked                                 S
Name: 137, dtype: object
138 PassengerId                    139
Survived                         0
Pclass                           3
Name           Osen, Mr. Olaf Elon
Sex                           male
Age                           16.0
SibSp                            0
Parch                            0
Ticket                        7534
Fare                        9.2167
Cabin                          NaN
Embarked                         S
Name: 138, dtype: object
139 PassengerId                   140
Survived                        0
Pclass                          1
Name           Giglio, Mr. Victor
Sex                          male
Age                          24.0
SibSp                           0
Parch                           0
Ticket                   PC 17593
Fare                         79.2
Cabin                         B86
Embarked                        C
Name: 139, dtype: object
140 PassengerId                              141
Survived                                   0
Pclass                                     3
Name           Boulos, Mrs. Joseph (Sultana)
Sex                                   female
Age                                      NaN
SibSp                                      0
Parch                                      2
Ticket                                  2678
Fare                                 15.2458
Cabin                                    NaN
Embarked                                   C
Name: 140, dtype: object
141 PassengerId                         142
Survived                              1
Pclass                                3
Name           Nysten, Miss. Anna Sofia
Sex                              female
Age                                22.0
SibSp                                 0
Parch                                 0
Ticket                           347081
Fare                               7.75
Cabin                               NaN
Embarked                              S
Name: 141, dtype: object
142 PassengerId                                                  143
Survived                                                       1
Pclass                                                         3
Name           Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
Sex                                                       female
Age                                                         24.0
SibSp                                                          1
Parch                                                          0
Ticket                                          STON/O2. 3101279
Fare                                                       15.85
Cabin                                                        NaN
Embarked                                                       S
Name: 142, dtype: object
143 PassengerId                    144
Survived                         0
Pclass                           3
Name           Burke, Mr. Jeremiah
Sex                           male
Age                           19.0
SibSp                            0
Parch                            0
Ticket                      365222
Fare                          6.75
Cabin                          NaN
Embarked                         Q
Name: 143, dtype: object
144 PassengerId                           145
Survived                                0
Pclass                                  2
Name           Andrew, Mr. Edgardo Samuel
Sex                                  male
Age                                  18.0
SibSp                                   0
Parch                                   0
Ticket                             231945
Fare                                 11.5
Cabin                                 NaN
Embarked                                S
Name: 144, dtype: object
145 PassengerId                             146
Survived                                  0
Pclass                                    2
Name           Nicholls, Mr. Joseph Charles
Sex                                    male
Age                                    19.0
SibSp                                     1
Parch                                     1
Ticket                           C.A. 33112
Fare                                  36.75
Cabin                                   NaN
Embarked                                  S
Name: 145, dtype: object
146 PassengerId                                             147
Survived                                                  1
Pclass                                                    3
Name           Andersson, Mr. August Edvard ("Wennerstrom")
Sex                                                    male
Age                                                    27.0
SibSp                                                     0
Parch                                                     0
Ticket                                               350043
Fare                                                 7.7958
Cabin                                                   NaN
Embarked                                                  S
Name: 146, dtype: object
147 PassengerId                                 148
Survived                                      0
Pclass                                        3
Name           Ford, Miss. Robina Maggie "Ruby"
Sex                                      female
Age                                         9.0
SibSp                                         2
Parch                                         2
Ticket                               W./C. 6608
Fare                                     34.375
Cabin                                       NaN
Embarked                                      S
Name: 147, dtype: object
148 PassengerId                                         149
Survived                                              0
Pclass                                                2
Name           Navratil, Mr. Michel ("Louis M Hoffman")
Sex                                                male
Age                                                36.5
SibSp                                                 0
Parch                                                 2
Ticket                                           230080
Fare                                               26.0
Cabin                                                F2
Embarked                                              S
Name: 148, dtype: object
149 PassengerId                                  150
Survived                                       0
Pclass                                         2
Name           Byles, Rev. Thomas Roussel Davids
Sex                                         male
Age                                         42.0
SibSp                                          0
Parch                                          0
Ticket                                    244310
Fare                                        13.0
Cabin                                        NaN
Embarked                                       S
Name: 149, dtype: object
150 PassengerId                           151
Survived                                0
Pclass                                  2
Name           Bateman, Rev. Robert James
Sex                                  male
Age                                  51.0
SibSp                                   0
Parch                                   0
Ticket                        S.O.P. 1166
Fare                               12.525
Cabin                                 NaN
Embarked                                S
Name: 150, dtype: object
151 PassengerId                                  152
Survived                                       1
Pclass                                         1
Name           Pears, Mrs. Thomas (Edith Wearne)
Sex                                       female
Age                                         22.0
SibSp                                          1
Parch                                          0
Ticket                                    113776
Fare                                        66.6
Cabin                                         C2
Embarked                                       S
Name: 151, dtype: object
152 PassengerId                 153
Survived                      0
Pclass                        3
Name           Meo, Mr. Alfonzo
Sex                        male
Age                        55.5
SibSp                         0
Parch                         0
Ticket               A.5. 11206
Fare                       8.05
Cabin                       NaN
Embarked                      S
Name: 152, dtype: object
153 PassengerId                                154

239 PassengerId                       240
Survived                            0
Pclass                              2
Name           Hunt, Mr. George Henry
Sex                              male
Age                              33.0
SibSp                               0
Parch                               0
Ticket                     SCO/W 1585
Fare                           12.275
Cabin                             NaN
Embarked                            S
Name: 239, dtype: object
240 PassengerId                      241
Survived                           0
Pclass                             3
Name           Zabour, Miss. Thamine
Sex                           female
Age                              NaN
SibSp                              1
Parch                              0
Ticket                          2665
Fare                         14.4542
Cabin                            NaN
Embarked                           C
Name: 240, dtype: object
241 PassengerId                               242
Survived                                    1
Pclass                                      3
Name           Murphy, Miss. Katherine "Kate"
Sex                                    female
Age                                       NaN
SibSp                                       1
Parch                                       0
Ticket                                 367230
Fare                                     15.5
Cabin                                     NaN
Embarked                                    Q
Name: 241, dtype: object
242 PassengerId                                243
Survived                                     0
Pclass                                       2
Name           Coleridge, Mr. Reginald Charles
Sex                                       male
Age                                       29.0
SibSp                                        0
Parch                                        0
Ticket                             W./C. 14263
Fare                                      10.5
Cabin                                      NaN
Embarked                                     S
Name: 242, dtype: object
243 PassengerId                              244
Survived                                   0
Pclass                                     3
Name           Maenpaa, Mr. Matti Alexanteri
Sex                                     male
Age                                     22.0
SibSp                                      0
Parch                                      0
Ticket                     STON/O 2. 3101275
Fare                                   7.125
Cabin                                    NaN
Embarked                                   S
Name: 243, dtype: object
244 PassengerId                     245
Survived                          0
Pclass                            3
Name           Attalah, Mr. Sleiman
Sex                            male
Age                            30.0
SibSp                             0
Parch                             0
Ticket                         2694
Fare                          7.225
Cabin                           NaN
Embarked                          C
Name: 244, dtype: object
245 PassengerId                            246
Survived                                 0
Pclass                                   1
Name           Minahan, Dr. William Edward
Sex                                   male
Age                                   44.0
SibSp                                    2
Parch                                    0
Ticket                               19928
Fare                                  90.0
Cabin                                  C78
Embarked                                 Q
Name: 245, dtype: object
246 PassengerId                                      247
Survived                                           0
Pclass                                             3
Name           Lindahl, Miss. Agda Thorilda Viktoria
Sex                                           female
Age                                             25.0
SibSp                                              0
Parch                                              0
Ticket                                        347071
Fare                                           7.775
Cabin                                            NaN
Embarked                                           S
Name: 246, dtype: object
247 PassengerId                                248
Survived                                     1
Pclass                                       2
Name           Hamalainen, Mrs. William (Anna)
Sex                                     female
Age                                       24.0
SibSp                                        0
Parch                                        2
Ticket                                  250649
Fare                                      14.5
Cabin                                      NaN
Embarked                                     S
Name: 247, dtype: object
248 PassengerId                              249
Survived                                   1
Pclass                                     1
Name           Beckwith, Mr. Richard Leonard
Sex                                     male
Age                                     37.0
SibSp                                      1
Parch                                      1
Ticket                                 11751
Fare                                 52.5542
Cabin                                    D35
Embarked                                   S
Name: 248, dtype: object
249 PassengerId                              250
Survived                                   0
Pclass                                     2
Name           Carter, Rev. Ernest Courtenay
Sex                                     male
Age                                     54.0
SibSp                                      1
Parch                                      0
Ticket                                244252
Fare                                    26.0
Cabin                                    NaN
Embarked                                   S
Name: 249, dtype: object
250 PassengerId                       251
Survived                            0
Pclass                              3
Name           Reed, Mr. James George
Sex                              male
Age                               NaN
SibSp                               0
Parch                               0
Ticket                         362316
Fare                             7.25
Cabin                             NaN
Embarked                            S
Name: 250, dtype: object
251 PassengerId                                           252
Survived                                                0
Pclass                                                  3
Name           Strom, Mrs. Wilhelm (Elna Matilda Persson)
Sex                                                female
Age                                                  29.0
SibSp                                                   1
Parch                                                   1
Ticket                                             347054
Fare                                              10.4625
Cabin                                                  G6
Embarked                                                S
Name: 251, dtype: object
252 PassengerId                          253
Survived                               0
Pclass                                 1
Name           Stead, Mr. William Thomas
Sex                                 male
Age                                 62.0
SibSp                                  0
Parch                                  0
Ticket                            113514
Fare                               26.55
Cabin                                C87
Embarked                               S
Name: 252, dtype: object
253 PassengerId                         254
Survived                              0
Pclass                                3
Name           Lobb, Mr. William Arthur
Sex                                male
Age                                30.0
SibSp                                 1
Parch                                 0
Ticket                        A/5. 3336
Fare                               16.1
Cabin                               NaN
Embarked                              S
Name: 253, dtype: object
254 PassengerId                                         255
Survived                                              0
Pclass                                                3
Name           Rosblom, Mrs. Viktor (Helena Wilhelmina)
Sex                                              female
Age                                                41.0
SibSp                                                 0
Parch                                                 2
Ticket                                           370129
Fare                                            20.2125
Cabin                                               NaN
Embarked                                              S
Name: 254, dtype: object
255 PassengerId                                        256
Survived                                             1
Pclass                                               3
Name           Touma, Mrs. Darwis (Hanne Youssef Razi)
Sex                                             female
Age                                               29.0
SibSp                                                0
Parch                                                2
Ticket                                            2650
Fare                                           15.2458
Cabin                                              NaN
Embarked                                             C
Name: 255, dtype: object
256 PassengerId                               257
Survived                                    1
Pclass                                      1
Name           Thorne, Mrs. Gertrude Maybelle
Sex                                    female
Age                                       NaN
SibSp                                       0
Parch                                       0
Ticket                               PC 17585
Fare                                     79.2
Cabin                                     NaN
Embarked                                    C
Name: 256, dtype: object
257 PassengerId                     258
Survived                          1
Pclass                            1
Name           Cherry, Miss. Gladys
Sex                          female
Age                            30.0
SibSp                             0
Parch                             0
Ticket                       110152
Fare                           86.5
Cabin                           B77
Embarked                          S
Name: 257, dtype: object
258 PassengerId                 259
Survived                      1
Pclass                        1
Name           Ward, Miss. Anna
Sex                      female
Age                        35.0
SibSp                         0
Parch                         0
Ticket                 PC 17755
Fare                   512.3292
Cabin                       NaN
Embarked                      C
Name: 258, dtype: object
259 PassengerId                            260
Survived                                 1
Pclass                                   2
Name           Parrish, Mrs. (Lutie Davis)
Sex                                 female
Age                                   50.0
SibSp                                    0
Parch                                    1
Ticket                              230433
Fare                                  26.0
Cabin                                  NaN
Embarked                                 S
Name: 259, dtype: object
260 PassengerId                  261
Survived                       0
Pclass                         3
Name           Smith, Mr. Thomas
Sex                         male
Age                          NaN
SibSp                          0
Parch                          0
Ticket                    384461
Fare                        7.75
Cabin                        NaN
Embarked                       Q
Name: 260, dtype: object
261 PassengerId                                  262
Survived                                       1
Pclass                                         3
Name           Asplund, Master. Edvin Rojj Felix
Sex                                         male
Age                                          3.0
SibSp                                          4
Parch                                          2
Ticket                                    347077
Fare                                     31.3875
Cabin                                        NaN
Embarked                                       S
Name: 261, dtype: object
262 PassengerId                  263
Survived                       0
Pclass                         1
Name           Taussig, Mr. Emil
Sex                         male
Age                         52.0
SibSp                          1
Parch                          1
Ticket                    110413
Fare                       79.65
Cabin                        E67
Embarked                       S
Name: 262, dtype: object
263 PassengerId                      264
Survived                           0
Pclass                             1
Name           Harrison, Mr. William
Sex                             male
Age                             40.0
SibSp                              0
Parch                              0
Ticket                        112059
Fare                             0.0
Cabin                            B94
Embarked                           S
Name: 263, dtype: object
264 PassengerId                   265
Survived                        0
Pclass                          3
Name           Henry, Miss. Delia
Sex                        female
Age                           NaN
SibSp                           0
Parch                           0
Ticket                     382649
Fare                         7.75
Cabin                         NaN
Embarked                        Q
Name: 264, dtype: object
265 PassengerId                  266
Survived                       0
Pclass                         2
Name           Reeves, Mr. David
Sex                         male
Age                         36.0
SibSp                          0
Parch                          0
Ticket                C.A. 17248
Fare                        10.5
Cabin                        NaN
Embarked                       S
Name: 265, dtype: object
266 PassengerId                          267
Survived                               0
Pclass                                 3
Name           Panula, Mr. Ernesti Arvid
Sex                                 male
Age                                 16.0
SibSp                                  4
Parch                                  1
Ticket                           3101295
Fare                             39.6875
Cabin                                NaN
Embarked                               S
Name: 266, dtype: object
267 PassengerId                         268
Survived                              1
Pclass                                3
Name           Persson, Mr. Ernst Ulrik
Sex                                male
Age                                25.0
SibSp                                 1
Parch                                 0
Ticket                           347083
Fare                              7.775
Cabin                               NaN
Embarked                              S
Name: 267, dtype: object
268 PassengerId                                              269
Survived                                                   1
Pclass                                                     1
Name           Graham, Mrs. William Thompson (Edith Junkins)
Sex                                                   female
Age                                                     58.0
SibSp                                                      0
Parch                                                      1
Ticket                                              PC 17582
Fare                                                153.4625
Cabin                                                   C125
Embarked                                                   S
Name: 268, dtype: object
269 PassengerId                       270
Survived                            1
Pclass                              1
Name           Bissette, Miss. Amelia
Sex                            female
Age                              35.0
SibSp                               0
Parch                               0
Ticket                       PC 17760
Fare                         135.6333
Cabin                             C99
Embarked                            S
Name: 269, dtype: object
270 PassengerId                      271
Survived                           0
Pclass                             1
Name           Cairns, Mr. Alexander
Sex                             male
Age                              NaN
SibSp                              0
Parch                              0
Ticket                        113798
Fare                            31.0
Cabin                            NaN
Embarked                           S
Name: 270, dtype: object
271 PassengerId                             272
Survived                                  1
Pclass                                    3
Name           Tornquist, Mr. William Henry
Sex                                    male
Age                                    25.0
SibSp                                     0
Parch                                     0
Ticket                                 LINE
Fare                                    0.0
Cabin                                   NaN
Embarked                                  S
Name: 271, dtype: object
272 PassengerId                                          273
Survived                                               1
Pclass                                                 2
Name           Mellinger, Mrs. (Elizabeth Anne Maidment)
Sex                                               female
Age                                                 41.0
SibSp                                                  0
Parch                                                  1
Ticket                                            250644
Fare                                                19.5
Cabin                                                NaN
Embarked                                               S
Name: 272, dtype: object
273 PassengerId                      274
Survived                           0
Pclass                             1
Name           Natsch, Mr. Charles H
Sex                             male
Age                             37.0
SibSp                              0
Parch                              1
Ticket                      PC 17596
Fare                            29.7
Cabin                           C118
Embarked                           C
Name: 273, dtype: object
274 PassengerId                           275
Survived                                1
Pclass                                  3
Name           Healy, Miss. Hanora "Nora"
Sex                                female
Age                                   NaN
SibSp                                   0
Parch                                   0
Ticket                             370375
Fare                                 7.75
Cabin                                 NaN
Embarked                                Q
Name: 274, dtype: object
275 PassengerId                                  276
Survived                                       1
Pclass                                         1
Name           Andrews, Miss. Kornelia Theodosia
Sex                                       female
Age                                         63.0
SibSp                                          1
Parch                                          0

375 PassengerId                                      376
Survived                                           1
Pclass                                             1
Name           Meyer, Mrs. Edgar Joseph (Leila Saks)
Sex                                           female
Age                                              NaN
SibSp                                              1
Parch                                              0
Ticket                                      PC 17604
Fare                                         82.1708
Cabin                                            NaN
Embarked                                           C
Name: 375, dtype: object
376 PassengerId                                377
Survived                                     1
Pclass                                       3
Name           Landergren, Miss. Aurora Adelia
Sex                                     female
Age                                       22.0
SibSp                                        0
Parch                                        0
Ticket                                  C 7077
Fare                                      7.25
Cabin                                      NaN
Embarked                                     S
Name: 376, dtype: object
377 PassengerId                          378
Survived                               0
Pclass                                 1
Name           Widener, Mr. Harry Elkins
Sex                                 male
Age                                 27.0
SibSp                                  0
Parch                                  2
Ticket                            113503
Fare                               211.5
Cabin                                C82
Embarked                               C
Name: 377, dtype: object
378 PassengerId                    379
Survived                         0
Pclass                           3
Name           Betros, Mr. Tannous
Sex                           male
Age                           20.0
SibSp                            0
Parch                            0
Ticket                        2648
Fare                        4.0125
Cabin                          NaN
Embarked                         C
Name: 378, dtype: object
379 PassengerId                            380
Survived                                 0
Pclass                                   3
Name           Gustafsson, Mr. Karl Gideon
Sex                                   male
Age                                   19.0
SibSp                                    0
Parch                                    0
Ticket                              347069
Fare                                 7.775
Cabin                                  NaN
Embarked                                 S
Name: 379, dtype: object
380 PassengerId                      381
Survived                           1
Pclass                             1
Name           Bidois, Miss. Rosalie
Sex                           female
Age                             42.0
SibSp                              0
Parch                              0
Ticket                      PC 17757
Fare                         227.525
Cabin                            NaN
Embarked                           C
Name: 380, dtype: object
381 PassengerId                            382
Survived                                 1
Pclass                                   3
Name           Nakid, Miss. Maria ("Mary")
Sex                                 female
Age                                    1.0
SibSp                                    0
Parch                                    2
Ticket                                2653
Fare                               15.7417
Cabin                                  NaN
Embarked                                 C
Name: 381, dtype: object
382 PassengerId                   383
Survived                        0
Pclass                          3
Name           Tikkanen, Mr. Juho
Sex                          male
Age                          32.0
SibSp                           0
Parch                           0
Ticket          STON/O 2. 3101293
Fare                        7.925
Cabin                         NaN
Embarked                        S
Name: 382, dtype: object
383 PassengerId                                                  384
Survived                                                       1
Pclass                                                         1
Name           Holverson, Mrs. Alexander Oskar (Mary Aline To...
Sex                                                       female
Age                                                         35.0
SibSp                                                          1
Parch                                                          0
Ticket                                                    113789
Fare                                                        52.0
Cabin                                                        NaN
Embarked                                                       S
Name: 383, dtype: object
384 PassengerId                       385
Survived                            0
Pclass                              3
Name           Plotcharsky, Mr. Vasil
Sex                              male
Age                               NaN
SibSp                               0
Parch                               0
Ticket                         349227
Fare                           7.8958
Cabin                             NaN
Embarked                            S
Name: 384, dtype: object
385 PassengerId                          386
Survived                               0
Pclass                                 2
Name           Davies, Mr. Charles Henry
Sex                                 male
Age                                 18.0
SibSp                                  0
Parch                                  0
Ticket                      S.O.C. 14879
Fare                                73.5
Cabin                                NaN
Embarked                               S
Name: 385, dtype: object
386 PassengerId                                387
Survived                                     0
Pclass                                       3
Name           Goodwin, Master. Sidney Leonard
Sex                                       male
Age                                        1.0
SibSp                                        5
Parch                                        2
Ticket                                 CA 2144
Fare                                      46.9
Cabin                                      NaN
Embarked                                     S
Name: 386, dtype: object
387 PassengerId                 388
Survived                      1
Pclass                        2
Name           Buss, Miss. Kate
Sex                      female
Age                        36.0
SibSp                         0
Parch                         0
Ticket                    27849
Fare                       13.0
Cabin                       NaN
Embarked                      S
Name: 387, dtype: object
388 PassengerId                     389
Survived                          0
Pclass                            3
Name           Sadlier, Mr. Matthew
Sex                            male
Age                             NaN
SibSp                             0
Parch                             0
Ticket                       367655
Fare                         7.7292
Cabin                           NaN
Embarked                          Q
Name: 388, dtype: object
389 PassengerId                      390
Survived                           1
Pclass                             2
Name           Lehmann, Miss. Bertha
Sex                           female
Age                             17.0
SibSp                              0
Parch                              0
Ticket                       SC 1748
Fare                            12.0
Cabin                            NaN
Embarked                           C
Name: 389, dtype: object
390 PassengerId                           391
Survived                                1
Pclass                                  1
Name           Carter, Mr. William Ernest
Sex                                  male
Age                                  36.0
SibSp                                   1
Parch                                   2
Ticket                             113760
Fare                                120.0
Cabin                             B96 B98
Embarked                                S
Name: 390, dtype: object
391 PassengerId                       392
Survived                            1
Pclass                              3
Name           Jansson, Mr. Carl Olof
Sex                              male
Age                              21.0
SibSp                               0
Parch                               0
Ticket                         350034
Fare                           7.7958
Cabin                             NaN
Embarked                            S
Name: 391, dtype: object
392 PassengerId                             393
Survived                                  0
Pclass                                    3
Name           Gustafsson, Mr. Johan Birger
Sex                                    male
Age                                    28.0
SibSp                                     2
Parch                                     0
Ticket                              3101277
Fare                                  7.925
Cabin                                   NaN
Embarked                                  S
Name: 392, dtype: object
393 PassengerId                       394
Survived                            1
Pclass                              1
Name           Newell, Miss. Marjorie
Sex                            female
Age                              23.0
SibSp                               1
Parch                               0
Ticket                          35273
Fare                          113.275
Cabin                             D36
Embarked                            C
Name: 393, dtype: object
394 PassengerId                                                  395
Survived                                                       1
Pclass                                                         3
Name           Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
Sex                                                       female
Age                                                         24.0
SibSp                                                          0
Parch                                                          2
Ticket                                                   PP 9549
Fare                                                        16.7
Cabin                                                         G6
Embarked                                                       S
Name: 394, dtype: object
395 PassengerId                    396
Survived                         0
Pclass                           3
Name           Johansson, Mr. Erik
Sex                           male
Age                           22.0
SibSp                            0
Parch                            0
Ticket                      350052
Fare                        7.7958
Cabin                          NaN
Embarked                         S
Name: 395, dtype: object
396 PassengerId                    397
Survived                         0
Pclass                           3
Name           Olsson, Miss. Elina
Sex                         female
Age                           31.0
SibSp                            0
Parch                            0
Ticket                      350407
Fare                        7.8542
Cabin                          NaN
Embarked                         S
Name: 396, dtype: object
397 PassengerId                        398
Survived                             0
Pclass                               2
Name           McKane, Mr. Peter David
Sex                               male
Age                               46.0
SibSp                                0
Parch                                0
Ticket                           28403
Fare                              26.0
Cabin                              NaN
Embarked                             S
Name: 397, dtype: object
398 PassengerId                 399
Survived                      0
Pclass                        2
Name           Pain, Dr. Alfred
Sex                        male
Age                        23.0
SibSp                         0
Parch                         0
Ticket                   244278
Fare                       10.5
Cabin                       NaN
Embarked                      S
Name: 398, dtype: object
399 PassengerId                                 400
Survived                                      1
Pclass                                        2
Name           Trout, Mrs. William H (Jessie L)
Sex                                      female
Age                                        28.0
SibSp                                         0
Parch                                         0
Ticket                                   240929
Fare                                      12.65
Cabin                                       NaN
Embarked                                      S
Name: 399, dtype: object
400 PassengerId                   401
Survived                        1
Pclass                          3
Name           Niskanen, Mr. Juha
Sex                          male
Age                          39.0
SibSp                           0
Parch                           0
Ticket          STON/O 2. 3101289
Fare                        7.925
Cabin                         NaN
Embarked                        S
Name: 400, dtype: object
401 PassengerId                402
Survived                     0
Pclass                       3
Name           Adams, Mr. John
Sex                       male
Age                       26.0
SibSp                        0
Parch                        0
Ticket                  341826
Fare                      8.05
Cabin                      NaN
Embarked                     S
Name: 401, dtype: object
402 PassengerId                         403
Survived                              0
Pclass                                3
Name           Jussila, Miss. Mari Aina
Sex                              female
Age                                21.0
SibSp                                 1
Parch                                 0
Ticket                             4137
Fare                              9.825
Cabin                               NaN
Embarked                              S
Name: 402, dtype: object
403 PassengerId                               404
Survived                                    0
Pclass                                      3
Name           Hakkarainen, Mr. Pekka Pietari
Sex                                      male
Age                                      28.0
SibSp                                       1
Parch                                       0
Ticket                       STON/O2. 3101279
Fare                                    15.85
Cabin                                     NaN
Embarked                                    S
Name: 403, dtype: object
404 PassengerId                        405
Survived                             0
Pclass                               3
Name           Oreskovic, Miss. Marija
Sex                             female
Age                               20.0
SibSp                                0
Parch                                0
Ticket                          315096
Fare                            8.6625
Cabin                              NaN
Embarked                             S
Name: 404, dtype: object
405 PassengerId                   406
Survived                        0
Pclass                          2
Name           Gale, Mr. Shadrach
Sex                          male
Age                          34.0
SibSp                           1
Parch                           0
Ticket                      28664
Fare                         21.0
Cabin                         NaN
Embarked                        S
Name: 405, dtype: object
406 PassengerId                                 407
Survived                                      0
Pclass                                        3
Name           Widegren, Mr. Carl/Charles Peter
Sex                                        male
Age                                        51.0
SibSp                                         0
Parch                                         0
Ticket                                   347064
Fare                                       7.75
Cabin                                       NaN
Embarked                                      S
Name: 406, dtype: object
407 PassengerId                               408
Survived                                    1
Pclass                                      2
Name           Richards, Master. William Rowe
Sex                                      male
Age                                       3.0
SibSp                                       1
Parch                                       1
Ticket                                  29106
Fare                                    18.75
Cabin                                     NaN
Embarked                                    S
Name: 407, dtype: object
408 PassengerId                                  409
Survived                                       0
Pclass                                         3
Name           Birkeland, Mr. Hans Martin Monsen
Sex                                         male
Age                                         21.0
SibSp                                          0
Parch                                          0
Ticket                                    312992
Fare                                       7.775
Cabin                                        NaN
Embarked                                       S
Name: 408, dtype: object
409 PassengerId                   410
Survived                        0
Pclass                          3
Name           Lefebre, Miss. Ida
Sex                        female
Age                           NaN
SibSp                           3
Parch                           1
Ticket                       4133
Fare                      25.4667
Cabin                         NaN
Embarked                        S
Name: 409, dtype: object
410 PassengerId                   411
Survived                        0
Pclass                          3
Name           Sdycoff, Mr. Todor
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket                     349222
Fare                       7.8958
Cabin                         NaN
Embarked                        S
Name: 410, dtype: object
411 PassengerId                412
Survived                     0
Pclass                       3
Name           Hart, Mr. Henry
Sex                       male
Age                        NaN
SibSp                        0
Parch                        0
Ticket                  394140
Fare                    6.8583
Cabin                      NaN
Embarked                     Q
Name: 411, dtype: object
412 PassengerId                       413
Survived                            1
Pclass                              1
Name           Minahan, Miss. Daisy E
Sex                            female
Age                              33.0
SibSp                               1
Parch                               0
Ticket                          19928
Fare                             90.0
Cabin                             C78
Embarked                            Q
Name: 412, dtype: object
413 PassengerId                               414
Survived                                    0
Pclass                                      2
Name           Cunningham, Mr. Alfred Fleming
Sex                                      male
Age                                       NaN

505 PassengerId                                           506
Survived                                                0
Pclass                                                  1
Name           Penasco y Castellana, Mr. Victor de Satode
Sex                                                  male
Age                                                  18.0
SibSp                                                   1
Parch                                                   0
Ticket                                           PC 17758
Fare                                                108.9
Cabin                                                 C65
Embarked                                                C
Name: 505, dtype: object
506 PassengerId                                              507
Survived                                                   1
Pclass                                                     2
Name           Quick, Mrs. Frederick Charles (Jane Richards)
Sex                                                   female
Age                                                     33.0
SibSp                                                      0
Parch                                                      2
Ticket                                                 26360
Fare                                                    26.0
Cabin                                                    NaN
Embarked                                                   S
Name: 506, dtype: object
507 PassengerId                                              508
Survived                                                   1
Pclass                                                     1
Name           Bradley, Mr. George ("George Arthur Brayton")
Sex                                                     male
Age                                                      NaN
SibSp                                                      0
Parch                                                      0
Ticket                                                111427
Fare                                                   26.55
Cabin                                                    NaN
Embarked                                                   S
Name: 507, dtype: object
508 PassengerId                         509
Survived                              0
Pclass                                3
Name           Olsen, Mr. Henry Margido
Sex                                male
Age                                28.0
SibSp                                 0
Parch                                 0
Ticket                           C 4001
Fare                             22.525
Cabin                               NaN
Embarked                              S
Name: 508, dtype: object
509 PassengerId               510
Survived                    1
Pclass                      3
Name           Lang, Mr. Fang
Sex                      male
Age                      26.0
SibSp                       0
Parch                       0
Ticket                   1601
Fare                  56.4958
Cabin                     NaN
Embarked                    S
Name: 509, dtype: object
510 PassengerId                         511
Survived                              1
Pclass                                3
Name           Daly, Mr. Eugene Patrick
Sex                                male
Age                                29.0
SibSp                                 0
Parch                                 0
Ticket                           382651
Fare                               7.75
Cabin                               NaN
Embarked                              Q
Name: 510, dtype: object
511 PassengerId                  512
Survived                       0
Pclass                         3
Name           Webber, Mr. James
Sex                         male
Age                          NaN
SibSp                          0
Parch                          0
Ticket          SOTON/OQ 3101316
Fare                        8.05
Cabin                        NaN
Embarked                       S
Name: 511, dtype: object
512 PassengerId                          513
Survived                               1
Pclass                                 1
Name           McGough, Mr. James Robert
Sex                                 male
Age                                 36.0
SibSp                                  0
Parch                                  0
Ticket                          PC 17473
Fare                             26.2875
Cabin                                E25
Embarked                               S
Name: 512, dtype: object
513 PassengerId                                               514
Survived                                                    1
Pclass                                                      1
Name           Rothschild, Mrs. Martin (Elizabeth L. Barrett)
Sex                                                    female
Age                                                      54.0
SibSp                                                       1
Parch                                                       0
Ticket                                               PC 17603
Fare                                                     59.4
Cabin                                                     NaN
Embarked                                                    C
Name: 513, dtype: object
514 PassengerId                  515
Survived                       0
Pclass                         3
Name           Coleff, Mr. Satio
Sex                         male
Age                         24.0
SibSp                          0
Parch                          0
Ticket                    349209
Fare                      7.4958
Cabin                        NaN
Embarked                       S
Name: 514, dtype: object
515 PassengerId                             516
Survived                                  0
Pclass                                    1
Name           Walker, Mr. William Anderson
Sex                                    male
Age                                    47.0
SibSp                                     0
Parch                                     0
Ticket                                36967
Fare                                34.0208
Cabin                                   D46
Embarked                                  S
Name: 515, dtype: object
516 PassengerId                             517
Survived                                  1
Pclass                                    2
Name           Lemore, Mrs. (Amelia Milley)
Sex                                  female
Age                                    34.0
SibSp                                     0
Parch                                     0
Ticket                           C.A. 34260
Fare                                   10.5
Cabin                                   F33
Embarked                                  S
Name: 516, dtype: object
517 PassengerId                  518
Survived                       0
Pclass                         3
Name           Ryan, Mr. Patrick
Sex                         male
Age                          NaN
SibSp                          0
Parch                          0
Ticket                    371110
Fare                       24.15
Cabin                        NaN
Embarked                       Q
Name: 517, dtype: object
518 PassengerId                                                  519
Survived                                                       1
Pclass                                                         2
Name           Angle, Mrs. William A (Florence "Mary" Agnes H...
Sex                                                       female
Age                                                         36.0
SibSp                                                          1
Parch                                                          0
Ticket                                                    226875
Fare                                                        26.0
Cabin                                                        NaN
Embarked                                                       S
Name: 518, dtype: object
519 PassengerId                    520
Survived                         0
Pclass                           3
Name           Pavlovic, Mr. Stefo
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      349242
Fare                        7.8958
Cabin                          NaN
Embarked                         S
Name: 519, dtype: object
520 PassengerId                      521
Survived                           1
Pclass                             1
Name           Perreault, Miss. Anne
Sex                           female
Age                             30.0
SibSp                              0
Parch                              0
Ticket                         12749
Fare                            93.5
Cabin                            B73
Embarked                           S
Name: 520, dtype: object
521 PassengerId                522
Survived                     0
Pclass                       3
Name           Vovk, Mr. Janko
Sex                       male
Age                       22.0
SibSp                        0
Parch                        0
Ticket                  349252
Fare                    7.8958
Cabin                      NaN
Embarked                     S
Name: 521, dtype: object
522 PassengerId                   523
Survived                        0
Pclass                          3
Name           Lahoud, Mr. Sarkis
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket                       2624
Fare                        7.225
Cabin                         NaN
Embarked                        C
Name: 522, dtype: object
523 PassengerId                                                524
Survived                                                     1
Pclass                                                       1
Name           Hippach, Mrs. Louis Albert (Ida Sophia Fischer)
Sex                                                     female
Age                                                       44.0
SibSp                                                        0
Parch                                                        1
Ticket                                                  111361
Fare                                                   57.9792
Cabin                                                      B18
Embarked                                                     C
Name: 523, dtype: object
524 PassengerId                  525
Survived                       0
Pclass                         3
Name           Kassem, Mr. Fared
Sex                         male
Age                          NaN
SibSp                          0
Parch                          0
Ticket                      2700
Fare                      7.2292
Cabin                        NaN
Embarked                       C
Name: 524, dtype: object
525 PassengerId                   526
Survived                        0
Pclass                          3
Name           Farrell, Mr. James
Sex                          male
Age                          40.5
SibSp                           0
Parch                           0
Ticket                     367232
Fare                         7.75
Cabin                         NaN
Embarked                        Q
Name: 525, dtype: object
526 PassengerId                     527
Survived                          1
Pclass                            2
Name           Ridsdale, Miss. Lucy
Sex                          female
Age                            50.0
SibSp                             0
Parch                             0
Ticket                  W./C. 14258
Fare                           10.5
Cabin                           NaN
Embarked                          S
Name: 526, dtype: object
527 PassengerId                   528
Survived                        0
Pclass                          1
Name           Farthing, Mr. John
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket                   PC 17483
Fare                     221.7792
Cabin                         C95
Embarked                        S
Name: 527, dtype: object
528 PassengerId                          529
Survived                               0
Pclass                                 3
Name           Salonen, Mr. Johan Werner
Sex                                 male
Age                                 39.0
SibSp                                  0
Parch                                  0
Ticket                           3101296
Fare                               7.925
Cabin                                NaN
Embarked                               S
Name: 528, dtype: object
529 PassengerId                            530
Survived                                 0
Pclass                                   2
Name           Hocking, Mr. Richard George
Sex                                   male
Age                                   23.0
SibSp                                    2
Parch                                    1
Ticket                               29104
Fare                                  11.5
Cabin                                  NaN
Embarked                                 S
Name: 529, dtype: object
530 PassengerId                         531
Survived                              1
Pclass                                2
Name           Quick, Miss. Phyllis May
Sex                              female
Age                                 2.0
SibSp                                 1
Parch                                 1
Ticket                            26360
Fare                               26.0
Cabin                               NaN
Embarked                              S
Name: 530, dtype: object
531 PassengerId                  532
Survived                       0
Pclass                         3
Name           Toufik, Mr. Nakli
Sex                         male
Age                          NaN
SibSp                          0
Parch                          0
Ticket                      2641
Fare                      7.2292
Cabin                        NaN
Embarked                       C
Name: 531, dtype: object
532 PassengerId                     533
Survived                          0
Pclass                            3
Name           Elias, Mr. Joseph Jr
Sex                            male
Age                            17.0
SibSp                             1
Parch                             1
Ticket                         2690
Fare                         7.2292
Cabin                           NaN
Embarked                          C
Name: 532, dtype: object
533 PassengerId                                       534
Survived                                            1
Pclass                                              3
Name           Peter, Mrs. Catherine (Catherine Rizk)
Sex                                            female
Age                                               NaN
SibSp                                               0
Parch                                               2
Ticket                                           2668
Fare                                          22.3583
Cabin                                             NaN
Embarked                                            C
Name: 533, dtype: object
534 PassengerId                    535
Survived                         0
Pclass                           3
Name           Cacic, Miss. Marija
Sex                         female
Age                           30.0
SibSp                            0
Parch                            0
Ticket                      315084
Fare                        8.6625
Cabin                          NaN
Embarked                         S
Name: 534, dtype: object
535 PassengerId                       536
Survived                            1
Pclass                              2
Name           Hart, Miss. Eva Miriam
Sex                            female
Age                               7.0
SibSp                               0
Parch                               2
Ticket                   F.C.C. 13529
Fare                            26.25
Cabin                             NaN
Embarked                            S
Name: 535, dtype: object
536 PassengerId                                  537
Survived                                       0
Pclass                                         1
Name           Butt, Major. Archibald Willingham
Sex                                         male
Age                                         45.0
SibSp                                          0
Parch                                          0
Ticket                                    113050
Fare                                       26.55
Cabin                                        B38
Embarked                                       S
Name: 536, dtype: object
537 PassengerId                    538
Survived                         1
Pclass                           1
Name           LeRoy, Miss. Bertha
Sex                         female
Age                           30.0
SibSp                            0
Parch                            0
Ticket                    PC 17761
Fare                       106.425
Cabin                          NaN
Embarked                         C
Name: 537, dtype: object
538 PassengerId                         539
Survived                              0
Pclass                                3
Name           Risien, Mr. Samuel Beard
Sex                                male
Age                                 NaN
SibSp                                 0
Parch                                 0
Ticket                           364498
Fare                               14.5
Cabin                               NaN
Embarked                              S
Name: 538, dtype: object
539 PassengerId                                   540
Survived                                        1
Pclass                                          1
Name           Frolicher, Miss. Hedwig Margaritha
Sex                                        female
Age                                          22.0
SibSp                                           0
Parch                                           2
Ticket                                      13568
Fare                                         49.5
Cabin                                         B39
Embarked                                        C
Name: 539, dtype: object
540 PassengerId                        541
Survived                             1
Pclass                               1
Name           Crosby, Miss. Harriet R
Sex                             female
Age                               36.0
SibSp                                0
Parch                                2
Ticket                       WE/P 5735
Fare                              71.0
Cabin                              B22
Embarked                             S
Name: 540, dtype: object
541 PassengerId                                     542
Survived                                          0
Pclass                                            3
Name           Andersson, Miss. Ingeborg Constanzia
Sex                                          female
Age                                             9.0
SibSp                                             4
Parch                                             2
Ticket                                       347082
Fare                                         31.275
Cabin                                           NaN
Embarked                                          S
Name: 541, dtype: object
542 PassengerId                                  543
Survived                                       0

Name: 654, dtype: object
655 PassengerId                          656
Survived                               0
Pclass                                 2
Name           Hickman, Mr. Leonard Mark
Sex                                 male
Age                                 24.0
SibSp                                  2
Parch                                  0
Ticket                      S.O.C. 14879
Fare                                73.5
Cabin                                NaN
Embarked                               S
Name: 655, dtype: object
656 PassengerId                      657
Survived                           0
Pclass                             3
Name           Radeff, Mr. Alexander
Sex                             male
Age                              NaN
SibSp                              0
Parch                              0
Ticket                        349223
Fare                          7.8958
Cabin                            NaN
Embarked                           S
Name: 656, dtype: object
657 PassengerId                              658
Survived                                   0
Pclass                                     3
Name           Bourke, Mrs. John (Catherine)
Sex                                   female
Age                                     32.0
SibSp                                      1
Parch                                      1
Ticket                                364849
Fare                                    15.5
Cabin                                    NaN
Embarked                                   Q
Name: 657, dtype: object
658 PassengerId                             659
Survived                                  0
Pclass                                    2
Name           Eitemiller, Mr. George Floyd
Sex                                    male
Age                                    23.0
SibSp                                     0
Parch                                     0
Ticket                                29751
Fare                                   13.0
Cabin                                   NaN
Embarked                                  S
Name: 658, dtype: object
659 PassengerId                           660
Survived                                0
Pclass                                  1
Name           Newell, Mr. Arthur Webster
Sex                                  male
Age                                  58.0
SibSp                                   0
Parch                                   2
Ticket                              35273
Fare                              113.275
Cabin                                 D48
Embarked                                C
Name: 659, dtype: object
660 PassengerId                              661
Survived                                   1
Pclass                                     1
Name           Frauenthal, Dr. Henry William
Sex                                     male
Age                                     50.0
SibSp                                      2
Parch                                      0
Ticket                              PC 17611
Fare                                  133.65
Cabin                                    NaN
Embarked                                   S
Name: 660, dtype: object
661 PassengerId                  662
Survived                       0
Pclass                         3
Name           Badt, Mr. Mohamed
Sex                         male
Age                         40.0
SibSp                          0
Parch                          0
Ticket                      2623
Fare                       7.225
Cabin                        NaN
Embarked                       C
Name: 661, dtype: object
662 PassengerId                           663
Survived                                0
Pclass                                  1
Name           Colley, Mr. Edward Pomeroy
Sex                                  male
Age                                  47.0
SibSp                                   0
Parch                                   0
Ticket                               5727
Fare                              25.5875
Cabin                                 E58
Embarked                                S
Name: 662, dtype: object
663 PassengerId                 664
Survived                      0
Pclass                        3
Name           Coleff, Mr. Peju
Sex                        male
Age                        36.0
SibSp                         0
Parch                         0
Ticket                   349210
Fare                     7.4958
Cabin                       NaN
Embarked                      S
Name: 663, dtype: object
664 PassengerId                            665
Survived                                 1
Pclass                                   3
Name           Lindqvist, Mr. Eino William
Sex                                   male
Age                                   20.0
SibSp                                    1
Parch                                    0
Ticket                   STON/O 2. 3101285
Fare                                 7.925
Cabin                                  NaN
Embarked                                 S
Name: 664, dtype: object
665 PassengerId                   666
Survived                        0
Pclass                          2
Name           Hickman, Mr. Lewis
Sex                          male
Age                          32.0
SibSp                           2
Parch                           0
Ticket               S.O.C. 14879
Fare                         73.5
Cabin                         NaN
Embarked                        S
Name: 665, dtype: object
666 PassengerId                            667
Survived                                 0
Pclass                                   2
Name           Butler, Mr. Reginald Fenton
Sex                                   male
Age                                   25.0
SibSp                                    0
Parch                                    0
Ticket                              234686
Fare                                  13.0
Cabin                                  NaN
Embarked                                 S
Name: 666, dtype: object
667 PassengerId                           668
Survived                                0
Pclass                                  3
Name           Rommetvedt, Mr. Knud Paust
Sex                                  male
Age                                   NaN
SibSp                                   0
Parch                                   0
Ticket                             312993
Fare                                7.775
Cabin                                 NaN
Embarked                                S
Name: 667, dtype: object
668 PassengerId                669
Survived                     0
Pclass                       3
Name           Cook, Mr. Jacob
Sex                       male
Age                       43.0
SibSp                        0
Parch                        0
Ticket                A/5 3536
Fare                      8.05
Cabin                      NaN
Embarked                     S
Name: 668, dtype: object
669 PassengerId                                                  670
Survived                                                       1
Pclass                                                         1
Name           Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)
Sex                                                       female
Age                                                          NaN
SibSp                                                          1
Parch                                                          0
Ticket                                                     19996
Fare                                                        52.0
Cabin                                                       C126
Embarked                                                       S
Name: 669, dtype: object
670 PassengerId                                                  671
Survived                                                       1
Pclass                                                         2
Name           Brown, Mrs. Thomas William Solomon (Elizabeth ...
Sex                                                       female
Age                                                         40.0
SibSp                                                          1
Parch                                                          1
Ticket                                                     29750
Fare                                                        39.0
Cabin                                                        NaN
Embarked                                                       S
Name: 670, dtype: object
671 PassengerId                       672
Survived                            0
Pclass                              1
Name           Davidson, Mr. Thornton
Sex                              male
Age                              31.0
SibSp                               1
Parch                               0
Ticket                     F.C. 12750
Fare                             52.0
Cabin                             B71
Embarked                            S
Name: 671, dtype: object
672 PassengerId                            673
Survived                                 0
Pclass                                   2
Name           Mitchell, Mr. Henry Michael
Sex                                   male
Age                                   70.0
SibSp                                    0
Parch                                    0
Ticket                          C.A. 24580
Fare                                  10.5
Cabin                                  NaN
Embarked                                 S
Name: 672, dtype: object
673 PassengerId                      674
Survived                           1
Pclass                             2
Name           Wilhelms, Mr. Charles
Sex                             male
Age                             31.0
SibSp                              0
Parch                              0
Ticket                        244270
Fare                            13.0
Cabin                            NaN
Embarked                           S
Name: 673, dtype: object
674 PassengerId                           675
Survived                                0
Pclass                                  2
Name           Watson, Mr. Ennis Hastings
Sex                                  male
Age                                   NaN
SibSp                                   0
Parch                                   0
Ticket                             239856
Fare                                  0.0
Cabin                                 NaN
Embarked                                S
Name: 674, dtype: object
675 PassengerId                               676
Survived                                    0
Pclass                                      3
Name           Edvardsson, Mr. Gustaf Hjalmar
Sex                                      male
Age                                      18.0
SibSp                                       0
Parch                                       0
Ticket                                 349912
Fare                                    7.775
Cabin                                     NaN
Embarked                                    S
Name: 675, dtype: object
676 PassengerId                              677
Survived                                   0
Pclass                                     3
Name           Sawyer, Mr. Frederick Charles
Sex                                     male
Age                                     24.5
SibSp                                      0
Parch                                      0
Ticket                                342826
Fare                                    8.05
Cabin                                    NaN
Embarked                                   S
Name: 676, dtype: object
677 PassengerId                        678
Survived                             1
Pclass                               3
Name           Turja, Miss. Anna Sofia
Sex                             female
Age                               18.0
SibSp                                0
Parch                                0
Ticket                            4138
Fare                            9.8417
Cabin                              NaN
Embarked                             S
Name: 677, dtype: object
678 PassengerId                                        679
Survived                                             0
Pclass                                               3
Name           Goodwin, Mrs. Frederick (Augusta Tyler)
Sex                                             female
Age                                               43.0
SibSp                                                1
Parch                                                6
Ticket                                         CA 2144
Fare                                              46.9
Cabin                                              NaN
Embarked                                             S
Name: 678, dtype: object
679 PassengerId                                   680
Survived                                        1
Pclass                                          1
Name           Cardeza, Mr. Thomas Drake Martinez
Sex                                          male
Age                                          36.0
SibSp                                           0
Parch                                           1
Ticket                                   PC 17755
Fare                                     512.3292
Cabin                                 B51 B53 B55
Embarked                                        C
Name: 679, dtype: object
680 PassengerId                    681
Survived                         0
Pclass                           3
Name           Peters, Miss. Katie
Sex                         female
Age                            NaN
SibSp                            0
Parch                            0
Ticket                      330935
Fare                        8.1375
Cabin                          NaN
Embarked                         Q
Name: 680, dtype: object
681 PassengerId                   682
Survived                        1
Pclass                          1
Name           Hassab, Mr. Hammad
Sex                          male
Age                          27.0
SibSp                           0
Parch                           0
Ticket                   PC 17572
Fare                      76.7292
Cabin                         D49
Embarked                        C
Name: 681, dtype: object
682 PassengerId                            683
Survived                                 0
Pclass                                   3
Name           Olsvigen, Mr. Thor Anderson
Sex                                   male
Age                                   20.0
SibSp                                    0
Parch                                    0
Ticket                                6563
Fare                                 9.225
Cabin                                  NaN
Embarked                                 S
Name: 682, dtype: object
683 PassengerId                            684
Survived                                 0
Pclass                                   3
Name           Goodwin, Mr. Charles Edward
Sex                                   male
Age                                   14.0
SibSp                                    5
Parch                                    2
Ticket                             CA 2144
Fare                                  46.9
Cabin                                  NaN
Embarked                                 S
Name: 683, dtype: object
684 PassengerId                                  685
Survived                                       0
Pclass                                         2
Name           Brown, Mr. Thomas William Solomon
Sex                                         male
Age                                         60.0
SibSp                                          1
Parch                                          1
Ticket                                     29750
Fare                                        39.0
Cabin                                        NaN
Embarked                                       S
Name: 684, dtype: object
685 PassengerId                                       686
Survived                                            0
Pclass                                              2
Name           Laroche, Mr. Joseph Philippe Lemercier
Sex                                              male
Age                                              25.0
SibSp                                               1
Parch                                               2
Ticket                                  SC/Paris 2123
Fare                                          41.5792
Cabin                                             NaN
Embarked                                            C
Name: 685, dtype: object
686 PassengerId                         687
Survived                              0
Pclass                                3
Name           Panula, Mr. Jaako Arnold
Sex                                male
Age                                14.0
SibSp                                 4
Parch                                 1
Ticket                          3101295
Fare                            39.6875
Cabin                               NaN
Embarked                              S
Name: 686, dtype: object
687 PassengerId                  688
Survived                       0
Pclass                         3
Name           Dakic, Mr. Branko
Sex                         male
Age                         19.0
SibSp                          0
Parch                          0
Ticket                    349228
Fare                     10.1708
Cabin                        NaN
Embarked                       S
Name: 687, dtype: object
688 PassengerId                                689
Survived                                     0
Pclass                                       3
Name           Fischer, Mr. Eberhard Thelander
Sex                                       male
Age                                       18.0
SibSp                                        0
Parch                                        0
Ticket                                  350036
Fare                                    7.7958
Cabin                                      NaN
Embarked                                     S
Name: 688, dtype: object
689 PassengerId                                  690
Survived                                       1
Pclass                                         1
Name           Madill, Miss. Georgette Alexandra
Sex                                       female
Age                                         15.0
SibSp                                          0
Parch                                          1
Ticket                                     24160
Fare                                    211.3375
Cabin                                         B5
Embarked                                       S
Name: 689, dtype: object
690 PassengerId                        691
Survived                             1
Pclass                               1
Name           Dick, Mr. Albert Adrian
Sex                               male
Age                               31.0
SibSp                                1
Parch                                0
Ticket                           17474
Fare                              57.0
Cabin                              B20
Embarked                             S
Name: 690, dtype: object
691 PassengerId                   692
Survived                        1
Pclass                          3
Name           Karun, Miss. Manca
Sex                        female
Age                           4.0
SibSp                           0
Parch                           1
Ticket                     349256
Fare                      13.4167
Cabin                         NaN

Name: 773, dtype: object
774 PassengerId                                      775
Survived                                           1
Pclass                                             2
Name           Hocking, Mrs. Elizabeth (Eliza Needs)
Sex                                           female
Age                                             54.0
SibSp                                              1
Parch                                              3
Ticket                                         29105
Fare                                            23.0
Cabin                                            NaN
Embarked                                           S
Name: 774, dtype: object
775 PassengerId                                        776
Survived                                             0
Pclass                                               3
Name           Myhrman, Mr. Pehr Fabian Oliver Malkolm
Sex                                               male
Age                                               18.0
SibSp                                                0
Parch                                                0
Ticket                                          347078
Fare                                              7.75
Cabin                                              NaN
Embarked                                             S
Name: 775, dtype: object
776 PassengerId                 777
Survived                      0
Pclass                        3
Name           Tobin, Mr. Roger
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   383121
Fare                       7.75
Cabin                       F38
Embarked                      Q
Name: 776, dtype: object
777 PassengerId                              778
Survived                                   1
Pclass                                     3
Name           Emanuel, Miss. Virginia Ethel
Sex                                   female
Age                                      5.0
SibSp                                      0
Parch                                      0
Ticket                                364516
Fare                                  12.475
Cabin                                    NaN
Embarked                                   S
Name: 777, dtype: object
778 PassengerId                        779
Survived                             0
Pclass                               3
Name           Kilgannon, Mr. Thomas J
Sex                               male
Age                                NaN
SibSp                                0
Parch                                0
Ticket                           36865
Fare                            7.7375
Cabin                              NaN
Embarked                             Q
Name: 778, dtype: object
779 PassengerId                                                  780
Survived                                                       1
Pclass                                                         1
Name           Robert, Mrs. Edward Scott (Elisabeth Walton Mc...
Sex                                                       female
Age                                                         43.0
SibSp                                                          0
Parch                                                          1
Ticket                                                     24160
Fare                                                    211.3375
Cabin                                                         B3
Embarked                                                       S
Name: 779, dtype: object
780 PassengerId                     781
Survived                          1
Pclass                            3
Name           Ayoub, Miss. Banoura
Sex                          female
Age                            13.0
SibSp                             0
Parch                             0
Ticket                         2687
Fare                         7.2292
Cabin                           NaN
Embarked                          C
Name: 780, dtype: object
781 PassengerId                                          782
Survived                                               1
Pclass                                                 1
Name           Dick, Mrs. Albert Adrian (Vera Gillespie)
Sex                                               female
Age                                                 17.0
SibSp                                                  1
Parch                                                  0
Ticket                                             17474
Fare                                                57.0
Cabin                                                B20
Embarked                                               S
Name: 781, dtype: object
782 PassengerId                       783
Survived                            0
Pclass                              1
Name           Long, Mr. Milton Clyde
Sex                              male
Age                              29.0
SibSp                               0
Parch                               0
Ticket                         113501
Fare                             30.0
Cabin                              D6
Embarked                            S
Name: 782, dtype: object
783 PassengerId                       784
Survived                            0
Pclass                              3
Name           Johnston, Mr. Andrew G
Sex                              male
Age                               NaN
SibSp                               1
Parch                               2
Ticket                     W./C. 6607
Fare                            23.45
Cabin                             NaN
Embarked                            S
Name: 783, dtype: object
784 PassengerId                   785
Survived                        0
Pclass                          3
Name             Ali, Mr. William
Sex                          male
Age                          25.0
SibSp                           0
Parch                           0
Ticket         SOTON/O.Q. 3101312
Fare                         7.05
Cabin                         NaN
Embarked                        S
Name: 784, dtype: object
785 PassengerId                                   786
Survived                                        0
Pclass                                          3
Name           Harmer, Mr. Abraham (David Lishin)
Sex                                          male
Age                                          25.0
SibSp                                           0
Parch                                           0
Ticket                                     374887
Fare                                         7.25
Cabin                                         NaN
Embarked                                        S
Name: 785, dtype: object
786 PassengerId                          787
Survived                               1
Pclass                                 3
Name           Sjoblom, Miss. Anna Sofia
Sex                               female
Age                                 18.0
SibSp                                  0
Parch                                  0
Ticket                           3101265
Fare                              7.4958
Cabin                                NaN
Embarked                               S
Name: 786, dtype: object
787 PassengerId                          788
Survived                               0
Pclass                                 3
Name           Rice, Master. George Hugh
Sex                                 male
Age                                  8.0
SibSp                                  4
Parch                                  1
Ticket                            382652
Fare                              29.125
Cabin                                NaN
Embarked                               Q
Name: 787, dtype: object
788 PassengerId                           789
Survived                                1
Pclass                                  3
Name           Dean, Master. Bertram Vere
Sex                                  male
Age                                   1.0
SibSp                                   1
Parch                                   2
Ticket                          C.A. 2315
Fare                               20.575
Cabin                                 NaN
Embarked                                S
Name: 788, dtype: object
789 PassengerId                         790
Survived                              0
Pclass                                1
Name           Guggenheim, Mr. Benjamin
Sex                                male
Age                                46.0
SibSp                                 0
Parch                                 0
Ticket                         PC 17593
Fare                               79.2
Cabin                           B82 B84
Embarked                              C
Name: 789, dtype: object
790 PassengerId                         791
Survived                              0
Pclass                                3
Name           Keane, Mr. Andrew "Andy"
Sex                                male
Age                                 NaN
SibSp                                 0
Parch                                 0
Ticket                            12460
Fare                               7.75
Cabin                               NaN
Embarked                              Q
Name: 790, dtype: object
791 PassengerId                    792
Survived                         0
Pclass                           2
Name           Gaskell, Mr. Alfred
Sex                           male
Age                           16.0
SibSp                            0
Parch                            0
Ticket                      239865
Fare                          26.0
Cabin                          NaN
Embarked                         S
Name: 791, dtype: object
792 PassengerId                        793
Survived                             0
Pclass                               3
Name           Sage, Miss. Stella Anna
Sex                             female
Age                                NaN
SibSp                                8
Parch                                2
Ticket                        CA. 2343
Fare                             69.55
Cabin                              NaN
Embarked                             S
Name: 792, dtype: object
793 PassengerId                         794
Survived                              0
Pclass                                1
Name           Hoyt, Mr. William Fisher
Sex                                male
Age                                 NaN
SibSp                                 0
Parch                                 0
Ticket                         PC 17600
Fare                            30.6958
Cabin                               NaN
Embarked                              C
Name: 793, dtype: object
794 PassengerId                      795
Survived                           0
Pclass                             3
Name           Dantcheff, Mr. Ristiu
Sex                             male
Age                             25.0
SibSp                              0
Parch                              0
Ticket                        349203
Fare                          7.8958
Cabin                            NaN
Embarked                           S
Name: 794, dtype: object
795 PassengerId                   796
Survived                        0
Pclass                          2
Name           Otter, Mr. Richard
Sex                          male
Age                          39.0
SibSp                           0
Parch                           0
Ticket                      28213
Fare                         13.0
Cabin                         NaN
Embarked                        S
Name: 795, dtype: object
796 PassengerId                            797
Survived                                 1
Pclass                                   1
Name           Leader, Dr. Alice (Farnham)
Sex                                 female
Age                                   49.0
SibSp                                    0
Parch                                    0
Ticket                               17465
Fare                               25.9292
Cabin                                  D17
Embarked                                 S
Name: 796, dtype: object
797 PassengerId                 798
Survived                      1
Pclass                        3
Name           Osman, Mrs. Mara
Sex                      female
Age                        31.0
SibSp                         0
Parch                         0
Ticket                   349244
Fare                     8.6833
Cabin                       NaN
Embarked                      S
Name: 797, dtype: object
798 PassengerId                             799
Survived                                  0
Pclass                                    3
Name           Ibrahim Shawah, Mr. Yousseff
Sex                                    male
Age                                    30.0
SibSp                                     0
Parch                                     0
Ticket                                 2685
Fare                                 7.2292
Cabin                                   NaN
Embarked                                  C
Name: 798, dtype: object
799 PassengerId                                                  800
Survived                                                       0
Pclass                                                         3
Name           Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...
Sex                                                       female
Age                                                         30.0
SibSp                                                          1
Parch                                                          1
Ticket                                                    345773
Fare                                                       24.15
Cabin                                                        NaN
Embarked                                                       S
Name: 799, dtype: object
800 PassengerId                     801
Survived                          0
Pclass                            2
Name           Ponesell, Mr. Martin
Sex                            male
Age                            34.0
SibSp                             0
Parch                             0
Ticket                       250647
Fare                           13.0
Cabin                           NaN
Embarked                          S
Name: 800, dtype: object
801 PassengerId                                            802
Survived                                                 1
Pclass                                                   2
Name           Collyer, Mrs. Harvey (Charlotte Annie Tate)
Sex                                                 female
Age                                                   31.0
SibSp                                                    1
Parch                                                    1
Ticket                                          C.A. 31921
Fare                                                 26.25
Cabin                                                  NaN
Embarked                                                 S
Name: 801, dtype: object
802 PassengerId                                    803
Survived                                         1
Pclass                                           1
Name           Carter, Master. William Thornton II
Sex                                           male
Age                                           11.0
SibSp                                            1
Parch                                            2
Ticket                                      113760
Fare                                         120.0
Cabin                                      B96 B98
Embarked                                         S
Name: 802, dtype: object
803 PassengerId                                804
Survived                                     1
Pclass                                       3
Name           Thomas, Master. Assad Alexander
Sex                                       male
Age                                       0.42
SibSp                                        0
Parch                                        1
Ticket                                    2625
Fare                                    8.5167
Cabin                                      NaN
Embarked                                     C
Name: 803, dtype: object
804 PassengerId                        805
Survived                             1
Pclass                               3
Name           Hedman, Mr. Oskar Arvid
Sex                               male
Age                               27.0
SibSp                                0
Parch                                0
Ticket                          347089
Fare                             6.975
Cabin                              NaN
Embarked                             S
Name: 804, dtype: object
805 PassengerId                          806
Survived                               0
Pclass                                 3
Name           Johansson, Mr. Karl Johan
Sex                                 male
Age                                 31.0
SibSp                                  0
Parch                                  0
Ticket                            347063
Fare                               7.775
Cabin                                NaN
Embarked                               S
Name: 805, dtype: object
806 PassengerId                       807
Survived                            0
Pclass                              1
Name           Andrews, Mr. Thomas Jr
Sex                              male
Age                              39.0
SibSp                               0
Parch                               0
Ticket                         112050
Fare                              0.0
Cabin                             A36
Embarked                            S
Name: 806, dtype: object
807 PassengerId                                808
Survived                                     0
Pclass                                       3
Name           Pettersson, Miss. Ellen Natalia
Sex                                     female
Age                                       18.0
SibSp                                        0
Parch                                        0
Ticket                                  347087
Fare                                     7.775
Cabin                                      NaN
Embarked                                     S
Name: 807, dtype: object
808 PassengerId                  809
Survived                       0
Pclass                         2
Name           Meyer, Mr. August
Sex                         male
Age                         39.0
SibSp                          0
Parch                          0
Ticket                    248723
Fare                        13.0
Cabin                        NaN
Embarked                       S
Name: 808, dtype: object
809 PassengerId                                               810
Survived                                                    1
Pclass                                                      1
Name           Chambers, Mrs. Norman Campbell (Bertha Griggs)
Sex                                                    female
Age                                                      33.0
SibSp                                                       1
Parch                                                       0
Ticket                                                 113806
Fare                                                     53.1
Cabin                                                      E8
Embarked                                                    S
Name: 809, dtype: object
810 PassengerId                       811
Survived                            0

871 PassengerId                                                 872
Survived                                                      1
Pclass                                                        1
Name           Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
Sex                                                      female
Age                                                        47.0
SibSp                                                         1
Parch                                                         1
Ticket                                                    11751
Fare                                                    52.5542
Cabin                                                       D35
Embarked                                                      S
Name: 871, dtype: object
872 PassengerId                         873
Survived                              0
Pclass                                1
Name           Carlsson, Mr. Frans Olof
Sex                                male
Age                                33.0
SibSp                                 0
Parch                                 0
Ticket                              695
Fare                                5.0
Cabin                       B51 B53 B55
Embarked                              S
Name: 872, dtype: object
873 PassengerId                            874
Survived                                 0
Pclass                                   3
Name           Vander Cruyssen, Mr. Victor
Sex                                   male
Age                                   47.0
SibSp                                    0
Parch                                    0
Ticket                              345765
Fare                                   9.0
Cabin                                  NaN
Embarked                                 S
Name: 873, dtype: object
874 PassengerId                                      875
Survived                                           1
Pclass                                             2
Name           Abelson, Mrs. Samuel (Hannah Wizosky)
Sex                                           female
Age                                             28.0
SibSp                                              1
Parch                                              0
Ticket                                     P/PP 3381
Fare                                            24.0
Cabin                                            NaN
Embarked                                           C
Name: 874, dtype: object
875 PassengerId                                 876
Survived                                      1
Pclass                                        3
Name           Najib, Miss. Adele Kiamie "Jane"
Sex                                      female
Age                                        15.0
SibSp                                         0
Parch                                         0
Ticket                                     2667
Fare                                      7.225
Cabin                                       NaN
Embarked                                      C
Name: 875, dtype: object
876 PassengerId                              877
Survived                                   0
Pclass                                     3
Name           Gustafsson, Mr. Alfred Ossian
Sex                                     male
Age                                     20.0
SibSp                                      0
Parch                                      0
Ticket                                  7534
Fare                                  9.8458
Cabin                                    NaN
Embarked                                   S
Name: 876, dtype: object
877 PassengerId                     878
Survived                          0
Pclass                            3
Name           Petroff, Mr. Nedelio
Sex                            male
Age                            19.0
SibSp                             0
Parch                             0
Ticket                       349212
Fare                         7.8958
Cabin                           NaN
Embarked                          S
Name: 877, dtype: object
878 PassengerId                   879
Survived                        0
Pclass                          3
Name           Laleff, Mr. Kristo
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket                     349217
Fare                       7.8958
Cabin                         NaN
Embarked                        S
Name: 878, dtype: object
879 PassengerId                                              880
Survived                                                   1
Pclass                                                     1
Name           Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
Sex                                                   female
Age                                                     56.0
SibSp                                                      0
Parch                                                      1
Ticket                                                 11767
Fare                                                 83.1583
Cabin                                                    C50
Embarked                                                   C
Name: 879, dtype: object
880 PassengerId                                             881
Survived                                                  1
Pclass                                                    2
Name           Shelley, Mrs. William (Imanita Parrish Hall)
Sex                                                  female
Age                                                    25.0
SibSp                                                     0
Parch                                                     1
Ticket                                               230433
Fare                                                   26.0
Cabin                                                   NaN
Embarked                                                  S
Name: 880, dtype: object
881 PassengerId                   882
Survived                        0
Pclass                          3
Name           Markun, Mr. Johann
Sex                          male
Age                          33.0
SibSp                           0
Parch                           0
Ticket                     349257
Fare                       7.8958
Cabin                         NaN
Embarked                        S
Name: 881, dtype: object
882 PassengerId                             883
Survived                                  0
Pclass                                    3
Name           Dahlberg, Miss. Gerda Ulrika
Sex                                  female
Age                                    22.0
SibSp                                     0
Parch                                     0
Ticket                                 7552
Fare                                10.5167
Cabin                                   NaN
Embarked                                  S
Name: 882, dtype: object
883 PassengerId                              884
Survived                                   0
Pclass                                     2
Name           Banfield, Mr. Frederick James
Sex                                     male
Age                                     28.0
SibSp                                      0
Parch                                      0
Ticket                      C.A./SOTON 34068
Fare                                    10.5
Cabin                                    NaN
Embarked                                   S
Name: 883, dtype: object
884 PassengerId                       885
Survived                            0
Pclass                              3
Name           Sutehall, Mr. Henry Jr
Sex                              male
Age                              25.0
SibSp                               0
Parch                               0
Ticket                SOTON/OQ 392076
Fare                             7.05
Cabin                             NaN
Embarked                            S
Name: 884, dtype: object
885 PassengerId                                     886
Survived                                          0
Pclass                                            3
Name           Rice, Mrs. William (Margaret Norton)
Sex                                          female
Age                                            39.0
SibSp                                             0
Parch                                             5
Ticket                                       382652
Fare                                         29.125
Cabin                                           NaN
Embarked                                          Q
Name: 885, dtype: object
886 PassengerId                      887
Survived                           0
Pclass                             2
Name           Montvila, Rev. Juozas
Sex                             male
Age                             27.0
SibSp                              0
Parch                              0
Ticket                        211536
Fare                            13.0
Cabin                            NaN
Embarked                           S
Name: 886, dtype: object
887 PassengerId                             888
Survived                                  1
Pclass                                    1
Name           Graham, Miss. Margaret Edith
Sex                                  female
Age                                    19.0
SibSp                                     0
Parch                                     0
Ticket                               112053
Fare                                   30.0
Cabin                                   B42
Embarked                                  S
Name: 887, dtype: object
888 PassengerId                                         889
Survived                                              0
Pclass                                                3
Name           Johnston, Miss. Catherine Helen "Carrie"
Sex                                              female
Age                                                 NaN
SibSp                                                 1
Parch                                                 2
Ticket                                       W./C. 6607
Fare                                              23.45
Cabin                                               NaN
Embarked                                              S
Name: 888, dtype: object
889 PassengerId                      890
Survived                           1
Pclass                             1
Name           Behr, Mr. Karl Howell
Sex                             male
Age                             26.0
SibSp                              0
Parch                              0
Ticket                        111369
Fare                            30.0
Cabin                           C148
Embarked                           C
Name: 889, dtype: object
890 PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [32]:
for index,row in df_titanic.iterrows():
    print(index,row[["Name","Fare"]])

0 Name    Braund, Mr. Owen Harris
Fare                       7.25
Name: 0, dtype: object
1 Name    Cumings, Mrs. John Bradley (Florence Briggs Th...
Fare                                              71.2833
Name: 1, dtype: object
2 Name    Heikkinen, Miss. Laina
Fare                     7.925
Name: 2, dtype: object
3 Name    Futrelle, Mrs. Jacques Heath (Lily May Peel)
Fare                                            53.1
Name: 3, dtype: object
4 Name    Allen, Mr. William Henry
Fare                        8.05
Name: 4, dtype: object
5 Name    Moran, Mr. James
Fare              8.4583
Name: 5, dtype: object
6 Name    McCarthy, Mr. Timothy J
Fare                    51.8625
Name: 6, dtype: object
7 Name    Palsson, Master. Gosta Leonard
Fare                            21.075
Name: 7, dtype: object
8 Name    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Fare                                              11.1333
Name: 8, dtype: object
9 Name    Nasser, Mrs. Nicholas (Adele Achem)
Fare                                30.0708
Name: 9, dtype: object
10 Name    Sandstrom, Miss. Marguerite Rut
Fare                               16.7
Name: 10, dtype: object
11 Name    Bonnell, Miss. Elizabeth
Fare                       26.55
Name: 11, dtype: object
12 Name    Saundercock, Mr. William Henry
Fare                              8.05
Name: 12, dtype: object
13 Name    Andersson, Mr. Anders Johan
Fare                         31.275
Name: 13, dtype: object
14 Name    Vestrom, Miss. Hulda Amanda Adolfina
Fare                                  7.8542
Name: 14, dtype: object
15 Name    Hewlett, Mrs. (Mary D Kingcome)
Fare                                16.0
Name: 15, dtype: object
16 Name    Rice, Master. Eugene
Fare                  29.125
Name: 16, dtype: object
17 Name    Williams, Mr. Charles Eugene
Fare                            13.0
Name: 17, dtype: object
18 Name    Vander Planke, Mrs. Julius (Emelia Maria Vande...
Fare                                                 18.0
Name: 18, dtype: object
19 Name    Masselmani, Mrs. Fatima
Fare                      7.225
Name: 19, dtype: object
20 Name    Fynney, Mr. Joseph J
Fare                    26.0
Name: 20, dtype: object
21 Name    Beesley, Mr. Lawrence
Fare                     13.0
Name: 21, dtype: object
22 Name    McGowan, Miss. Anna "Annie"
Fare                         8.0292
Name: 22, dtype: object
23 Name    Sloper, Mr. William Thompson
Fare                            35.5
Name: 23, dtype: object
24 Name    Palsson, Miss. Torborg Danira
Fare                           21.075
Name: 24, dtype: object
25 Name    Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
Fare                                              31.3875
Name: 25, dtype: object
26 Name    Emir, Mr. Farred Chehab
Fare                      7.225
Name: 26, dtype: object
27 Name    Fortune, Mr. Charles Alexander
Fare                             263.0
Name: 27, dtype: object
28 Name    O'Dwyer, Miss. Ellen "Nellie"
Fare                           7.8792
Name: 28, dtype: object
29 Name    Todoroff, Mr. Lalio
Fare                 7.8958
Name: 29, dtype: object
30 Name    Uruchurtu, Don. Manuel E
Fare                     27.7208
Name: 30, dtype: object
31 Name    Spencer, Mrs. William Augustus (Marie Eugenie)
Fare                                          146.5208
Name: 31, dtype: object
32 Name    Glynn, Miss. Mary Agatha
Fare                        7.75
Name: 32, dtype: object
33 Name    Wheadon, Mr. Edward H
Fare                     10.5
Name: 33, dtype: object
34 Name    Meyer, Mr. Edgar Joseph
Fare                    82.1708
Name: 34, dtype: object
35 Name    Holverson, Mr. Alexander Oskar
Fare                              52.0
Name: 35, dtype: object
36 Name    Mamee, Mr. Hanna
Fare              7.2292
Name: 36, dtype: object
37 Name    Cann, Mr. Ernest Charles
Fare                        8.05
Name: 37, dtype: object
38 Name    Vander Planke, Miss. Augusta Maria
Fare                                  18.0
Name: 38, dtype: object
39 Name    Nicola-Yarred, Miss. Jamila
Fare                        11.2417
Name: 39, dtype: object
40 Name    Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
Fare                                             9.475
Name: 40, dtype: object
41 Name    Turpin, Mrs. William John Robert (Dorothy Ann ...
Fare                                                 21.0
Name: 41, dtype: object
42 Name    Kraeff, Mr. Theodor
Fare                 7.8958
Name: 42, dtype: object
43 Name    Laroche, Miss. Simonne Marie Anne Andree
Fare                                     41.5792
Name: 43, dtype: object
44 Name    Devaney, Miss. Margaret Delia
Fare                           7.8792
Name: 44, dtype: object
45 Name    Rogers, Mr. William John
Fare                        8.05
Name: 45, dtype: object
46 Name    Lennon, Mr. Denis
Fare                 15.5
Name: 46, dtype: object
47 Name    O'Driscoll, Miss. Bridget
Fare                         7.75
Name: 47, dtype: object
48 Name    Samaan, Mr. Youssef
Fare                21.6792
Name: 48, dtype: object
49 Name    Arnold-Franchi, Mrs. Josef (Josefine Franchi)
Fare                                             17.8
Name: 49, dtype: object
50 Name    Panula, Master. Juha Niilo
Fare                       39.6875
Name: 50, dtype: object
51 Name    Nosworthy, Mr. Richard Cater
Fare                             7.8
Name: 51, dtype: object
52 Name    Harper, Mrs. Henry Sleeper (Myna Haxtun)
Fare                                     76.7292
Name: 52, dtype: object
53 Name    Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...
Fare                                                 26.0
Name: 53, dtype: object
54 Name    Ostby, Mr. Engelhart Cornelius
Fare                           61.9792
Name: 54, dtype: object
55 Name    Woolner, Mr. Hugh
Fare                 35.5
Name: 55, dtype: object
56 Name    Rugg, Miss. Emily
Fare                 10.5
Name: 56, dtype: object
57 Name    Novel, Mr. Mansouer
Fare                 7.2292
Name: 57, dtype: object
58 Name    West, Miss. Constance Mirium
Fare                           27.75
Name: 58, dtype: object
59 Name    Goodwin, Master. William Frederick
Fare                                  46.9
Name: 59, dtype: object
60 Name    Sirayanian, Mr. Orsen
Fare                   7.2292
Name: 60, dtype: object
61 Name    Icard, Miss. Amelie
Fare                   80.0
Name: 61, dtype: object
62 Name    Harris, Mr. Henry Birkhardt
Fare                         83.475
Name: 62, dtype: object
63 Name    Skoog, Master. Harald
Fare                     27.9
Name: 63, dtype: object
64 Name    Stewart, Mr. Albert A
Fare                  27.7208
Name: 64, dtype: object
65 Name    Moubarek, Master. Gerios
Fare                     15.2458
Name: 65, dtype: object
66 Name    Nye, Mrs. (Elizabeth Ramell)
Fare                            10.5
Name: 66, dtype: object
67 Name    Crease, Mr. Ernest James
Fare                      8.1583
Name: 67, dtype: object
68 Name    Andersson, Miss. Erna Alexandra
Fare                              7.925
Name: 68, dtype: object
69 Name    Kink, Mr. Vincenz
Fare               8.6625
Name: 69, dtype: object
70 Name    Jenkin, Mr. Stephen Curnow
Fare                          10.5
Name: 70, dtype: object
71 Name    Goodwin, Miss. Lillian Amy
Fare                          46.9
Name: 71, dtype: object
72 Name    Hood, Mr. Ambrose Jr
Fare                    73.5
Name: 72, dtype: object
73 Name    Chronopoulos, Mr. Apostolos
Fare                        14.4542
Name: 73, dtype: object
74 Name    Bing, Mr. Lee
Fare          56.4958
Name: 74, dtype: object
75 Name    Moen, Mr. Sigurd Hansen
Fare                       7.65
Name: 75, dtype: object
76 Name    Staneff, Mr. Ivan
Fare               7.8958
Name: 76, dtype: object
77 Name    Moutal, Mr. Rahamin Haim
Fare                        8.05
Name: 77, dtype: object
78 Name    Caldwell, Master. Alden Gates
Fare                             29.0
Name: 78, dtype: object
79 Name    Dowdell, Miss. Elizabeth
Fare                      12.475
Name: 79, dtype: object
80 Name    Waelens, Mr. Achille
Fare                     9.0
Name: 80, dtype: object
81 Name    Sheerlinck, Mr. Jan Baptist
Fare                            9.5
Name: 81, dtype: object
82 Name    McDermott, Miss. Brigdet Delia
Fare                            7.7875
Name: 82, dtype: object
83 Name    Carrau, Mr. Francisco M
Fare                       47.1
Name: 83, dtype: object
84 Name    Ilett, Miss. Bertha
Fare                   10.5
Name: 84, dtype: object
85 Name    Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...
Fare                                                15.85
Name: 85, dtype: object
86 Name    Ford, Mr. William Neal
Fare                    34.375
Name: 86, dtype: object
87 Name    Slocovski, Mr. Selman Francis
Fare                             8.05
Name: 87, dtype: object
88 Name    Fortune, Miss. Mabel Helen
Fare                         263.0
Name: 88, dtype: object
89 Name    Celotti, Mr. Francesco
Fare                      8.05
Name: 89, dtype: object
90 Name    Christmann, Mr. Emil
Fare                    8.05
Name: 90, dtype: object
91 Name    Andreasson, Mr. Paul Edvin
Fare                        7.8542
Name: 91, dtype: object
92 Name    Chaffee, Mr. Herbert Fuller
Fare                         61.175
Name: 92, dtype: object
93 Name    Dean, Mr. Bertram Frank
Fare                     20.575
Name: 93, dtype: object
94 Name    Coxon, Mr. Daniel
Fare                 7.25
Name: 94, dtype: object
95 Name    Shorney, Mr. Charles Joseph
Fare                           8.05
Name: 95, dtype: object
96 Name    Goldschmidt, Mr. George B
Fare                      34.6542
Name: 96, dtype: object
97 Name    Greenfield, Mr. William Bertram
Fare                            63.3583
Name: 97, dtype: object
98 Name    Doling, Mrs. John T (Ada Julia Bone)
Fare                                    23.0
Name: 98, dtype: object
99 Name    Kantor, Mr. Sinai
Fare                 26.0
Name: 99, dtype: object
100 Name    Petranec, Miss. Matilda
Fare                     7.8958
Name: 100, dtype: object
101 Name    Petroff, Mr. Pastcho ("Pentcho")
Fare                              7.8958
Name: 101, dtype: object
102 Name    White, Mr. Richard Frasar
Fare                      77.2875
Name: 102, dtype: object
103 Name    Johansson, Mr. Gustaf Joel
Fare                        8.6542
Name: 103, dtype: object
104 Name    Gustafsson, Mr. Anders Vilhelm
Fare                             7.925
Name: 104, dtype: object
105 Name    Mionoff, Mr. Stoytcho
Fare                   7.8958
Name: 105, dtype: object
106 Name    Salkjelsvik, Miss. Anna Kristine
Fare                                7.65
Name: 106, dtype: object
107 Name    Moss, Mr. Albert Johan
Fare                     7.775
Name: 107, dtype: object
108 Name    Rekic, Mr. Tido
Fare             7.8958
Name: 108, dtype: object
109 Name    Moran, Miss. Bertha
Fare                  24.15
Name: 109, dtype: object
110 Name    Porter, Mr. Walter Chamberlain
Fare                              52.0
Name: 110, dtype: object
111 Name    Zabour, Miss. Hileni
Fare                 14.4542
Name: 111, dtype: object
112 Name    Barton, Mr. David John
Fare                      8.05
Name: 112, dtype: object
113 Name    Jussila, Miss. Katriina
Fare                      9.825
Name: 113, dtype: object
114 Name    Attalah, Miss. Malake
Fare                  14.4583
Name: 114, dtype: object
115 Name    Pekoniemi, Mr. Edvard
Fare                    7.925
Name: 115, dtype: object
116 Name    Connors, Mr. Patrick
Fare                    7.75
Name: 116, dtype: object
117 Name    Turpin, Mr. William John Robert
Fare                               21.0
Name: 117, dtype: object
118 Name    Baxter, Mr. Quigg Edmond
Fare                    247.5208
Name: 118, dtype: object
119 Name    Andersson, Miss. Ellis Anna Maria
Fare                               31.275
Name: 119, dtype: object
120 Name    Hickman, Mr. Stanley George
Fare                           73.5
Name: 120, dtype: object
121 Name    Moore, Mr. Leonard Charles
Fare                          8.05
Name: 121, dtype: object
122 Name    Nasser, Mr. Nicholas
Fare                 30.0708
Name: 122, dtype: object
123 Name    Webber, Miss. Susan
Fare                   13.0
Name: 123, dtype: object
124 Name    White, Mr. Percival Wayland
Fare                        77.2875
Name: 124, dtype: object
125 Name    Nicola-Yarred, Master. Elias
Fare                         11.2417
Name: 125, dtype: object
126 Name    McMahon, Mr. Martin
Fare                   7.75
Name: 126, dtype: object
127 Name    Madsen, Mr. Fridtjof Arne
Fare                       7.1417
Name: 127, dtype: object
128 Name    Peter, Miss. Anna
Fare              22.3583
Name: 128, dtype: object
129 Name    Ekstrom, Mr. Johan
Fare                 6.975
Name: 129, dtype: object
130 Name    Drazenoic, Mr. Jozef
Fare                  7.8958
Name: 130, dtype: object
131 Name    Coelho, Mr. Domingos Fernandeo
Fare                              7.05
Name: 131, dtype: object
132 Name    Robins, Mrs. Alexander A (Grace Charity Laury)
Fare                                              14.5
Name: 132, dtype: object
133 Name    Weisz, Mrs. Leopold (Mathilde Francoise Pede)
Fare                                             26.0
Name: 133, dtype: object
134 Name    Sobey, Mr. Samuel James Hayden
Fare                              13.0
Name: 134, dtype: object
135 Name    Richard, Mr. Emile
Fare               15.0458
Name: 135, dtype: object
136 Name    Newsom, Miss. Helen Monypeny
Fare                         26.2833
Name: 136, dtype: object
137 Name    Futrelle, Mr. Jacques Heath
Fare                           53.1
Name: 137, dtype: object
138 Name    Osen, Mr. Olaf Elon
Fare                 9.2167
Name: 138, dtype: object
139 Name    Giglio, Mr. Victor
Fare                  79.2
Name: 139, dtype: object
140 Name    Boulos, Mrs. Joseph (Sultana)
Fare                          15.2458
Name: 140, dtype: object
141 Name    Nysten, Miss. Anna Sofia
Fare                        7.75
Name: 141, dtype: object
142 Name    Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
Fare                                                15.85
Name: 142, dtype: object
143 Name    Burke, Mr. Jeremiah
Fare                   6.75
Name: 143, dtype: object
144 Name    Andrew, Mr. Edgardo Samuel
Fare                          11.5

Name: 144, dtype: object
145 Name    Nicholls, Mr. Joseph Charles
Fare                           36.75
Name: 145, dtype: object
146 Name    Andersson, Mr. August Edvard ("Wennerstrom")
Fare                                          7.7958
Name: 146, dtype: object
147 Name    Ford, Miss. Robina Maggie "Ruby"
Fare                              34.375
Name: 147, dtype: object
148 Name    Navratil, Mr. Michel ("Louis M Hoffman")
Fare                                        26.0
Name: 148, dtype: object
149 Name    Byles, Rev. Thomas Roussel Davids
Fare                                 13.0
Name: 149, dtype: object
150 Name    Bateman, Rev. Robert James
Fare                        12.525
Name: 150, dtype: object
151 Name    Pears, Mrs. Thomas (Edith Wearne)
Fare                                 66.6
Name: 151, dtype: object
152 Name    Meo, Mr. Alfonzo
Fare                8.05
Name: 152, dtype: object
153 Name    van Billiard, Mr. Austin Blyler
Fare                               14.5
Name: 153, dtype: object
154 Name    Olsen, Mr. Ole Martin
Fare                   7.3125
Name: 154, dtype: object
155 Name    Williams, Mr. Charles Duane
Fare                        61.3792
Name: 155, dtype: object
156 Name    Gilnagh, Miss. Katherine "Katie"
Fare                              7.7333
Name: 156, dtype: object
157 Name    Corn, Mr. Harry
Fare               8.05
Name: 157, dtype: object
158 Name    Smiljanic, Mr. Mile
Fare                 8.6625
Name: 158, dtype: object
159 Name    Sage, Master. Thomas Henry
Fare                         69.55
Name: 159, dtype: object
160 Name    Cribb, Mr. John Hatfield
Fare                        16.1
Name: 160, dtype: object
161 Name    Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...
Fare                                                15.75
Name: 161, dtype: object
162 Name    Bengtsson, Mr. John Viktor
Fare                         7.775
Name: 162, dtype: object
163 Name    Calic, Mr. Jovo
Fare             8.6625
Name: 163, dtype: object
164 Name    Panula, Master. Eino Viljami
Fare                         39.6875
Name: 164, dtype: object
165 Name    Goldsmith, Master. Frank John William "Frankie"
Fare                                             20.525
Name: 165, dtype: object
166 Name    Chibnall, Mrs. (Edith Martha Bowerman)
Fare                                      55.0
Name: 166, dtype: object
167 Name    Skoog, Mrs. William (Anna Bernhardina Karlsson)
Fare                                               27.9
Name: 167, dtype: object
168 Name    Baumann, Mr. John D
Fare                 25.925
Name: 168, dtype: object
169 Name    Ling, Mr. Lee
Fare          56.4958
Name: 169, dtype: object
170 Name    Van der hoef, Mr. Wyckoff
Fare                         33.5
Name: 170, dtype: object
171 Name    Rice, Master. Arthur
Fare                  29.125
Name: 171, dtype: object
172 Name    Johnson, Miss. Eleanor Ileen
Fare                         11.1333
Name: 172, dtype: object
173 Name    Sivola, Mr. Antti Wilhelm
Fare                        7.925
Name: 173, dtype: object
174 Name    Smith, Mr. James Clinch
Fare                    30.6958
Name: 174, dtype: object
175 Name    Klasen, Mr. Klas Albin
Fare                    7.8542
Name: 175, dtype: object
176 Name    Lefebre, Master. Henry Forbes
Fare                          25.4667
Name: 176, dtype: object
177 Name    Isham, Miss. Ann Elizabeth
Fare                       28.7125
Name: 177, dtype: object
178 Name    Hale, Mr. Reginald
Fare                  13.0
Name: 178, dtype: object
179 Name    Leonard, Mr. Lionel
Fare                    0.0
Name: 179, dtype: object
180 Name    Sage, Miss. Constance Gladys
Fare                           69.55
Name: 180, dtype: object
181 Name    Pernot, Mr. Rene
Fare               15.05
Name: 181, dtype: object
182 Name    Asplund, Master. Clarence Gustaf Hugo
Fare                                  31.3875
Name: 182, dtype: object
183 Name    Becker, Master. Richard F
Fare                         39.0
Name: 183, dtype: object
184 Name    Kink-Heilmann, Miss. Luise Gretchen
Fare                                 22.025
Name: 184, dtype: object
185 Name    Rood, Mr. Hugh Roscoe
Fare                     50.0
Name: 185, dtype: object
186 Name    O'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)
Fare                                               15.5
Name: 186, dtype: object
187 Name    Romaine, Mr. Charles Hallace ("Mr C Rolmane")
Fare                                            26.55
Name: 187, dtype: object
188 Name    Bourke, Mr. John
Fare                15.5
Name: 188, dtype: object
189 Name    Turcin, Mr. Stjepan
Fare                 7.8958
Name: 189, dtype: object
190 Name    Pinsky, Mrs. (Rosa)
Fare                   13.0
Name: 190, dtype: object
191 Name    Carbines, Mr. William
Fare                     13.0
Name: 191, dtype: object
192 Name    Andersen-Jensen, Miss. Carla Christine Nielsine
Fare                                             7.8542
Name: 192, dtype: object
193 Name    Navratil, Master. Michel M
Fare                          26.0
Name: 193, dtype: object
194 Name    Brown, Mrs. James Joseph (Margaret Tobin)
Fare                                      27.7208
Name: 194, dtype: object
195 Name    Lurette, Miss. Elise
Fare                146.5208
Name: 195, dtype: object
196 Name    Mernagh, Mr. Robert
Fare                   7.75
Name: 196, dtype: object
197 Name    Olsen, Mr. Karl Siegwart Andreas
Fare                              8.4042
Name: 197, dtype: object
198 Name    Madigan, Miss. Margaret "Maggie"
Fare                                7.75
Name: 198, dtype: object
199 Name    Yrois, Miss. Henriette ("Mrs Harbeck")
Fare                                      13.0
Name: 199, dtype: object
200 Name    Vande Walle, Mr. Nestor Cyriel
Fare                               9.5
Name: 200, dtype: object
201 Name    Sage, Mr. Frederick
Fare                  69.55
Name: 201, dtype: object
202 Name    Johanson, Mr. Jakob Alfred
Fare                        6.4958
Name: 202, dtype: object
203 Name    Youseff, Mr. Gerious
Fare                   7.225
Name: 203, dtype: object
204 Name    Cohen, Mr. Gurshon "Gus"
Fare                        8.05
Name: 204, dtype: object
205 Name    Strom, Miss. Telma Matilda
Fare                       10.4625
Name: 205, dtype: object
206 Name    Backstrom, Mr. Karl Alfred
Fare                         15.85
Name: 206, dtype: object
207 Name    Albimona, Mr. Nassef Cassem
Fare                        18.7875
Name: 207, dtype: object
208 Name    Carr, Miss. Helen "Ellen"
Fare                         7.75
Name: 208, dtype: object
209 Name    Blank, Mr. Henry
Fare                31.0
Name: 209, dtype: object
210 Name    Ali, Mr. Ahmed
Fare              7.05
Name: 210, dtype: object
211 Name    Cameron, Miss. Clear Annie
Fare                          21.0
Name: 211, dtype: object
212 Name    Perkin, Mr. John Henry
Fare                      7.25
Name: 212, dtype: object
213 Name    Givard, Mr. Hans Kristensen
Fare                           13.0
Name: 213, dtype: object
214 Name    Kiernan, Mr. Philip
Fare                   7.75
Name: 214, dtype: object
215 Name    Newell, Miss. Madeleine
Fare                    113.275
Name: 215, dtype: object
216 Name    Honkanen, Miss. Eliina
Fare                     7.925
Name: 216, dtype: object
217 Name    Jacobsohn, Mr. Sidney Samuel
Fare                            27.0
Name: 217, dtype: object
218 Name    Bazzani, Miss. Albina
Fare                  76.2917
Name: 218, dtype: object
219 Name    Harris, Mr. Walter
Fare                  10.5
Name: 219, dtype: object
220 Name    Sunderland, Mr. Victor Francis
Fare                              8.05
Name: 220, dtype: object
221 Name    Bracken, Mr. James H
Fare                    13.0
Name: 221, dtype: object
222 Name    Green, Mr. George Henry
Fare                       8.05
Name: 222, dtype: object
223 Name    Nenkoff, Mr. Christo
Fare                  7.8958
Name: 223, dtype: object
224 Name    Hoyt, Mr. Frederick Maxfield
Fare                            90.0
Name: 224, dtype: object
225 Name    Berglund, Mr. Karl Ivar Sven
Fare                            9.35
Name: 225, dtype: object
226 Name    Mellors, Mr. William John
Fare                         10.5
Name: 226, dtype: object
227 Name    Lovell, Mr. John Hall ("Henry")
Fare                               7.25
Name: 227, dtype: object
228 Name    Fahlstrom, Mr. Arne Jonas
Fare                         13.0
Name: 228, dtype: object
229 Name    Lefebre, Miss. Mathilde
Fare                    25.4667
Name: 229, dtype: object
230 Name    Harris, Mrs. Henry Birkhardt (Irene Wallach)
Fare                                          83.475
Name: 230, dtype: object
231 Name    Larsson, Mr. Bengt Edvin
Fare                       7.775
Name: 231, dtype: object
232 Name    Sjostedt, Mr. Ernst Adolf
Fare                         13.5
Name: 232, dtype: object
233 Name    Asplund, Miss. Lillian Gertrud
Fare                           31.3875
Name: 233, dtype: object
234 Name    Leyson, Mr. Robert William Norman
Fare                                 10.5
Name: 234, dtype: object
235 Name    Harknett, Miss. Alice Phoebe
Fare                            7.55
Name: 235, dtype: object
236 Name    Hold, Mr. Stephen
Fare                 26.0
Name: 236, dtype: object
237 Name    Collyer, Miss. Marjorie "Lottie"
Fare                               26.25
Name: 237, dtype: object
238 Name    Pengelly, Mr. Frederick William
Fare                               10.5
Name: 238, dtype: object
239 Name    Hunt, Mr. George Henry
Fare                    12.275
Name: 239, dtype: object
240 Name    Zabour, Miss. Thamine
Fare                  14.4542
Name: 240, dtype: object
241 Name    Murphy, Miss. Katherine "Kate"
Fare                              15.5
Name: 241, dtype: object
242 Name    Coleridge, Mr. Reginald Charles
Fare                               10.5
Name: 242, dtype: object
243 Name    Maenpaa, Mr. Matti Alexanteri
Fare                            7.125
Name: 243, dtype: object
244 Name    Attalah, Mr. Sleiman
Fare                   7.225
Name: 244, dtype: object
245 Name    Minahan, Dr. William Edward
Fare                           90.0
Name: 245, dtype: object
246 Name    Lindahl, Miss. Agda Thorilda Viktoria
Fare                                    7.775
Name: 246, dtype: object
247 Name    Hamalainen, Mrs. William (Anna)
Fare                               14.5
Name: 247, dtype: object
248 Name    Beckwith, Mr. Richard Leonard
Fare                          52.5542
Name: 248, dtype: object
249 Name    Carter, Rev. Ernest Courtenay
Fare                             26.0
Name: 249, dtype: object
250 Name    Reed, Mr. James George
Fare                      7.25
Name: 250, dtype: object
251 Name    Strom, Mrs. Wilhelm (Elna Matilda Persson)
Fare                                       10.4625
Name: 251, dtype: object
252 Name    Stead, Mr. William Thomas
Fare                        26.55
Name: 252, dtype: object
253 Name    Lobb, Mr. William Arthur
Fare                        16.1
Name: 253, dtype: object
254 Name    Rosblom, Mrs. Viktor (Helena Wilhelmina)
Fare                                     20.2125
Name: 254, dtype: object
255 Name    Touma, Mrs. Darwis (Hanne Youssef Razi)
Fare                                    15.2458
Name: 255, dtype: object
256 Name    Thorne, Mrs. Gertrude Maybelle
Fare                              79.2
Name: 256, dtype: object
257 Name    Cherry, Miss. Gladys
Fare                    86.5
Name: 257, dtype: object
258 Name    Ward, Miss. Anna
Fare            512.3292
Name: 258, dtype: object
259 Name    Parrish, Mrs. (Lutie Davis)
Fare                           26.0
Name: 259, dtype: object
260 Name    Smith, Mr. Thomas
Fare                 7.75
Name: 260, dtype: object
261 Name    Asplund, Master. Edvin Rojj Felix
Fare                              31.3875
Name: 261, dtype: object
262 Name    Taussig, Mr. Emil
Fare                79.65
Name: 262, dtype: object
263 Name    Harrison, Mr. William
Fare                      0.0
Name: 263, dtype: object
264 Name    Henry, Miss. Delia
Fare                  7.75
Name: 264, dtype: object
265 Name    Reeves, Mr. David
Fare                 10.5
Name: 265, dtype: object
266 Name    Panula, Mr. Ernesti Arvid
Fare                      39.6875
Name: 266, dtype: object
267 Name    Persson, Mr. Ernst Ulrik
Fare                       7.775
Name: 267, dtype: object
268 Name    Graham, Mrs. William Thompson (Edith Junkins)
Fare                                         153.4625
Name: 268, dtype: object
269 Name    Bissette, Miss. Amelia
Fare                  135.6333
Name: 269, dtype: object
270 Name    Cairns, Mr. Alexander
Fare                     31.0
Name: 270, dtype: object
271 Name    Tornquist, Mr. William Henry
Fare                             0.0
Name: 271, dtype: object
272 Name    Mellinger, Mrs. (Elizabeth Anne Maidment)
Fare                                         19.5
Name: 272, dtype: object
273 Name    Natsch, Mr. Charles H
Fare                     29.7
Name: 273, dtype: object
274 Name    Healy, Miss. Hanora "Nora"
Fare                          7.75
Name: 274, dtype: object
275 Name    Andrews, Miss. Kornelia Theodosia
Fare                              77.9583
Name: 275, dtype: object
276 Name    Lindblom, Miss. Augusta Charlotta
Fare                                 7.75
Name: 276, dtype: object
277 Name    Parkes, Mr. Francis "Frank"
Fare                            0.0
Name: 277, dtype: object
278 Name    Rice, Master. Eric
Fare                29.125
Name: 278, dtype: object
279 Name    Abbott, Mrs. Stanton (Rosa Hunt)
Fare                               20.25
Name: 279, dtype: object
280 Name    Duane, Mr. Frank
Fare                7.75
Name: 280, dtype: object
281 Name    Olsson, Mr. Nils Johan Goransson
Fare                              7.8542
Name: 281, dtype: object
282 Name    de Pelsmaeker, Mr. Alfons
Fare                          9.5
Name: 282, dtype: object
283 Name    Dorking, Mr. Edward Arthur
Fare                          8.05
Name: 283, dtype: object
284 Name    Smith, Mr. Richard William
Fare                          26.0
Name: 284, dtype: object
285 Name    Stankovic, Mr. Ivan
Fare                 8.6625
Name: 285, dtype: object
286 Name    de Mulder, Mr. Theodore
Fare                        9.5
Name: 286, dtype: object
287 Name    Naidenoff, Mr. Penko
Fare                  7.8958
Name: 287, dtype: object
288 Name    Hosono, Mr. Masabumi
Fare                    13.0
Name: 288, dtype: object
289 Name    Connolly, Miss. Kate
Fare                    7.75
Name: 289, dtype: object
290 Name    Barber, Miss. Ellen "Nellie"
Fare                           78.85
Name: 290, dtype: object
291 Name    Bishop, Mrs. Dickinson H (Helen Walton)
Fare                                    91.0792
Name: 291, dtype: object
292 Name    Levy, Mr. Rene Jacques
Fare                    12.875
Name: 292, dtype: object
293 Name    Haas, Miss. Aloisia
Fare                   8.85
Name: 293, dtype: object
294 Name    Mineff, Mr. Ivan
Fare              7.8958
Name: 294, dtype: object
295 Name    Lewy, Mr. Ervin G
Fare              27.7208
Name: 295, dtype: object
296 Name    Hanna, Mr. Mansour
Fare                7.2292
Name: 296, dtype: object
297 Name    Allison, Miss. Helen Loraine
Fare                          151.55
Name: 297, dtype: object
298 Name    Saalfeld, Mr. Adolphe
Fare                     30.5
Name: 298, dtype: object
299 Name    Baxter, Mrs. James (Helene DeLaudeniere Chaput)
Fare                                           247.5208
Name: 299, dtype: object
300 Name    Kelly, Miss. Anna Katherine "Annie Kate"
Fare                                        7.75
Name: 300, dtype: object
301 Name    McCoy, Mr. Bernard
Fare                 23.25
Name: 301, dtype: object
302 Name    Johnson, Mr. William Cahoone Jr
Fare                                0.0
Name: 302, dtype: object
303 Name    Keane, Miss. Nora A
Fare                  12.35
Name: 303, dtype: object
304 Name    Williams, Mr. Howard Hugh "Harry"
Fare                                 8.05
Name: 304, dtype: object
305 Name    Allison, Master. Hudson Trevor
Fare                            151.55
Name: 305, dtype: object
306 Name    Fleming, Miss. Margaret
Fare                   110.8833
Name: 306, dtype: object
307 Name    Penasco y Castellana, Mrs. Victor de Satode (M...
Fare                                                108.9
Name: 307, dtype: object
308 Name    Abelson, Mr. Samuel
Fare                   24.0
Name: 308, dtype: object
309 Name    Francatelli, Miss. Laura Mabel
Fare                           56.9292
Name: 309, dtype: object
310 Name    Hays, Miss. Margaret Bechstein
Fare                           83.1583
Name: 310, dtype: object
311 Name    Ryerson, Miss. Emily Borie
Fare                       262.375
Name: 311, dtype: object

312 Name    Lahtinen, Mrs. William (Anna Sylfven)
Fare                                     26.0
Name: 312, dtype: object
313 Name    Hendekovic, Mr. Ignjac
Fare                    7.8958
Name: 313, dtype: object
314 Name    Hart, Mr. Benjamin
Fare                 26.25
Name: 314, dtype: object
315 Name    Nilsson, Miss. Helmina Josefina
Fare                             7.8542
Name: 315, dtype: object
316 Name    Kantor, Mrs. Sinai (Miriam Sternin)
Fare                                   26.0
Name: 316, dtype: object
317 Name    Moraweck, Dr. Ernest
Fare                    14.0
Name: 317, dtype: object
318 Name    Wick, Miss. Mary Natalie
Fare                    164.8667
Name: 318, dtype: object
319 Name    Spedden, Mrs. Frederic Oakley (Margaretta Corn...
Fare                                                134.5
Name: 319, dtype: object
320 Name    Dennis, Mr. Samuel
Fare                  7.25
Name: 320, dtype: object
321 Name    Danoff, Mr. Yoto
Fare              7.8958
Name: 321, dtype: object
322 Name    Slayter, Miss. Hilda Mary
Fare                        12.35
Name: 322, dtype: object
323 Name    Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...
Fare                                                 29.0
Name: 323, dtype: object
324 Name    Sage, Mr. George John Jr
Fare                       69.55
Name: 324, dtype: object
325 Name    Young, Miss. Marie Grice
Fare                    135.6333
Name: 325, dtype: object
326 Name    Nysveen, Mr. Johan Hansen
Fare                       6.2375
Name: 326, dtype: object
327 Name    Ball, Mrs. (Ada E Hall)
Fare                       13.0
Name: 327, dtype: object
328 Name    Goldsmith, Mrs. Frank John (Emily Alice Brown)
Fare                                            20.525
Name: 328, dtype: object
329 Name    Hippach, Miss. Jean Gertrude
Fare                         57.9792
Name: 329, dtype: object
330 Name    McCoy, Miss. Agnes
Fare                 23.25
Name: 330, dtype: object
331 Name    Partner, Mr. Austen
Fare                   28.5
Name: 331, dtype: object
332 Name    Graham, Mr. George Edward
Fare                     153.4625
Name: 332, dtype: object
333 Name    Vander Planke, Mr. Leo Edmondus
Fare                               18.0
Name: 333, dtype: object
334 Name    Frauenthal, Mrs. Henry William (Clara Heinshei...
Fare                                               133.65
Name: 334, dtype: object
335 Name    Denkoff, Mr. Mitto
Fare                7.8958
Name: 335, dtype: object
336 Name    Pears, Mr. Thomas Clinton
Fare                         66.6
Name: 336, dtype: object
337 Name    Burns, Miss. Elizabeth Margaret
Fare                              134.5
Name: 337, dtype: object
338 Name    Dahl, Mr. Karl Edwart
Fare                     8.05
Name: 338, dtype: object
339 Name    Blackwell, Mr. Stephen Weart
Fare                            35.5
Name: 339, dtype: object
340 Name    Navratil, Master. Edmond Roger
Fare                              26.0
Name: 340, dtype: object
341 Name    Fortune, Miss. Alice Elizabeth
Fare                             263.0
Name: 341, dtype: object
342 Name    Collander, Mr. Erik Gustaf
Fare                          13.0
Name: 342, dtype: object
343 Name    Sedgwick, Mr. Charles Frederick Waddington
Fare                                          13.0
Name: 343, dtype: object
344 Name    Fox, Mr. Stanley Hubert
Fare                       13.0
Name: 344, dtype: object
345 Name    Brown, Miss. Amelia "Mildred"
Fare                             13.0
Name: 345, dtype: object
346 Name    Smith, Miss. Marion Elsie
Fare                         13.0
Name: 346, dtype: object
347 Name    Davison, Mrs. Thomas Henry (Mary E Finck)
Fare                                         16.1
Name: 347, dtype: object
348 Name    Coutts, Master. William Loch "William"
Fare                                      15.9
Name: 348, dtype: object
349 Name    Dimic, Mr. Jovan
Fare              8.6625
Name: 349, dtype: object
350 Name    Odahl, Mr. Nils Martin
Fare                     9.225
Name: 350, dtype: object
351 Name    Williams-Lambert, Mr. Fletcher Fellows
Fare                                      35.0
Name: 351, dtype: object
352 Name    Elias, Mr. Tannous
Fare                7.2292
Name: 352, dtype: object
353 Name    Arnold-Franchi, Mr. Josef
Fare                         17.8
Name: 353, dtype: object
354 Name    Yousif, Mr. Wazli
Fare                7.225
Name: 354, dtype: object
355 Name    Vanden Steen, Mr. Leo Peter
Fare                            9.5
Name: 355, dtype: object
356 Name    Bowerman, Miss. Elsie Edith
Fare                           55.0
Name: 356, dtype: object
357 Name    Funk, Miss. Annie Clemmer
Fare                         13.0
Name: 357, dtype: object
358 Name    McGovern, Miss. Mary
Fare                  7.8792
Name: 358, dtype: object
359 Name    Mockler, Miss. Helen Mary "Ellie"
Fare                               7.8792
Name: 359, dtype: object
360 Name    Skoog, Mr. Wilhelm
Fare                  27.9
Name: 360, dtype: object
361 Name    del Carlo, Mr. Sebastiano
Fare                      27.7208
Name: 361, dtype: object
362 Name    Barbara, Mrs. (Catherine David)
Fare                            14.4542
Name: 362, dtype: object
363 Name    Asim, Mr. Adola
Fare               7.05
Name: 363, dtype: object
364 Name    O'Brien, Mr. Thomas
Fare                   15.5
Name: 364, dtype: object
365 Name    Adahl, Mr. Mauritz Nils Martin
Fare                              7.25
Name: 365, dtype: object
366 Name    Warren, Mrs. Frank Manley (Anna Sophia Atkinson)
Fare                                               75.25
Name: 366, dtype: object
367 Name    Moussa, Mrs. (Mantoura Boulos)
Fare                            7.2292
Name: 367, dtype: object
368 Name    Jermyn, Miss. Annie
Fare                   7.75
Name: 368, dtype: object
369 Name    Aubart, Mme. Leontine Pauline
Fare                             69.3
Name: 369, dtype: object
370 Name    Harder, Mr. George Achilles
Fare                        55.4417
Name: 370, dtype: object
371 Name    Wiklund, Mr. Jakob Alfred
Fare                       6.4958
Name: 371, dtype: object
372 Name    Beavan, Mr. William Thomas
Fare                          8.05
Name: 372, dtype: object
373 Name    Ringhini, Mr. Sante
Fare               135.6333
Name: 373, dtype: object
374 Name    Palsson, Miss. Stina Viola
Fare                        21.075
Name: 374, dtype: object
375 Name    Meyer, Mrs. Edgar Joseph (Leila Saks)
Fare                                  82.1708
Name: 375, dtype: object
376 Name    Landergren, Miss. Aurora Adelia
Fare                               7.25
Name: 376, dtype: object
377 Name    Widener, Mr. Harry Elkins
Fare                        211.5
Name: 377, dtype: object
378 Name    Betros, Mr. Tannous
Fare                 4.0125
Name: 378, dtype: object
379 Name    Gustafsson, Mr. Karl Gideon
Fare                          7.775
Name: 379, dtype: object
380 Name    Bidois, Miss. Rosalie
Fare                  227.525
Name: 380, dtype: object
381 Name    Nakid, Miss. Maria ("Mary")
Fare                        15.7417
Name: 381, dtype: object
382 Name    Tikkanen, Mr. Juho
Fare                 7.925
Name: 382, dtype: object
383 Name    Holverson, Mrs. Alexander Oskar (Mary Aline To...
Fare                                                 52.0
Name: 383, dtype: object
384 Name    Plotcharsky, Mr. Vasil
Fare                    7.8958
Name: 384, dtype: object
385 Name    Davies, Mr. Charles Henry
Fare                         73.5
Name: 385, dtype: object
386 Name    Goodwin, Master. Sidney Leonard
Fare                               46.9
Name: 386, dtype: object
387 Name    Buss, Miss. Kate
Fare                13.0
Name: 387, dtype: object
388 Name    Sadlier, Mr. Matthew
Fare                  7.7292
Name: 388, dtype: object
389 Name    Lehmann, Miss. Bertha
Fare                     12.0
Name: 389, dtype: object
390 Name    Carter, Mr. William Ernest
Fare                         120.0
Name: 390, dtype: object
391 Name    Jansson, Mr. Carl Olof
Fare                    7.7958
Name: 391, dtype: object
392 Name    Gustafsson, Mr. Johan Birger
Fare                           7.925
Name: 392, dtype: object
393 Name    Newell, Miss. Marjorie
Fare                   113.275
Name: 393, dtype: object
394 Name    Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
Fare                                                 16.7
Name: 394, dtype: object
395 Name    Johansson, Mr. Erik
Fare                 7.7958
Name: 395, dtype: object
396 Name    Olsson, Miss. Elina
Fare                 7.8542
Name: 396, dtype: object
397 Name    McKane, Mr. Peter David
Fare                       26.0
Name: 397, dtype: object
398 Name    Pain, Dr. Alfred
Fare                10.5
Name: 398, dtype: object
399 Name    Trout, Mrs. William H (Jessie L)
Fare                               12.65
Name: 399, dtype: object
400 Name    Niskanen, Mr. Juha
Fare                 7.925
Name: 400, dtype: object
401 Name    Adams, Mr. John
Fare               8.05
Name: 401, dtype: object
402 Name    Jussila, Miss. Mari Aina
Fare                       9.825
Name: 402, dtype: object
403 Name    Hakkarainen, Mr. Pekka Pietari
Fare                             15.85
Name: 403, dtype: object
404 Name    Oreskovic, Miss. Marija
Fare                     8.6625
Name: 404, dtype: object
405 Name    Gale, Mr. Shadrach
Fare                  21.0
Name: 405, dtype: object
406 Name    Widegren, Mr. Carl/Charles Peter
Fare                                7.75
Name: 406, dtype: object
407 Name    Richards, Master. William Rowe
Fare                             18.75
Name: 407, dtype: object
408 Name    Birkeland, Mr. Hans Martin Monsen
Fare                                7.775
Name: 408, dtype: object
409 Name    Lefebre, Miss. Ida
Fare               25.4667
Name: 409, dtype: object
410 Name    Sdycoff, Mr. Todor
Fare                7.8958
Name: 410, dtype: object
411 Name    Hart, Mr. Henry
Fare             6.8583
Name: 411, dtype: object
412 Name    Minahan, Miss. Daisy E
Fare                      90.0
Name: 412, dtype: object
413 Name    Cunningham, Mr. Alfred Fleming
Fare                               0.0
Name: 413, dtype: object
414 Name    Sundman, Mr. Johan Julian
Fare                        7.925
Name: 414, dtype: object
415 Name    Meek, Mrs. Thomas (Annie Louise Rowley)
Fare                                       8.05
Name: 415, dtype: object
416 Name    Drew, Mrs. James Vivian (Lulu Thorne Christian)
Fare                                               32.5
Name: 416, dtype: object
417 Name    Silven, Miss. Lyyli Karoliina
Fare                             13.0
Name: 417, dtype: object
418 Name    Matthews, Mr. William John
Fare                          13.0
Name: 418, dtype: object
419 Name    Van Impe, Miss. Catharina
Fare                        24.15
Name: 419, dtype: object
420 Name    Gheorgheff, Mr. Stanio
Fare                    7.8958
Name: 420, dtype: object
421 Name    Charters, Mr. David
Fare                 7.7333
Name: 421, dtype: object
422 Name    Zimmerman, Mr. Leo
Fare                 7.875
Name: 422, dtype: object
423 Name    Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria ...
Fare                                                 14.4
Name: 423, dtype: object
424 Name    Rosblom, Mr. Viktor Richard
Fare                        20.2125
Name: 424, dtype: object
425 Name    Wiseman, Mr. Phillippe
Fare                      7.25
Name: 425, dtype: object
426 Name    Clarke, Mrs. Charles V (Ada Maria Winfield)
Fare                                           26.0
Name: 426, dtype: object
427 Name    Phillips, Miss. Kate Florence ("Mrs Kate Louis...
Fare                                                 26.0
Name: 427, dtype: object
428 Name    Flynn, Mr. James
Fare                7.75
Name: 428, dtype: object
429 Name    Pickard, Mr. Berk (Berk Trembisky)
Fare                                  8.05
Name: 429, dtype: object
430 Name    Bjornstrom-Steffansson, Mr. Mauritz Hakan
Fare                                        26.55
Name: 430, dtype: object
431 Name    Thorneycroft, Mrs. Percival (Florence Kate White)
Fare                                                 16.1
Name: 431, dtype: object
432 Name    Louch, Mrs. Charles Alexander (Alice Adelaide ...
Fare                                                 26.0
Name: 432, dtype: object
433 Name    Kallio, Mr. Nikolai Erland
Fare                         7.125
Name: 433, dtype: object
434 Name    Silvey, Mr. William Baird
Fare                         55.9
Name: 434, dtype: object
435 Name    Carter, Miss. Lucile Polk
Fare                        120.0
Name: 435, dtype: object
436 Name    Ford, Miss. Doolina Margaret "Daisy"
Fare                                  34.375
Name: 436, dtype: object
437 Name    Richards, Mrs. Sidney (Emily Hocking)
Fare                                    18.75
Name: 437, dtype: object
438 Name    Fortune, Mr. Mark
Fare                263.0
Name: 438, dtype: object
439 Name    Kvillner, Mr. Johan Henrik Johannesson
Fare                                      10.5
Name: 439, dtype: object
440 Name    Hart, Mrs. Benjamin (Esther Ada Bloomfield)
Fare                                          26.25
Name: 440, dtype: object
441 Name    Hampe, Mr. Leon
Fare                9.5
Name: 441, dtype: object
442 Name    Petterson, Mr. Johan Emil
Fare                        7.775
Name: 442, dtype: object
443 Name    Reynaldo, Ms. Encarnacion
Fare                         13.0
Name: 443, dtype: object
444 Name    Johannesen-Bratthammer, Mr. Bernt
Fare                               8.1125
Name: 444, dtype: object
445 Name    Dodge, Master. Washington
Fare                      81.8583
Name: 445, dtype: object
446 Name    Mellinger, Miss. Madeleine Violet
Fare                                 19.5
Name: 446, dtype: object
447 Name    Seward, Mr. Frederic Kimber
Fare                          26.55
Name: 447, dtype: object
448 Name    Baclini, Miss. Marie Catherine
Fare                           19.2583
Name: 448, dtype: object
449 Name    Peuchen, Major. Arthur Godfrey
Fare                              30.5
Name: 449, dtype: object
450 Name    West, Mr. Edwy Arthur
Fare                    27.75
Name: 450, dtype: object
451 Name    Hagland, Mr. Ingvald Olai Olsen
Fare                            19.9667
Name: 451, dtype: object
452 Name    Foreman, Mr. Benjamin Laventall
Fare                              27.75
Name: 452, dtype: object
453 Name    Goldenberg, Mr. Samuel L
Fare                     89.1042
Name: 453, dtype: object
454 Name    Peduzzi, Mr. Joseph
Fare                   8.05
Name: 454, dtype: object
455 Name    Jalsevac, Mr. Ivan
Fare                7.8958
Name: 455, dtype: object
456 Name    Millet, Mr. Francis Davis
Fare                        26.55
Name: 456, dtype: object
457 Name    Kenyon, Mrs. Frederick R (Marion)
Fare                              51.8625
Name: 457, dtype: object
458 Name    Toomey, Miss. Ellen
Fare                   10.5
Name: 458, dtype: object
459 Name    O'Connor, Mr. Maurice
Fare                     7.75
Name: 459, dtype: object
460 Name    Anderson, Mr. Harry
Fare                  26.55
Name: 460, dtype: object
461 Name    Morley, Mr. William
Fare                   8.05
Name: 461, dtype: object
462 Name    Gee, Mr. Arthur H
Fare                 38.5
Name: 462, dtype: object
463 Name    Milling, Mr. Jacob Christian
Fare                            13.0
Name: 463, dtype: object
464 Name    Maisner, Mr. Simon
Fare                  8.05
Name: 464, dtype: object
465 Name    Goncalves, Mr. Manuel Estanslas
Fare                               7.05
Name: 465, dtype: object
466 Name    Campbell, Mr. William
Fare                      0.0
Name: 466, dtype: object
467 Name    Smart, Mr. John Montgomery
Fare                         26.55
Name: 467, dtype: object

468 Name    Scanlan, Mr. James
Fare                 7.725
Name: 468, dtype: object
469 Name    Baclini, Miss. Helene Barbara
Fare                          19.2583
Name: 469, dtype: object
470 Name    Keefe, Mr. Arthur
Fare                 7.25
Name: 470, dtype: object
471 Name    Cacic, Mr. Luka
Fare             8.6625
Name: 471, dtype: object
472 Name    West, Mrs. Edwy Arthur (Ada Mary Worth)
Fare                                      27.75
Name: 472, dtype: object
473 Name    Jerwan, Mrs. Amin S (Marie Marthe Thuillard)
Fare                                         13.7917
Name: 473, dtype: object
474 Name    Strandberg, Miss. Ida Sofia
Fare                         9.8375
Name: 474, dtype: object
475 Name    Clifford, Mr. George Quincy
Fare                           52.0
Name: 475, dtype: object
476 Name    Renouf, Mr. Peter Henry
Fare                       21.0
Name: 476, dtype: object
477 Name    Braund, Mr. Lewis Richard
Fare                       7.0458
Name: 477, dtype: object
478 Name    Karlsson, Mr. Nils August
Fare                       7.5208
Name: 478, dtype: object
479 Name    Hirvonen, Miss. Hildur E
Fare                     12.2875
Name: 479, dtype: object
480 Name    Goodwin, Master. Harold Victor
Fare                              46.9
Name: 480, dtype: object
481 Name    Frost, Mr. Anthony Wood "Archie"
Fare                                 0.0
Name: 481, dtype: object
482 Name    Rouse, Mr. Richard Henry
Fare                        8.05
Name: 482, dtype: object
483 Name    Turkula, Mrs. (Hedwig)
Fare                    9.5875
Name: 483, dtype: object
484 Name    Bishop, Mr. Dickinson H
Fare                    91.0792
Name: 484, dtype: object
485 Name    Lefebre, Miss. Jeannie
Fare                   25.4667
Name: 485, dtype: object
486 Name    Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)
Fare                                               90.0
Name: 486, dtype: object
487 Name    Kent, Mr. Edward Austin
Fare                       29.7
Name: 487, dtype: object
488 Name    Somerton, Mr. Francis William
Fare                             8.05
Name: 488, dtype: object
489 Name    Coutts, Master. Eden Leslie "Neville"
Fare                                     15.9
Name: 489, dtype: object
490 Name    Hagland, Mr. Konrad Mathias Reiersen
Fare                                 19.9667
Name: 490, dtype: object
491 Name    Windelov, Mr. Einar
Fare                   7.25
Name: 491, dtype: object
492 Name    Molson, Mr. Harry Markland
Fare                          30.5
Name: 492, dtype: object
493 Name    Artagaveytia, Mr. Ramon
Fare                    49.5042
Name: 493, dtype: object
494 Name    Stanley, Mr. Edward Roland
Fare                          8.05
Name: 494, dtype: object
495 Name    Yousseff, Mr. Gerious
Fare                  14.4583
Name: 495, dtype: object
496 Name    Eustis, Miss. Elizabeth Mussey
Fare                           78.2667
Name: 496, dtype: object
497 Name    Shellard, Mr. Frederick William
Fare                               15.1
Name: 497, dtype: object
498 Name    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Fare                                             151.55
Name: 498, dtype: object
499 Name    Svensson, Mr. Olof
Fare                7.7958
Name: 499, dtype: object
500 Name    Calic, Mr. Petar
Fare              8.6625
Name: 500, dtype: object
501 Name    Canavan, Miss. Mary
Fare                   7.75
Name: 501, dtype: object
502 Name    O'Sullivan, Miss. Bridget Mary
Fare                            7.6292
Name: 502, dtype: object
503 Name    Laitinen, Miss. Kristina Sofia
Fare                            9.5875
Name: 503, dtype: object
504 Name    Maioni, Miss. Roberta
Fare                     86.5
Name: 504, dtype: object
505 Name    Penasco y Castellana, Mr. Victor de Satode
Fare                                         108.9
Name: 505, dtype: object
506 Name    Quick, Mrs. Frederick Charles (Jane Richards)
Fare                                             26.0
Name: 506, dtype: object
507 Name    Bradley, Mr. George ("George Arthur Brayton")
Fare                                            26.55
Name: 507, dtype: object
508 Name    Olsen, Mr. Henry Margido
Fare                      22.525
Name: 508, dtype: object
509 Name    Lang, Mr. Fang
Fare           56.4958
Name: 509, dtype: object
510 Name    Daly, Mr. Eugene Patrick
Fare                        7.75
Name: 510, dtype: object
511 Name    Webber, Mr. James
Fare                 8.05
Name: 511, dtype: object
512 Name    McGough, Mr. James Robert
Fare                      26.2875
Name: 512, dtype: object
513 Name    Rothschild, Mrs. Martin (Elizabeth L. Barrett)
Fare                                              59.4
Name: 513, dtype: object
514 Name    Coleff, Mr. Satio
Fare               7.4958
Name: 514, dtype: object
515 Name    Walker, Mr. William Anderson
Fare                         34.0208
Name: 515, dtype: object
516 Name    Lemore, Mrs. (Amelia Milley)
Fare                            10.5
Name: 516, dtype: object
517 Name    Ryan, Mr. Patrick
Fare                24.15
Name: 517, dtype: object
518 Name    Angle, Mrs. William A (Florence "Mary" Agnes H...
Fare                                                 26.0
Name: 518, dtype: object
519 Name    Pavlovic, Mr. Stefo
Fare                 7.8958
Name: 519, dtype: object
520 Name    Perreault, Miss. Anne
Fare                     93.5
Name: 520, dtype: object
521 Name    Vovk, Mr. Janko
Fare             7.8958
Name: 521, dtype: object
522 Name    Lahoud, Mr. Sarkis
Fare                 7.225
Name: 522, dtype: object
523 Name    Hippach, Mrs. Louis Albert (Ida Sophia Fischer)
Fare                                            57.9792
Name: 523, dtype: object
524 Name    Kassem, Mr. Fared
Fare               7.2292
Name: 524, dtype: object
525 Name    Farrell, Mr. James
Fare                  7.75
Name: 525, dtype: object
526 Name    Ridsdale, Miss. Lucy
Fare                    10.5
Name: 526, dtype: object
527 Name    Farthing, Mr. John
Fare              221.7792
Name: 527, dtype: object
528 Name    Salonen, Mr. Johan Werner
Fare                        7.925
Name: 528, dtype: object
529 Name    Hocking, Mr. Richard George
Fare                           11.5
Name: 529, dtype: object
530 Name    Quick, Miss. Phyllis May
Fare                        26.0
Name: 530, dtype: object
531 Name    Toufik, Mr. Nakli
Fare               7.2292
Name: 531, dtype: object
532 Name    Elias, Mr. Joseph Jr
Fare                  7.2292
Name: 532, dtype: object
533 Name    Peter, Mrs. Catherine (Catherine Rizk)
Fare                                   22.3583
Name: 533, dtype: object
534 Name    Cacic, Miss. Marija
Fare                 8.6625
Name: 534, dtype: object
535 Name    Hart, Miss. Eva Miriam
Fare                     26.25
Name: 535, dtype: object
536 Name    Butt, Major. Archibald Willingham
Fare                                26.55
Name: 536, dtype: object
537 Name    LeRoy, Miss. Bertha
Fare                106.425
Name: 537, dtype: object
538 Name    Risien, Mr. Samuel Beard
Fare                        14.5
Name: 538, dtype: object
539 Name    Frolicher, Miss. Hedwig Margaritha
Fare                                  49.5
Name: 539, dtype: object
540 Name    Crosby, Miss. Harriet R
Fare                       71.0
Name: 540, dtype: object
541 Name    Andersson, Miss. Ingeborg Constanzia
Fare                                  31.275
Name: 541, dtype: object
542 Name    Andersson, Miss. Sigrid Elisabeth
Fare                               31.275
Name: 542, dtype: object
543 Name    Beane, Mr. Edward
Fare                 26.0
Name: 543, dtype: object
544 Name    Douglas, Mr. Walter Donald
Fare                       106.425
Name: 544, dtype: object
545 Name    Nicholson, Mr. Arthur Ernest
Fare                            26.0
Name: 545, dtype: object
546 Name    Beane, Mrs. Edward (Ethel Clarke)
Fare                                 26.0
Name: 546, dtype: object
547 Name    Padro y Manent, Mr. Julian
Fare                       13.8625
Name: 547, dtype: object
548 Name    Goldsmith, Mr. Frank John
Fare                       20.525
Name: 548, dtype: object
549 Name    Davies, Master. John Morgan Jr
Fare                             36.75
Name: 549, dtype: object
550 Name    Thayer, Mr. John Borland Jr
Fare                       110.8833
Name: 550, dtype: object
551 Name    Sharp, Mr. Percival James R
Fare                           26.0
Name: 551, dtype: object
552 Name    O'Brien, Mr. Timothy
Fare                  7.8292
Name: 552, dtype: object
553 Name    Leeni, Mr. Fahim ("Philip Zenni")
Fare                                7.225
Name: 553, dtype: object
554 Name    Ohman, Miss. Velin
Fare                 7.775
Name: 554, dtype: object
555 Name    Wright, Mr. George
Fare                 26.55
Name: 555, dtype: object

556 Name    Duff Gordon, Lady. (Lucille Christiana Sutherl...
Fare                                                 39.6
Name: 556, dtype: object
557 Name    Robbins, Mr. Victor
Fare                227.525
Name: 557, dtype: object
558 Name    Taussig, Mrs. Emil (Tillie Mandelbaum)
Fare                                     79.65
Name: 558, dtype: object
559 Name    de Messemaeker, Mrs. Guillaume Joseph (Emma)
Fare                                            17.4
Name: 559, dtype: object
560 Name    Morrow, Mr. Thomas Rowan
Fare                        7.75
Name: 560, dtype: object
561 Name    Sivic, Mr. Husein
Fare               7.8958
Name: 561, dtype: object
562 Name    Norman, Mr. Robert Douglas
Fare                          13.5
Name: 562, dtype: object
563 Name    Simmons, Mr. John
Fare                 8.05
Name: 563, dtype: object
564 Name    Meanwell, Miss. (Marion Ogden)
Fare                              8.05
Name: 564, dtype: object
565 Name    Davies, Mr. Alfred J
Fare                   24.15
Name: 565, dtype: object
566 Name    Stoytcheff, Mr. Ilia
Fare                  7.8958
Name: 566, dtype: object
567 Name    Palsson, Mrs. Nils (Alma Cornelia Berglund)
Fare                                         21.075
Name: 567, dtype: object
568 Name    Doharr, Mr. Tannous
Fare                 7.2292
Name: 568, dtype: object
569 Name    Jonsson, Mr. Carl
Fare               7.8542
Name: 569, dtype: object
570 Name    Harris, Mr. George
Fare                  10.5
Name: 570, dtype: object
571 Name    Appleton, Mrs. Edward Dale (Charlotte Lamson)
Fare                                          51.4792
Name: 571, dtype: object
572 Name    Flynn, Mr. John Irwin ("Irving")
Fare                             26.3875
Name: 572, dtype: object
573 Name    Kelly, Miss. Mary
Fare                 7.75
Name: 573, dtype: object
574 Name    Rush, Mr. Alfred George John
Fare                            8.05
Name: 574, dtype: object
575 Name    Patchett, Mr. George
Fare                    14.5
Name: 575, dtype: object
576 Name    Garside, Miss. Ethel
Fare                    13.0
Name: 576, dtype: object
577 Name    Silvey, Mrs. William Baird (Alice Munger)
Fare                                         55.9
Name: 577, dtype: object
578 Name    Caram, Mrs. Joseph (Maria Elias)
Fare                             14.4583
Name: 578, dtype: object
579 Name    Jussila, Mr. Eiriik
Fare                  7.925
Name: 579, dtype: object
580 Name    Christy, Miss. Julie Rachel
Fare                           30.0
Name: 580, dtype: object
581 Name    Thayer, Mrs. John Borland (Marian Longstreth M...
Fare                                             110.8833
Name: 581, dtype: object
582 Name    Downton, Mr. William James
Fare                          26.0
Name: 582, dtype: object
583 Name    Ross, Mr. John Hugo
Fare                 40.125
Name: 583, dtype: object
584 Name    Paulner, Mr. Uscher
Fare                 8.7125
Name: 584, dtype: object
585 Name    Taussig, Miss. Ruth
Fare                  79.65
Name: 585, dtype: object
586 Name    Jarvis, Mr. John Denzil
Fare                       15.0
Name: 586, dtype: object
587 Name    Frolicher-Stehli, Mr. Maxmillian
Fare                                79.2
Name: 587, dtype: object
588 Name    Gilinski, Mr. Eliezer
Fare                     8.05
Name: 588, dtype: object
589 Name    Murdlin, Mr. Joseph
Fare                   8.05
Name: 589, dtype: object
590 Name    Rintamaki, Mr. Matti
Fare                   7.125
Name: 590, dtype: object
591 Name    Stephenson, Mrs. Walter Bertram (Martha Eustis)
Fare                                            78.2667
Name: 591, dtype: object
592 Name    Elsbury, Mr. William James
Fare                          7.25
Name: 592, dtype: object
593 Name    Bourke, Miss. Mary
Fare                  7.75
Name: 593, dtype: object
594 Name    Chapman, Mr. John Henry
Fare                       26.0
Name: 594, dtype: object
595 Name    Van Impe, Mr. Jean Baptiste
Fare                          24.15
Name: 595, dtype: object
596 Name    Leitch, Miss. Jessie Wills
Fare                          33.0
Name: 596, dtype: object
597 Name    Johnson, Mr. Alfred
Fare                    0.0
Name: 597, dtype: object
598 Name    Boulos, Mr. Hanna
Fare                7.225
Name: 598, dtype: object
599 Name    Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
Fare                                         56.9292
Name: 599, dtype: object
600 Name    Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...
Fare                                                 27.0
Name: 600, dtype: object
601 Name    Slabenoff, Mr. Petco
Fare                  7.8958
Name: 601, dtype: object
602 Name    Harrington, Mr. Charles H
Fare                         42.4
Name: 602, dtype: object
603 Name    Torber, Mr. Ernst William
Fare                         8.05
Name: 603, dtype: object
604 Name    Homer, Mr. Harry ("Mr E Haven")
Fare                              26.55
Name: 604, dtype: object
605 Name    Lindell, Mr. Edvard Bengtsson
Fare                            15.55
Name: 605, dtype: object
606 Name    Karaic, Mr. Milan
Fare               7.8958
Name: 606, dtype: object
607 Name    Daniel, Mr. Robert Williams
Fare                           30.5
Name: 607, dtype: object
608 Name    Laroche, Mrs. Joseph (Juliette Marie Louise La...
Fare                                              41.5792
Name: 608, dtype: object
609 Name    Shutes, Miss. Elizabeth W
Fare                     153.4625
Name: 609, dtype: object
610 Name    Andersson, Mrs. Anders Johan (Alfrida Konstant...
Fare                                               31.275
Name: 610, dtype: object
611 Name    Jardin, Mr. Jose Neto
Fare                     7.05
Name: 611, dtype: object
612 Name    Murphy, Miss. Margaret Jane
Fare                           15.5
Name: 612, dtype: object
613 Name    Horgan, Mr. John
Fare                7.75
Name: 613, dtype: object
614 Name    Brocklebank, Mr. William Alfred
Fare                               8.05
Name: 614, dtype: object
615 Name    Herman, Miss. Alice
Fare                   65.0
Name: 615, dtype: object
616 Name    Danbom, Mr. Ernst Gilbert
Fare                         14.4
Name: 616, dtype: object
617 Name    Lobb, Mrs. William Arthur (Cordelia K Stanlick)
Fare                                               16.1
Name: 617, dtype: object
618 Name    Becker, Miss. Marion Louise
Fare                           39.0
Name: 618, dtype: object
619 Name    Gavey, Mr. Lawrence
Fare                   10.5
Name: 619, dtype: object
620 Name    Yasbeck, Mr. Antoni
Fare                14.4542
Name: 620, dtype: object
621 Name    Kimball, Mr. Edwin Nelson Jr
Fare                         52.5542
Name: 621, dtype: object
622 Name    Nakid, Mr. Sahid
Fare             15.7417
Name: 622, dtype: object
623 Name    Hansen, Mr. Henry Damsgaard
Fare                         7.8542
Name: 623, dtype: object
624 Name    Bowen, Mr. David John "Dai"
Fare                           16.1
Name: 624, dtype: object
625 Name    Sutton, Mr. Frederick
Fare                  32.3208
Name: 625, dtype: object
626 Name    Kirkland, Rev. Charles Leonard
Fare                             12.35
Name: 626, dtype: object
627 Name    Longley, Miss. Gretchen Fiske
Fare                          77.9583
Name: 627, dtype: object
628 Name    Bostandyeff, Mr. Guentcho
Fare                       7.8958
Name: 628, dtype: object
629 Name    O'Connell, Mr. Patrick D
Fare                      7.7333
Name: 629, dtype: object
630 Name    Barkworth, Mr. Algernon Henry Wilson
Fare                                    30.0
Name: 630, dtype: object
631 Name    Lundahl, Mr. Johan Svensson
Fare                         7.0542
Name: 631, dtype: object
632 Name    Stahelin-Maeglin, Dr. Max
Fare                         30.5
Name: 632, dtype: object
633 Name    Parr, Mr. William Henry Marsh
Fare                              0.0
Name: 633, dtype: object
634 Name    Skoog, Miss. Mabel
Fare                  27.9
Name: 634, dtype: object
635 Name    Davis, Miss. Mary
Fare                 13.0
Name: 635, dtype: object
636 Name    Leinonen, Mr. Antti Gustaf
Fare                         7.925
Name: 636, dtype: object
637 Name    Collyer, Mr. Harvey
Fare                  26.25
Name: 637, dtype: object
638 Name    Panula, Mrs. Juha (Maria Emilia Ojala)
Fare                                   39.6875
Name: 638, dtype: object
639 Name    Thorneycroft, Mr. Percival
Fare                          16.1
Name: 639, dtype: object
640 Name    Jensen, Mr. Hans Peder
Fare                    7.8542
Name: 640, dtype: object
641 Name    Sagesser, Mlle. Emma
Fare                    69.3
Name: 641, dtype: object
642 Name    Skoog, Miss. Margit Elizabeth
Fare                             27.9
Name: 642, dtype: object
643 Name    Foo, Mr. Choong
Fare            56.4958
Name: 643, dtype: object
644 Name    Baclini, Miss. Eugenie
Fare                   19.2583
Name: 644, dtype: object
645 Name    Harper, Mr. Henry Sleeper
Fare                      76.7292
Name: 645, dtype: object
646 Name    Cor, Mr. Liudevit
Fare               7.8958
Name: 646, dtype: object
647 Name    Simonius-Blumer, Col. Oberst Alfons
Fare                                   35.5
Name: 647, dtype: object
648 Name    Willey, Mr. Edward
Fare                  7.55
Name: 648, dtype: object
649 Name    Stanley, Miss. Amy Zillah Elsie
Fare                               7.55
Name: 649, dtype: object
650 Name    Mitkoff, Mr. Mito
Fare               7.8958
Name: 650, dtype: object
651 Name    Doling, Miss. Elsie
Fare                   23.0
Name: 651, dtype: object
652 Name    Kalvik, Mr. Johannes Halvorsen
Fare                            8.4333
Name: 652, dtype: object
653 Name    O'Leary, Miss. Hanora "Norah"
Fare                           7.8292
Name: 653, dtype: object
654 Name    Hegarty, Miss. Hanora "Nora"
Fare                            6.75
Name: 654, dtype: object
655 Name    Hickman, Mr. Leonard Mark
Fare                         73.5
Name: 655, dtype: object
656 Name    Radeff, Mr. Alexander
Fare                   7.8958
Name: 656, dtype: object
657 Name    Bourke, Mrs. John (Catherine)
Fare                             15.5
Name: 657, dtype: object
658 Name    Eitemiller, Mr. George Floyd
Fare                            13.0
Name: 658, dtype: object
659 Name    Newell, Mr. Arthur Webster
Fare                       113.275
Name: 659, dtype: object
660 Name    Frauenthal, Dr. Henry William
Fare                           133.65
Name: 660, dtype: object
661 Name    Badt, Mr. Mohamed
Fare                7.225
Name: 661, dtype: object
662 Name    Colley, Mr. Edward Pomeroy
Fare                       25.5875
Name: 662, dtype: object
663 Name    Coleff, Mr. Peju
Fare              7.4958
Name: 663, dtype: object
664 Name    Lindqvist, Mr. Eino William
Fare                          7.925
Name: 664, dtype: object
665 Name    Hickman, Mr. Lewis
Fare                  73.5
Name: 665, dtype: object
666 Name    Butler, Mr. Reginald Fenton
Fare                           13.0
Name: 666, dtype: object
667 Name    Rommetvedt, Mr. Knud Paust
Fare                         7.775
Name: 667, dtype: object
668 Name    Cook, Mr. Jacob
Fare               8.05
Name: 668, dtype: object
669 Name    Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)
Fare                                                 52.0
Name: 669, dtype: object
670 Name    Brown, Mrs. Thomas William Solomon (Elizabeth ...
Fare                                                 39.0
Name: 670, dtype: object
671 Name    Davidson, Mr. Thornton
Fare                      52.0
Name: 671, dtype: object
672 Name    Mitchell, Mr. Henry Michael
Fare                           10.5
Name: 672, dtype: object
673 Name    Wilhelms, Mr. Charles
Fare                     13.0
Name: 673, dtype: object
674 Name    Watson, Mr. Ennis Hastings
Fare                           0.0
Name: 674, dtype: object
675 Name    Edvardsson, Mr. Gustaf Hjalmar
Fare                             7.775
Name: 675, dtype: object
676 Name    Sawyer, Mr. Frederick Charles
Fare                             8.05
Name: 676, dtype: object
677 Name    Turja, Miss. Anna Sofia
Fare                     9.8417
Name: 677, dtype: object
678 Name    Goodwin, Mrs. Frederick (Augusta Tyler)
Fare                                       46.9
Name: 678, dtype: object
679 Name    Cardeza, Mr. Thomas Drake Martinez
Fare                              512.3292
Name: 679, dtype: object
680 Name    Peters, Miss. Katie
Fare                 8.1375
Name: 680, dtype: object
681 Name    Hassab, Mr. Hammad
Fare               76.7292
Name: 681, dtype: object
682 Name    Olsvigen, Mr. Thor Anderson
Fare                          9.225
Name: 682, dtype: object
683 Name    Goodwin, Mr. Charles Edward
Fare                           46.9
Name: 683, dtype: object
684 Name    Brown, Mr. Thomas William Solomon
Fare                                 39.0
Name: 684, dtype: object
685 Name    Laroche, Mr. Joseph Philippe Lemercier
Fare                                   41.5792
Name: 685, dtype: object
686 Name    Panula, Mr. Jaako Arnold
Fare                     39.6875
Name: 686, dtype: object
687 Name    Dakic, Mr. Branko
Fare              10.1708
Name: 687, dtype: object
688 Name    Fischer, Mr. Eberhard Thelander
Fare                             7.7958
Name: 688, dtype: object
689 Name    Madill, Miss. Georgette Alexandra
Fare                             211.3375
Name: 689, dtype: object
690 Name    Dick, Mr. Albert Adrian
Fare                       57.0
Name: 690, dtype: object
691 Name    Karun, Miss. Manca
Fare               13.4167
Name: 691, dtype: object
692 Name    Lam, Mr. Ali
Fare         56.4958
Name: 692, dtype: object
693 Name    Saad, Mr. Khalil
Fare               7.225

Name: 693, dtype: object
694 Name    Weir, Col. John
Fare              26.55
Name: 694, dtype: object
695 Name    Chapman, Mr. Charles Henry
Fare                          13.5
Name: 695, dtype: object
696 Name    Kelly, Mr. James
Fare                8.05
Name: 696, dtype: object
697 Name    Mullens, Miss. Katherine "Katie"
Fare                              7.7333
Name: 697, dtype: object
698 Name    Thayer, Mr. John Borland
Fare                    110.8833
Name: 698, dtype: object
699 Name    Humblen, Mr. Adolf Mathias Nicolai Olsen
Fare                                        7.65
Name: 699, dtype: object
700 Name    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
Fare                                              227.525
Name: 700, dtype: object
701 Name    Silverthorne, Mr. Spencer Victor
Fare                             26.2875
Name: 701, dtype: object
702 Name    Barbara, Miss. Saiide
Fare                  14.4542
Name: 702, dtype: object
703 Name    Gallagher, Mr. Martin
Fare                   7.7417
Name: 703, dtype: object
704 Name    Hansen, Mr. Henrik Juul
Fare                     7.8542
Name: 704, dtype: object
705 Name    Morley, Mr. Henry Samuel ("Mr Henry Marshall")
Fare                                              26.0
Name: 705, dtype: object
706 Name    Kelly, Mrs. Florence "Fannie"
Fare                             13.5
Name: 706, dtype: object
707 Name    Calderhead, Mr. Edward Pennington
Fare                              26.2875
Name: 707, dtype: object
708 Name    Cleaver, Miss. Alice
Fare                  151.55
Name: 708, dtype: object
709 Name    Moubarek, Master. Halim Gonios ("William George")
Fare                                              15.2458
Name: 709, dtype: object
710 Name    Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
Fare                                             49.5042
Name: 710, dtype: object
711 Name    Klaber, Mr. Herman
Fare                 26.55
Name: 711, dtype: object
712 Name    Taylor, Mr. Elmer Zebley
Fare                        52.0
Name: 712, dtype: object
713 Name    Larsson, Mr. August Viktor
Fare                        9.4833
Name: 713, dtype: object
714 Name    Greenberg, Mr. Samuel
Fare                     13.0
Name: 714, dtype: object
715 Name    Soholt, Mr. Peter Andreas Lauritz Andersen
Fare                                          7.65
Name: 715, dtype: object
716 Name    Endres, Miss. Caroline Louise
Fare                          227.525
Name: 716, dtype: object
717 Name    Troutt, Miss. Edwina Celia "Winnie"
Fare                                   10.5
Name: 717, dtype: object
718 Name    McEvoy, Mr. Michael
Fare                   15.5
Name: 718, dtype: object
719 Name    Johnson, Mr. Malkolm Joackim
Fare                           7.775
Name: 719, dtype: object
720 Name    Harper, Miss. Annie Jessie "Nina"
Fare                                 33.0
Name: 720, dtype: object
721 Name    Jensen, Mr. Svend Lauritz
Fare                       7.0542
Name: 721, dtype: object
722 Name    Gillespie, Mr. William Henry
Fare                            13.0
Name: 722, dtype: object
723 Name    Hodges, Mr. Henry Price
Fare                       13.0
Name: 723, dtype: object
724 Name    Chambers, Mr. Norman Campbell
Fare                             53.1
Name: 724, dtype: object
725 Name    Oreskovic, Mr. Luka
Fare                 8.6625
Name: 725, dtype: object
726 Name    Renouf, Mrs. Peter Henry (Lillian Jefferys)
Fare                                           21.0
Name: 726, dtype: object
727 Name    Mannion, Miss. Margareth
Fare                      7.7375
Name: 727, dtype: object
728 Name    Bryhl, Mr. Kurt Arnold Gottfrid
Fare                               26.0
Name: 728, dtype: object
729 Name    Ilmakangas, Miss. Pieta Sofia
Fare                            7.925
Name: 729, dtype: object
730 Name    Allen, Miss. Elisabeth Walton
Fare                         211.3375
Name: 730, dtype: object
731 Name    Hassan, Mr. Houssein G N
Fare                     18.7875
Name: 731, dtype: object
732 Name    Knight, Mr. Robert J
Fare                     0.0
Name: 732, dtype: object
733 Name    Berriman, Mr. William John
Fare                          13.0
Name: 733, dtype: object
734 Name    Troupiansky, Mr. Moses Aaron
Fare                            13.0
Name: 734, dtype: object
735 Name    Williams, Mr. Leslie
Fare                    16.1
Name: 735, dtype: object
736 Name    Ford, Mrs. Edward (Margaret Ann Watson)
Fare                                     34.375
Name: 736, dtype: object
737 Name    Lesurer, Mr. Gustave J
Fare                  512.3292
Name: 737, dtype: object
738 Name    Ivanoff, Mr. Kanio
Fare                7.8958
Name: 738, dtype: object
739 Name    Nankoff, Mr. Minko
Fare                7.8958
Name: 739, dtype: object
740 Name    Hawksford, Mr. Walter James
Fare                           30.0
Name: 740, dtype: object
741 Name    Cavendish, Mr. Tyrell William
Fare                            78.85
Name: 741, dtype: object
742 Name    Ryerson, Miss. Susan Parker "Suzette"
Fare                                  262.375
Name: 742, dtype: object
743 Name    McNamee, Mr. Neal
Fare                 16.1
Name: 743, dtype: object
744 Name    Stranden, Mr. Juho
Fare                 7.925
Name: 744, dtype: object
745 Name    Crosby, Capt. Edward Gifford
Fare                            71.0
Name: 745, dtype: object
746 Name    Abbott, Mr. Rossmore Edward
Fare                          20.25
Name: 746, dtype: object
747 Name    Sinkkonen, Miss. Anna
Fare                     13.0
Name: 747, dtype: object
748 Name    Marvin, Mr. Daniel Warner
Fare                         53.1
Name: 748, dtype: object
749 Name    Connaghton, Mr. Michael
Fare                       7.75
Name: 749, dtype: object
750 Name    Wells, Miss. Joan
Fare                 23.0
Name: 750, dtype: object
751 Name    Moor, Master. Meier
Fare                 12.475
Name: 751, dtype: object
752 Name    Vande Velde, Mr. Johannes Joseph
Fare                                 9.5
Name: 752, dtype: object
753 Name    Jonkoff, Mr. Lalio
Fare                7.8958
Name: 753, dtype: object
754 Name    Herman, Mrs. Samuel (Jane Laver)
Fare                                65.0
Name: 754, dtype: object
755 Name    Hamalainen, Master. Viljo
Fare                         14.5
Name: 755, dtype: object
756 Name    Carlsson, Mr. August Sigfrid
Fare                          7.7958
Name: 756, dtype: object
757 Name    Bailey, Mr. Percy Andrew
Fare                        11.5
Name: 757, dtype: object
758 Name    Theobald, Mr. Thomas Leonard
Fare                            8.05
Name: 758, dtype: object
759 Name    Rothes, the Countess. of (Lucy Noel Martha Dye...
Fare                                                 86.5
Name: 759, dtype: object
760 Name    Garfirth, Mr. John
Fare                  14.5
Name: 760, dtype: object
761 Name    Nirva, Mr. Iisakki Antino Aijo
Fare                             7.125
Name: 761, dtype: object
762 Name    Barah, Mr. Hanna Assi
Fare                   7.2292
Name: 762, dtype: object
763 Name    Carter, Mrs. William Ernest (Lucile Polk)
Fare                                        120.0
Name: 763, dtype: object
764 Name    Eklund, Mr. Hans Linus
Fare                     7.775
Name: 764, dtype: object
765 Name    Hogeboom, Mrs. John C (Anna Andrews)
Fare                                 77.9583
Name: 765, dtype: object
766 Name    Brewe, Dr. Arthur Jackson
Fare                         39.6
Name: 766, dtype: object
767 Name    Mangan, Miss. Mary
Fare                  7.75
Name: 767, dtype: object
768 Name    Moran, Mr. Daniel J
Fare                  24.15
Name: 768, dtype: object
769 Name    Gronnestad, Mr. Daniel Danielsen
Fare                              8.3625
Name: 769, dtype: object
770 Name    Lievens, Mr. Rene Aime
Fare                       9.5
Name: 770, dtype: object
771 Name    Jensen, Mr. Niels Peder
Fare                     7.8542
Name: 771, dtype: object
772 Name    Mack, Mrs. (Mary)
Fare                 10.5
Name: 772, dtype: object
773 Name    Elias, Mr. Dibo
Fare              7.225
Name: 773, dtype: object
774 Name    Hocking, Mrs. Elizabeth (Eliza Needs)
Fare                                     23.0
Name: 774, dtype: object
775 Name    Myhrman, Mr. Pehr Fabian Oliver Malkolm
Fare                                       7.75
Name: 775, dtype: object
776 Name    Tobin, Mr. Roger
Fare                7.75
Name: 776, dtype: object
777 Name    Emanuel, Miss. Virginia Ethel
Fare                           12.475
Name: 777, dtype: object
778 Name    Kilgannon, Mr. Thomas J
Fare                     7.7375
Name: 778, dtype: object
779 Name    Robert, Mrs. Edward Scott (Elisabeth Walton Mc...
Fare                                             211.3375
Name: 779, dtype: object
780 Name    Ayoub, Miss. Banoura
Fare                  7.2292
Name: 780, dtype: object
781 Name    Dick, Mrs. Albert Adrian (Vera Gillespie)
Fare                                         57.0
Name: 781, dtype: object
782 Name    Long, Mr. Milton Clyde
Fare                      30.0
Name: 782, dtype: object
783 Name    Johnston, Mr. Andrew G
Fare                     23.45
Name: 783, dtype: object
784 Name    Ali, Mr. William
Fare                7.05
Name: 784, dtype: object
785 Name    Harmer, Mr. Abraham (David Lishin)
Fare                                  7.25
Name: 785, dtype: object
786 Name    Sjoblom, Miss. Anna Sofia
Fare                       7.4958
Name: 786, dtype: object
787 Name    Rice, Master. George Hugh
Fare                       29.125
Name: 787, dtype: object
788 Name    Dean, Master. Bertram Vere
Fare                        20.575
Name: 788, dtype: object
789 Name    Guggenheim, Mr. Benjamin
Fare                        79.2
Name: 789, dtype: object
790 Name    Keane, Mr. Andrew "Andy"
Fare                        7.75
Name: 790, dtype: object
791 Name    Gaskell, Mr. Alfred
Fare                   26.0
Name: 791, dtype: object
792 Name    Sage, Miss. Stella Anna
Fare                      69.55
Name: 792, dtype: object
793 Name    Hoyt, Mr. William Fisher
Fare                     30.6958
Name: 793, dtype: object
794 Name    Dantcheff, Mr. Ristiu
Fare                   7.8958
Name: 794, dtype: object
795 Name    Otter, Mr. Richard
Fare                  13.0
Name: 795, dtype: object
796 Name    Leader, Dr. Alice (Farnham)
Fare                        25.9292
Name: 796, dtype: object
797 Name    Osman, Mrs. Mara
Fare              8.6833
Name: 797, dtype: object
798 Name    Ibrahim Shawah, Mr. Yousseff
Fare                          7.2292
Name: 798, dtype: object
799 Name    Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...
Fare                                                24.15
Name: 799, dtype: object
800 Name    Ponesell, Mr. Martin
Fare                    13.0
Name: 800, dtype: object
801 Name    Collyer, Mrs. Harvey (Charlotte Annie Tate)
Fare                                          26.25
Name: 801, dtype: object
802 Name    Carter, Master. William Thornton II
Fare                                  120.0
Name: 802, dtype: object
803 Name    Thomas, Master. Assad Alexander
Fare                             8.5167
Name: 803, dtype: object
804 Name    Hedman, Mr. Oskar Arvid
Fare                      6.975
Name: 804, dtype: object
805 Name    Johansson, Mr. Karl Johan
Fare                        7.775
Name: 805, dtype: object
806 Name    Andrews, Mr. Thomas Jr
Fare                       0.0
Name: 806, dtype: object
807 Name    Pettersson, Miss. Ellen Natalia
Fare                              7.775
Name: 807, dtype: object
808 Name    Meyer, Mr. August
Fare                 13.0
Name: 808, dtype: object
809 Name    Chambers, Mrs. Norman Campbell (Bertha Griggs)
Fare                                              53.1
Name: 809, dtype: object
810 Name    Alexander, Mr. William
Fare                    7.8875
Name: 810, dtype: object
811 Name    Lester, Mr. James
Fare                24.15
Name: 811, dtype: object
812 Name    Slemen, Mr. Richard James
Fare                         10.5
Name: 812, dtype: object
813 Name    Andersson, Miss. Ebba Iris Alfrida
Fare                                31.275
Name: 813, dtype: object
814 Name    Tomlin, Mr. Ernest Portage
Fare                          8.05
Name: 814, dtype: object
815 Name    Fry, Mr. Richard
Fare                 0.0
Name: 815, dtype: object
816 Name    Heininen, Miss. Wendla Maria
Fare                           7.925
Name: 816, dtype: object
817 Name    Mallet, Mr. Albert
Fare               37.0042
Name: 817, dtype: object
818 Name    Holm, Mr. John Fredrik Alexander
Fare                                6.45
Name: 818, dtype: object
819 Name    Skoog, Master. Karl Thorsten
Fare                            27.9
Name: 819, dtype: object
820 Name    Hays, Mrs. Charles Melville (Clara Jennings Gr...
Fare                                                 93.5
Name: 820, dtype: object
821 Name    Lulic, Mr. Nikola
Fare               8.6625
Name: 821, dtype: object
822 Name    Reuchlin, Jonkheer. John George
Fare                                0.0
Name: 822, dtype: object
823 Name    Moor, Mrs. (Beila)
Fare                12.475
Name: 823, dtype: object
824 Name    Panula, Master. Urho Abraham
Fare                         39.6875
Name: 824, dtype: object
825 Name    Flynn, Mr. John
Fare               6.95
Name: 825, dtype: object
826 Name    Lam, Mr. Len
Fare         56.4958
Name: 826, dtype: object
827 Name    Mallet, Master. Andre
Fare                  37.0042
Name: 827, dtype: object
828 Name    McCormack, Mr. Thomas Joseph
Fare                            7.75
Name: 828, dtype: object
829 Name    Stone, Mrs. George Nelson (Martha Evelyn)
Fare                                         80.0
Name: 829, dtype: object
830 Name    Yasbeck, Mrs. Antoni (Selini Alexander)
Fare                                    14.4542
Name: 830, dtype: object
831 Name    Richards, Master. George Sibley
Fare                              18.75
Name: 831, dtype: object
832 Name    Saad, Mr. Amin
Fare            7.2292
Name: 832, dtype: object
833 Name    Augustsson, Mr. Albert
Fare                    7.8542
Name: 833, dtype: object

834 Name    Allum, Mr. Owen George
Fare                       8.3
Name: 834, dtype: object
835 Name    Compton, Miss. Sara Rebecca
Fare                        83.1583
Name: 835, dtype: object
836 Name    Pasic, Mr. Jakob
Fare              8.6625
Name: 836, dtype: object
837 Name    Sirota, Mr. Maurice
Fare                   8.05
Name: 837, dtype: object
838 Name    Chip, Mr. Chang
Fare            56.4958
Name: 838, dtype: object
839 Name    Marechal, Mr. Pierre
Fare                    29.7
Name: 839, dtype: object
840 Name    Alhomaki, Mr. Ilmari Rudolf
Fare                          7.925
Name: 840, dtype: object
841 Name    Mudd, Mr. Thomas Charles
Fare                        10.5
Name: 841, dtype: object
842 Name    Serepeca, Miss. Augusta
Fare                       31.0
Name: 842, dtype: object
843 Name    Lemberopolous, Mr. Peter L
Fare                        6.4375
Name: 843, dtype: object
844 Name    Culumovic, Mr. Jeso
Fare                 8.6625
Name: 844, dtype: object
845 Name    Abbing, Mr. Anthony
Fare                   7.55
Name: 845, dtype: object
846 Name    Sage, Mr. Douglas Bullen
Fare                       69.55
Name: 846, dtype: object
847 Name    Markoff, Mr. Marin
Fare                7.8958
Name: 847, dtype: object
848 Name    Harper, Rev. John
Fare                 33.0
Name: 848, dtype: object
849 Name    Goldenberg, Mrs. Samuel L (Edwiga Grabowska)
Fare                                         89.1042
Name: 849, dtype: object
850 Name    Andersson, Master. Sigvard Harald Elias
Fare                                     31.275
Name: 850, dtype: object
851 Name    Svensson, Mr. Johan
Fare                  7.775
Name: 851, dtype: object
852 Name    Boulos, Miss. Nourelain
Fare                    15.2458
Name: 852, dtype: object
853 Name    Lines, Miss. Mary Conover
Fare                         39.4
Name: 853, dtype: object
854 Name    Carter, Mrs. Ernest Courtenay (Lilian Hughes)
Fare                                             26.0
Name: 854, dtype: object
855 Name    Aks, Mrs. Sam (Leah Rosen)
Fare                          9.35
Name: 855, dtype: object
856 Name    Wick, Mrs. George Dennick (Mary Hitchcock)
Fare                                      164.8667
Name: 856, dtype: object
857 Name    Daly, Mr. Peter Denis
Fare                     26.55
Name: 857, dtype: object
858 Name    Baclini, Mrs. Solomon (Latifa Qurban)
Fare                                  19.2583
Name: 858, dtype: object
859 Name    Razi, Mr. Raihed
Fare              7.2292
Name: 859, dtype: object
860 Name    Hansen, Mr. Claus Peter
Fare                    14.1083
Name: 860, dtype: object
861 Name    Giles, Mr. Frederick Edward
Fare                           11.5
Name: 861, dtype: object
862 Name    Swift, Mrs. Frederick Joel (Margaret Welles Ba...
Fare                                              25.9292
Name: 862, dtype: object
863 Name    Sage, Miss. Dorothy Edith "Dolly"
Fare                                69.55
Name: 863, dtype: object
864 Name    Gill, Mr. John William
Fare                      13.0
Name: 864, dtype: object
865 Name    Bystrom, Mrs. (Karolina)
Fare                        13.0
Name: 865, dtype: object
866 Name    Duran y More, Miss. Asuncion
Fare                         13.8583
Name: 866, dtype: object
867 Name    Roebling, Mr. Washington Augustus II
Fare                                 50.4958
Name: 867, dtype: object
868 Name    van Melkebeke, Mr. Philemon
Fare                            9.5
Name: 868, dtype: object
869 Name    Johnson, Master. Harold Theodor
Fare                            11.1333
Name: 869, dtype: object
870 Name    Balkic, Mr. Cerin
Fare               7.8958
Name: 870, dtype: object
871 Name    Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
Fare                                             52.5542
Name: 871, dtype: object
872 Name    Carlsson, Mr. Frans Olof
Fare                         5.0
Name: 872, dtype: object
873 Name    Vander Cruyssen, Mr. Victor
Fare                            9.0
Name: 873, dtype: object
874 Name    Abelson, Mrs. Samuel (Hannah Wizosky)
Fare                                     24.0
Name: 874, dtype: object
875 Name    Najib, Miss. Adele Kiamie "Jane"
Fare                               7.225
Name: 875, dtype: object
876 Name    Gustafsson, Mr. Alfred Ossian
Fare                           9.8458
Name: 876, dtype: object
877 Name    Petroff, Mr. Nedelio
Fare                  7.8958
Name: 877, dtype: object
878 Name    Laleff, Mr. Kristo
Fare                7.8958
Name: 878, dtype: object
879 Name    Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
Fare                                          83.1583
Name: 879, dtype: object
880 Name    Shelley, Mrs. William (Imanita Parrish Hall)
Fare                                            26.0
Name: 880, dtype: object
881 Name    Markun, Mr. Johann
Fare                7.8958
Name: 881, dtype: object
882 Name    Dahlberg, Miss. Gerda Ulrika
Fare                         10.5167
Name: 882, dtype: object
883 Name    Banfield, Mr. Frederick James
Fare                             10.5
Name: 883, dtype: object
884 Name    Sutehall, Mr. Henry Jr
Fare                      7.05
Name: 884, dtype: object
885 Name    Rice, Mrs. William (Margaret Norton)
Fare                                  29.125
Name: 885, dtype: object
886 Name    Montvila, Rev. Juozas
Fare                     13.0
Name: 886, dtype: object
887 Name    Graham, Miss. Margaret Edith
Fare                            30.0
Name: 887, dtype: object
888 Name    Johnston, Miss. Catherine Helen "Carrie"
Fare                                       23.45
Name: 888, dtype: object
889 Name    Behr, Mr. Karl Howell
Fare                     30.0
Name: 889, dtype: object
890 Name    Dooley, Mr. Patrick
Fare                   7.75
Name: 890, dtype: object

# Sorting

In [62]:
titanic2.head(2)

,Velocity Corporate Training Center - Python and Data Science Batch,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,MOCK INTERVIEW - II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr No,Student Name,Group,Batch,Interview Time,Interviewer,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df_titanic.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [35]:
df_titanic.sort_values("Age").head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [36]:
df_titanic.sort_values("Age",ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [37]:
df_titanic.sort_values("Age",ascending=False)[0:1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

In [39]:
"""
df_titanic.sort_values(
    by,
    axis=0,
    ascending=True,
    inplace=False,
    kind='quicksort',
    na_position='last',
    ignore_index=False,
    key: 'ValueKeyFunc' = None,
)
"""

df_titanic.sort_values(["Age","Name"],ascending=[0,1])


# 0 decending 1 Ascending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
354,355,0,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C
495,496,0,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C
240,241,0,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S

# Exporting

In [40]:
df_titanic["test col"]=0
#Creates a new column with values zero

In [41]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,test col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [42]:
df_titanic["test col"]=df_titanic["Age"]*2

In [43]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,test col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,54.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,38.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,52.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,64.0

df_titanic.to_csv("C:\\Users\\91976\\Downloads\\DATA SCI BATCH\\Dataset\\titanic1111.csv")

df_titanic.to_excel("C:\\Users\\91976\\Downloads\\DATA SCI BATCH\\Dataset\\titanic1111.xlsx",index=false)

df_titanic.to_csv("C:\\Users\\91976\\Downloads\\DATA SCI BATCH\\Dataset\\titanic1111.txt",sep="\t")

# loc and iloc

Pandas library of python is very useful for the manipulation of mathematical data and is widely used in the field of machine learning. It comprises of many methods for its proper functioning. loc() and iloc() are one of those methods. These **are used in slicing** of data from the Pandas DataFrame. They help in the convenient selection of data from the DataFrame. They **are used in filtering the data according to some conditions.** 

loc() : loc() is **label based data selecting method** which means that we have to pass the name of the row or column which we want to select. This method includes the last element of the range passed in it, unlike iloc(). **loc() can accept the boolean data unlike iloc()** .

iloc() : iloc() is a **indexed based selecting method** which means that we have to pass integer index in the method to select specific row/column. This method does not include the last element of the range passed in it unlike loc(). iloc() does not accept the boolean data unlike loc().

In [44]:
data = pd.DataFrame({'Brand' : ['Maruti', 'Hyundai', 'Tata',
                                'Mahindra', 'Maruti', 'Hyundai',
                                'Renault', 'Tata', 'Maruti'],
                     'Year' : [2012, 2014, 2011, 2015, 2012, 
                               2016, 2014, 2018, 2019],
                     'Kms Driven' : [50000, 30000, 60000, 
                                     25000, 10000, 46000, 
                                     31000, 15000, 12000],
                     'City' : ['Gurgaon', 'Delhi', 'Mumbai', 
                               'Delhi', 'Mumbai', 'Delhi', 
                               'Mumbai','Chennai',  'Ghaziabad'],
                     'Mileage' :  [28, 27, 25, 26, 28, 
                                   29, 24, 21, 24]})

In [45]:
df1=pd.DataFrame(data)

In [51]:
df1.index=["a","b","c","d","e","f","g","h",3]
#NOTICE: all indexes need not be of same datatype

In [52]:
df1

      Brand  Year  Kms Driven       City  Mileage
a    Maruti  2012       50000    Gurgaon       28
b   Hyundai  2014       30000      Delhi       27
c      Tata  2011       60000     Mumbai       25
d  Mahindra  2015       25000      Delhi       26
e    Maruti  2012       10000     Mumbai       28
f   Hyundai  2016       46000      Delhi       29
g   Renault  2014       31000     Mumbai       24
h      Tata  2018       15000    Chennai       21
3    Maruti  2019       12000  Ghaziabad       24

In [54]:
df1.iloc[3:7,0:3]
#Purely integer-location based indexing for selection by position.

      Brand  Year  Kms Driven
d  Mahindra  2015       25000
e    Maruti  2012       10000
f   Hyundai  2016       46000
g   Renault  2014       31000

In [55]:
#df1.iloc[3:7,["Year"]]
#ERROR: .iloc requires numeric indexers, got ['Year']

In [56]:
#df1.loc[3:7,["Brand","Mileage"]]
#TypeError: cannot do slice indexing on Index with these indexers [3] of type int
#Access a group of rows and columns by label(s) or a boolean array.

In [61]:
df1.iloc[5: , :]
#Rows from 5th row and all columns

     Brand  Year  Kms Driven       City  Mileage
f  Hyundai  2016       46000      Delhi       29
g  Renault  2014       31000     Mumbai       24
h     Tata  2018       15000    Chennai       21
3   Maruti  2019       12000  Ghaziabad       24

In [64]:
df1.loc["a":"h","Brand"]

a      Maruti
b     Hyundai
c        Tata
d    Mahindra
e      Maruti
f     Hyundai
g     Renault
h        Tata
Name: Brand, dtype: object

In [65]:
df1.iloc[2:5,:]

      Brand  Year  Kms Driven    City  Mileage
c      Tata  2011       60000  Mumbai       25
d  Mahindra  2015       25000   Delhi       26
e    Maruti  2012       10000  Mumbai       28

In [66]:
# df1.iloc["AA":5,:]
#TypeError: cannot do positional indexing on Index with these indexers [AA] of type str

In [69]:
df1.loc["h","Brand"]

'Tata'

In [70]:
print(df1)

      Brand  Year  Kms Driven       City  Mileage
a    Maruti  2012       50000    Gurgaon       28
b   Hyundai  2014       30000      Delhi       27
c      Tata  2011       60000     Mumbai       25
d  Mahindra  2015       25000      Delhi       26
e    Maruti  2012       10000     Mumbai       28
f   Hyundai  2016       46000      Delhi       29
g   Renault  2014       31000     Mumbai       24
h      Tata  2018       15000    Chennai       21
3    Maruti  2019       12000  Ghaziabad       24

In [72]:
(df1["Mileage"]>25) & (df1["Kms Driven"]>10000)

a     True
b     True
c    False
d     True
e    False
f     True
g    False
h    False
3    False
dtype: bool

In [76]:
#.loc[] can accept arrays of booleans
df1.loc[df1["Mileage"]>25]

      Brand  Year  Kms Driven     City  Mileage
a    Maruti  2012       50000  Gurgaon       28
b   Hyundai  2014       30000    Delhi       27
d  Mahindra  2015       25000    Delhi       26
e    Maruti  2012       10000   Mumbai       28
f   Hyundai  2016       46000    Delhi       29

In [81]:
df1.loc[(df1["Mileage"]>25) & (df1["Kms Driven"]>10000)]

      Brand  Year  Kms Driven     City  Mileage
a    Maruti  2012       50000  Gurgaon       28
b   Hyundai  2014       30000    Delhi       27
d  Mahindra  2015       25000    Delhi       26
f   Hyundai  2016       46000    Delhi       29

In [85]:
#df1.iloc[df1["Mileage"]>25]
#ValueError: iLocation based boolean indexing cannot use an indexable as a mask
list(df1["Mileage"]>25)

[True, True, False, True, True, True, False, False, False]

In [86]:
df1.iloc[list(df1["Mileage"]>25)]

      Brand  Year  Kms Driven     City  Mileage
a    Maruti  2012       50000  Gurgaon       28
b   Hyundai  2014       30000    Delhi       27
d  Mahindra  2015       25000    Delhi       26
e    Maruti  2012       10000   Mumbai       28
f   Hyundai  2016       46000    Delhi       29

In [106]:
list(df1['Mileage']>25)

[True, True, False, True, True, True, False, False, False]

In [87]:
print(type(df1['Mileage']>25))
df1['Mileage']>25

<class 'pandas.core.series.Series'>

a     True
b     True
c    False
d     True
e     True
f     True
g    False
h    False
3    False
Name: Mileage, dtype: bool

# Handling Missing Data

- removing the missing data- dropna()


- fill the some default values- fillna()

- drop_duplicates()

In [3]:
import pandas as pd
t=pd.read_csv(r"C:\Users\admin\Desktop\data_science\data\\titanic_train.csv")
df_t=pd.DataFrame(t)
df_t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df_t.shape

(891, 12)

In [91]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [95]:
df_t.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                                                                                       ..
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
333          0         1       Graham, Mr. George Edward                             male    38.0  0      1      PC 17582  153.4625  C91    S           1
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
Length: 183, dtype: int64

In [96]:
# df_t=df_t.dropna()
df_t.dropna(inplace=True)
df_t.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [97]:
df_t.shape

(183, 12)

In [98]:
df_t2=pd.DataFrame(t)

In [99]:
df_t2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [102]:
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [103]:
df_t2["Age"].fillna(df_t2["Age"].mean(),inplace=True)

In [104]:
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [106]:
df_t2["Cabin"].mode()

0        B96 B98
1    C23 C25 C27
2             G6
dtype: object

In [108]:
df_t2["Cabin"].fillna("G6",inplace=True)

In [109]:
df_t2["Cabin"]

0        G6
1       C85
2        G6
3      C123
4        G6
       ...
886      G6
887     B42
888      G6
889    C148
890      G6
Name: Cabin, Length: 891, dtype: object

In [110]:
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [111]:
df_t2["Embarked"].fillna("S",inplace=True)

In [112]:
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [114]:
df_t2.duplicated()
#Return boolean Series denoting duplicate rows.Considering certain columns is optional.

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [116]:
data = pd.DataFrame({'Brand' : ['Maruti','Maruti', 'Hyundai', 'Tata',
                                'Mahindra', 'Maruti', 'Hyundai',
                                'Renault', 'Tata', 'Maruti'],
                     'Year' : [2012,2012, 2014, 2011, 2015, 2012, 
                               2016, 2014, 2018, 2019],
                     'Kms Driven' : [50000,50000, 30000, 60000, 
                                     25000, 10000, 46000, 
                                     31000, 15000, 12000],
                     'City' : ['Gurgaon','Gurgaon', 'Delhi', 'Mumbai', 
                               'Delhi', 'Mumbai', 'Delhi', 
                               'Mumbai','Chennai',  'Ghaziabad'],
                     'Mileage' :  [28,28, 27, 25, 26, 28, 
                                   29, 24, 21, 24]})
data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1    Maruti  2012       50000    Gurgaon       28
2   Hyundai  2014       30000      Delhi       27
3      Tata  2011       60000     Mumbai       25
4  Mahindra  2015       25000      Delhi       26
5    Maruti  2012       10000     Mumbai       28
6   Hyundai  2016       46000      Delhi       29
7   Renault  2014       31000     Mumbai       24
8      Tata  2018       15000    Chennai       21
9    Maruti  2019       12000  Ghaziabad       24

In [118]:
data.duplicated()
#All values in the row needs to be same

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [119]:
data.drop_duplicates(inplace=True)

In [120]:
data

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
2   Hyundai  2014       30000      Delhi       27
3      Tata  2011       60000     Mumbai       25
4  Mahindra  2015       25000      Delhi       26
5    Maruti  2012       10000     Mumbai       28
6   Hyundai  2016       46000      Delhi       29
7   Renault  2014       31000     Mumbai       24
8      Tata  2018       15000    Chennai       21
9    Maruti  2019       12000  Ghaziabad       24

In [122]:
data.nlargest(3,"Mileage")
#Return the first `n` rows ordered by `columns` in descending order.

     Brand  Year  Kms Driven     City  Mileage
6  Hyundai  2016       46000    Delhi       29
0   Maruti  2012       50000  Gurgaon       28
5   Maruti  2012       10000   Mumbai       28

In [123]:
data.nsmallest(3,"Mileage")

     Brand  Year  Kms Driven       City  Mileage
8     Tata  2018       15000    Chennai       21
7  Renault  2014       31000     Mumbai       24
9   Maruti  2019       12000  Ghaziabad       24