## Data Filtering

In [1]:
import pandas as pd
titanic=pd.read_csv(r"C:\Users\admin\Desktop\data_science\data\\titanic_train.csv")
df_titanic=pd.DataFrame(titanic)

In [2]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df_titanic["Age"]>30

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: Age, Length: 891, dtype: bool

In [5]:
df_titanic.loc[df_titanic["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
(df_titanic["Age"]>30) & (df_titanic["Age"]<60)

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: Age, Length: 891, dtype: bool

In [7]:
df_titanic.loc[df_titanic["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
df_titanic.loc[(df_titanic["Age"]>30) & (df_titanic["Age"]<60) |  (df_titanic["Sex"]=="female")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df_titanic.loc[df_titanic["Name"].str.contains("Mrs")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [10]:
df_titanic.loc[df_titanic["Name"].str.contains("William")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
...,...,...,...,...,...,...,...,...,...,...,...,...
802,803,1,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S
810,811,0,3,"Alexander, Mr. William",male,26.0,0,0,3474,7.8875,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [11]:
df_titanic.loc[df_titanic["Name"].str.startswith("Henry")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
264,265,0,3,"Henry, Miss. Delia",female,NaN,0,0,382649,7.75,NaN,Q

In [12]:
df_titanic.loc[df_titanic["Name"].str.endswith("Henry")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,NaN,S
209,210,1,1,"Blank, Mr. Henry",male,40.0,0,0,112277,31.0000,A31,C
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
239,240,0,2,"Hunt, Mr. George Henry",male,33.0,0,0,SCO/W 1585,12.2750,NaN,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S
385,386,0,2,"Davies, Mr. Charles Henry",male,18.0,0,0,S.O.C. 14879,73.5000,NaN,S
411,412,0,3,"Hart, Mr. Henry",male,NaN,0,0,394140,6.8583,NaN,Q
476,477,0,2,"Renouf, Mr. Peter Henry",male,34.0,1,0,31027,21.0000,NaN,S
482,483,0,3,"Rouse, Mr. Richard Henry",male,50.0,0,0,A/5 3594,8.0500,NaN,S
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
722,723,0,2,"Gillespie, Mr. William Henry",male,34.0,0,0,12233,13.0000,NaN,S

In [13]:
df_titanic["Fare"].sort_values()

271      0.0000
597      0.0000
302      0.0000
633      0.0000
277      0.0000
         ...
438    263.0000
341    263.0000
737    512.3292
258    512.3292
679    512.3292
Name: Fare, Length: 891, dtype: float64

# Conditional changes

In [14]:
details = {
    'Name' : ['Ankit', 'Aishwarya','Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Maths' : [80, 40, 50, 70,42, 61],
   'Sci' : [83, 21, 43, 61,72, 71],
    'Hindi' : [53, 21, 73, 11,92, 11],
    'Chem' : [73, 41, 43, 41,82, 91],
    'Bio' : [93, 41, 23, 41,45, 51],
    'Sanskrit' : [73, 81, 53, 41,72, 21],
}
import pandas as pd
d1=pd.DataFrame(details)

d1

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit
0      Ankit     80   83     53    73   93        73
1  Aishwarya     40   21     21    41   41        81
2      Ankit     50   43     73    43   23        53
3  Aishwarya     70   61     11    41   41        41
4    Shaurya     42   72     92    82   45        72
5   Shivangi     61   71     11    91   51        21

In [15]:
d1["total"]=0

In [16]:
d1["total"]=d1["Maths"]+d1["Sci"]+d1["Hindi"]+d1["Chem"]+d1["Bio"]+d1["Sanskrit"]
d1

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit  total
0      Ankit     80   83     53    73   93        73    455
1  Aishwarya     40   21     21    41   41        81    245
2      Ankit     50   43     73    43   23        53    285
3  Aishwarya     70   61     11    41   41        41    265
4    Shaurya     42   72     92    82   45        72    405
5   Shivangi     61   71     11    91   51        21    306

In [17]:
d1["%"]=0
d1

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit  total  %
0      Ankit     80   83     53    73   93        73    455  0
1  Aishwarya     40   21     21    41   41        81    245  0
2      Ankit     50   43     73    43   23        53    285  0
3  Aishwarya     70   61     11    41   41        41    265  0
4    Shaurya     42   72     92    82   45        72    405  0
5   Shivangi     61   71     11    91   51        21    306  0

In [18]:
d1["%"]=(d1["total"]/600)*100
d1

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit  total          %
0      Ankit     80   83     53    73   93        73    455  75.833333
1  Aishwarya     40   21     21    41   41        81    245  40.833333
2      Ankit     50   43     73    43   23        53    285  47.500000
3  Aishwarya     70   61     11    41   41        41    265  44.166667
4    Shaurya     42   72     92    82   45        72    405  67.500000
5   Shivangi     61   71     11    91   51        21    306  51.000000

### Example: Grades

less than 45 :fail


45-60 pass


60-70 1st class


70- distinction

In [19]:
d1["Grade"]=None

In [20]:
d1

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit  total          % Grade
0      Ankit     80   83     53    73   93        73    455  75.833333  None
1  Aishwarya     40   21     21    41   41        81    245  40.833333  None
2      Ankit     50   43     73    43   23        53    285  47.500000  None
3  Aishwarya     70   61     11    41   41        41    265  44.166667  None
4    Shaurya     42   72     92    82   45        72    405  67.500000  None
5   Shivangi     61   71     11    91   51        21    306  51.000000  None

In [21]:
d1.loc[d1["%"]<45]

        Name  Maths  Sci  Hindi  Chem  Bio  Sanskrit  total          % Grade
1  Aishwarya     40   21     21    41   41        81    245  40.833333  None
3  Aishwarya     70   61     11    41   41        41    265  44.166667  None

In [22]:
d1.loc[(d1["%"]>45)&(d1["%"]<60),["Grade"]]="PASS"

In [23]:
d1.loc[(d1["%"]>60)&(d1["%"]<70),["Grade"]]="FIRST CLASS"

In [24]:
d1.loc[(d1["%"]>70)&(d1["%"]<100),["Grade"]]="DISTINCTION"

In [25]:
d1.loc[d1["%"]<45,["Grade"]]="FAIL"

In [26]:
d1

,Name,Maths,Sci,Hindi,Chem,Bio,Sanskrit,total,%,Grade
0,Ankit,80,83,53,73,93,73,455,75.833333,DISTINCTION
1,Aishwarya,40,21,21,41,41,81,245,40.833333,FAIL
2,Ankit,50,43,73,43,23,53,285,47.500000,PASS
3,Aishwarya,70,61,11,41,41,41,265,44.166667,FAIL
4,Shaurya,42,72,92,82,45,72,405,67.500000,FIRST CLASS
5,Shivangi,61,71,11,91,51,21,306,51.000000,PASS

In [27]:
>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...      index=['cobra', 'viper', 'sidewinder'],
...      columns=['max_speed', 'shield'])

In [28]:
df

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [30]:
#Single label. Note this returns the row as a Series.

df.loc['viper']

max_speed    4
shield       5
Name: viper, dtype: int64

In [31]:
#List of labels. Note using ``[[]]`` returns a DataFrame.
df.loc[['viper', 'sidewinder']]

            max_speed  shield
viper               4       5
sidewinder          7       8

In [32]:
#Single label for row and column
df.loc['cobra', 'shield']

2

In [33]:
#Slice with labels for row and single label for column. As mentioned
#above, note that both the start and stop of the slice are included.

df.loc['cobra':'viper', 'max_speed']

cobra    1
viper    4
Name: max_speed, dtype: int64

In [34]:
#Boolean list with the same length as the row axis

df.loc[[False, False, True]]

            max_speed  shield
sidewinder          7       8

In [37]:
#Alignable boolean Series:
df.loc[pd.Series([False, True, False],index=['viper', 'sidewinder', 'cobra'])]

            max_speed  shield
sidewinder          7       8

In [38]:
#Index (same behavior as ``df.reindex``)
df.loc[pd.Index(["cobra", "viper"], name="foo")]

       max_speed  shield
foo
cobra          1       2
viper          4       5

In [39]:
#Conditional that returns a boolean Series
df.loc[df['shield'] > 6]

            max_speed  shield
sidewinder          7       8

In [40]:
#Conditional that returns a boolean Series with column labels specified
df.loc[df['shield'] > 6, ['max_speed']]

            max_speed
sidewinder          7

In [41]:
#Callable that returns a boolean Series
df.loc[lambda df: df['shield'] == 8]

            max_speed  shield
sidewinder          7       8

In [42]:
#Set value for all items matching the list of labels
df.loc[['viper', 'sidewinder'], ['shield']] = 50
df

            max_speed  shield
cobra               1       2
viper               4      50
sidewinder          7      50

In [43]:
#Set value for an entire row

df.loc['cobra'] = 10
df

            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

In [44]:
#Set value for an entire column

df.loc[:, 'max_speed'] = 30
df

            max_speed  shield
cobra              30      10
viper              30      50
sidewinder         30      50

In [45]:
#Set value for rows matching callable condition
df.loc[df['shield'] > 35] = 0
df

            max_speed  shield
cobra              30      10
viper               0       0
sidewinder          0       0

Slice with integer labels for rows. As mentioned above, note that both
the start and stop of the slice are included.

>>> df.loc[7:9]
   max_speed  shield
7          1       2
8          4       5
9          7       8

**Getting values with a MultiIndex**

A number of examples using a DataFrame with a MultiIndex

>>> tuples = [
...    ('cobra', 'mark i'), ('cobra', 'mark ii'),
...    ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
...    ('viper', 'mark ii'), ('viper', 'mark iii')
... ]
>>> index = pd.MultiIndex.from_tuples(tuples)
>>> values = [[12, 2], [0, 4], [10, 20],
...         [1, 4], [7, 1], [16, 36]]
>>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
>>> df
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Single label. Note this returns a DataFrame with a single index.

>>> df.loc['cobra']
         max_speed  shield
mark i          12       2
mark ii          0       4

Single index tuple. Note this returns a Series.

>>> df.loc[('cobra', 'mark ii')]
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

Single label for row and column. Similar to passing in a tuple, this
returns a Series.

>>> df.loc['cobra', 'mark i']
max_speed    12
shield        2
Name: (cobra, mark i), dtype: int64

Single tuple. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[[('cobra', 'mark ii')]]
               max_speed  shield
cobra mark ii          0       4

Single tuple for the index with a single label for the column

>>> df.loc[('cobra', 'mark i'), 'shield']
2

Slice from index tuple to single label

>>> df.loc[('cobra', 'mark i'):'viper']
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Slice from index tuple to index tuple

>>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                    max_speed  shield
cobra      mark i          12       2
           mark ii          0       4
sidewinder mark i          10      20
           mark ii          1       4
viper      mark ii          7       1