## What is Pandas:
-Open source data analysis library written in python
-It leverages the speed and power of Numpy(which is written in C lang) to make datat analysis and preprocessing easy for data scientists
-It provides rich and highly robus data operations

#### Pandas has 2 types of data structures:
SERIES: Its a 1D array with indexes it stores single column or row of data in a dataframe. Capable of holding any one type of data.

DATAFRAMES: Its a tabular spreadsheet like structure representing rows which contains one or more columns. Capable of holding columns pf potentially different types of data.

In [26]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":['harry','rohan','skillf','shubh'],
    "marks":[92,34,24,17],
    "city":['rampur','kolkata','pune','mumbai']
}

In [4]:
df=pd.DataFrame(dict1)
df
"""
Dataframe:
rows:index
column:columns
"""

     name  marks     city
0   harry     92   rampur
1   rohan     34  kolkata
2  skillf     24     pune
3   shubh     17   mumbai

In [5]:
df.to_csv('friends.csv')

In [6]:
#df.to_csv('friends_without_index.csv', index=False)

In [8]:
df.head(3)

     name  marks     city
0   harry     92   rampur
1   rohan     34  kolkata
2  skillf     24     pune

In [9]:
df.tail(4)

     name  marks     city
0   harry     92   rampur
1   rohan     34  kolkata
2  skillf     24     pune
3   shubh     17   mumbai

In [11]:
df.describe()

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [14]:
ak=pd.read_csv('ak.csv')
ak

   Train No.  Speed     city
0      12344     34   rampur
1      12534    132  kolkata
2     125654     67     pune
3     564523     87   mumbai

In [15]:
ak['Speed']

0     34
1    132
2     67
3     87
Name: Speed, dtype: int64

In [16]:
ak['Speed'][0]

34

In [17]:
ak['Speed'][0]=500

<ipython-input-17-52e773f2a0b1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ak['Speed'][0]=500

In [18]:
ak

   Train No.  Speed     city
0      12344    500   rampur
1      12534    132  kolkata
2     125654     67     pune
3     564523     87   mumbai

In [22]:
ak.to_csv('ak.csv',index=True)

In [23]:
ak.index=['first','second','third','fourth']

In [24]:
ak

        Train No.  Speed     city
first       12344    500   rampur
second      12534    132  kolkata
third      125654     67     pune
fourth     564523     87   mumbai

In [31]:
ser = pd.Series(np.random.rand(10))
ser

0    0.775004
1    0.535568
2    0.521811
3    0.515051
4    0.791750
5    0.253686
6    0.690260
7    0.875321
8    0.453618
9    0.268368
dtype: float64

In [32]:
type(ser)

pandas.core.series.Series

In [34]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.930286  0.418558  0.094475  0.221318  0.351370
1  0.979444  0.163588  0.231736  0.413348  0.843781
2  0.148983  0.079686  0.670735  0.387778  0.302773
3  0.889044  0.927721  0.546517  0.944857  0.155654
4  0.258995  0.647910  0.534798  0.004942  0.504393

In [35]:
type(newdf)

pandas.core.frame.DataFrame

In [37]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.501089    0.523834    0.490427    0.497611    0.484769
std      0.292729    0.303045    0.294108    0.300474    0.286181
min      0.001064    0.000173    0.000296    0.000504    0.000889
25%      0.236353    0.261082    0.234470    0.225695    0.239910
50%      0.479281    0.540724    0.494485    0.483558    0.466300
75%      0.765732    0.791958    0.734085    0.784056    0.741980
max      0.999609    0.995545    0.999972    0.993199    0.997852

In [39]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [40]:
newdf[0][0]="akshay"
newdf.head()

          0         1         2         3         4
0    akshay  0.418558  0.094475  0.221318  0.351370
1  0.979444  0.163588  0.231736  0.413348  0.843781
2  0.148983  0.079686  0.670735  0.387778  0.302773
3  0.889044  0.927721  0.546517  0.944857  0.155654
4  0.258995  0.647910  0.534798  0.004942  0.504393

In [41]:
newdf.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
           dtype='int64', length=334)

In [43]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [44]:
newdf.to_numpy()

array([['akshay', 0.41855797408320883, 0.09447501600755526,
        0.22131775434923717, 0.35137002715161947],
       [0.9794442155472902, 0.16358794829408163, 0.23173592701600487,
        0.4133482214541242, 0.8437805349245977],
       [0.1489831964091194, 0.07968578590921738, 0.6707349859395202,
        0.38777790196137907, 0.30277304912347147],
       ...,
       [0.4946083875846461, 0.6935313345342458, 0.19614341313016925,
        0.0027145606398721878, 0.2663509268157128],
       [0.9561212464760119, 0.844397284552916, 0.45138932446029534,
        0.8437703926701272, 0.244718977391989],
       [0.7974667084681398, 0.38815869069628095, 0.0038602834139133124,
        0.12280256307186865, 0.3202677412120115]], dtype=object)

In [58]:
newdf[0][0]="harry"
newdf.head()

<ipython-input-58-3f188cf85083>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[0][0]="harry"

          0         1         2         3         4
0     harry  0.418558  0.094475  0.221318  0.351370
1      ajay  0.163588  0.231736  0.413348  0.843781
2  0.148983  0.079686  0.670735  0.387778  0.302773
3  0.889044  0.927721  0.546517  0.944857  0.155654
4  0.258995  0.647910  0.534798  0.004942  0.504393

In [49]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,harry,0.979444,0.148983,0.889044,0.258995,0.673216,0.360183,0.317058,0.107228,0.902197,...,0.880575,0.712633,0.947991,0.035873,0.95222,0.54392,0.396257,0.494608,0.956121,0.797467
1,0.418558,0.163588,0.079686,0.927721,0.64791,0.284997,0.273016,0.264861,0.971757,0.622333,...,0.012567,0.485649,0.136888,0.744026,0.726636,0.234448,0.505084,0.693531,0.844397,0.388159
2,0.094475,0.231736,0.670735,0.546517,0.534798,0.273029,0.679574,0.30796,0.878208,0.694204,...,0.748151,0.458571,0.07634,0.012896,0.85384,0.670526,0.893846,0.196143,0.451389,0.00386
3,0.221318,0.413348,0.387778,0.944857,0.004942,0.211358,0.989071,0.220384,0.063946,0.663102,...,0.594323,0.97703,0.613838,0.828857,0.001724,0.322871,0.676096,0.002715,0.84377,0.122803
4,0.35137,0.843781,0.302773,0.155654,0.504393,0.664526,0.863737,0.336685,0.779991,0.949927,...,0.03249,0.91455,0.257292,0.386957,0.920347,0.673381,0.227458,0.266351,0.244719,0.320268

In [48]:
newdf.head()

          0         1         2         3         4
0     harry  0.418558  0.094475  0.221318  0.351370
1  0.979444  0.163588  0.231736  0.413348  0.843781
2  0.148983  0.079686  0.670735  0.387778  0.302773
3  0.889044  0.927721  0.546517  0.944857  0.155654
4  0.258995  0.647910  0.534798  0.004942  0.504393

In [50]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.797467  0.388159  0.003860  0.122803  0.320268
332  0.956121  0.844397  0.451389  0.843770  0.244719
331  0.494608  0.693531  0.196143  0.002715  0.266351
330  0.396257  0.505084  0.893846  0.676096  0.227458
329   0.54392  0.234448  0.670526  0.322871  0.673381
..        ...       ...       ...       ...       ...
4    0.258995  0.647910  0.534798  0.004942  0.504393
3    0.889044  0.927721  0.546517  0.944857  0.155654
2    0.148983  0.079686  0.670735  0.387778  0.302773
1    0.979444  0.163588  0.231736  0.413348  0.843781
0       harry  0.418558  0.094475  0.221318  0.351370

[334 rows x 5 columns]

In [51]:
newdf.head()

          0         1         2         3         4
0     harry  0.418558  0.094475  0.221318  0.351370
1  0.979444  0.163588  0.231736  0.413348  0.843781
2  0.148983  0.079686  0.670735  0.387778  0.302773
3  0.889044  0.927721  0.546517  0.944857  0.155654
4  0.258995  0.647910  0.534798  0.004942  0.504393

In [52]:
type(newdf[0])

pandas.core.series.Series

In [59]:
newdf2=newdf
newdf2[0][1]="ajay"
#newf2 is just a view of newdf and pointer to the same memory location. Any change in one of two makes change in other.

<ipython-input-59-ca43d0adeffa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][1]="ajay"

In [60]:
newdf

            0         1         2         3         4
0       harry  0.418558  0.094475  0.221318  0.351370
1        ajay  0.163588  0.231736  0.413348  0.843781
2    0.148983  0.079686  0.670735  0.387778  0.302773
3    0.889044  0.927721  0.546517  0.944857  0.155654
4    0.258995  0.647910  0.534798  0.004942  0.504393
..        ...       ...       ...       ...       ...
329   0.54392  0.234448  0.670526  0.322871  0.673381
330  0.396257  0.505084  0.893846  0.676096  0.227458
331  0.494608  0.693531  0.196143  0.002715  0.266351
332  0.956121  0.844397  0.451389  0.843770  0.244719
333  0.797467  0.388159  0.003860  0.122803  0.320268

[334 rows x 5 columns]