In [2]:
import pandas as pd

dfp=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')

dfs=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

dictionary={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["sflajf@gmail","adjhdj@yahoo","adsfasfd@facebook"]
}

dfd=pd.DataFrame(dictionary)

In [3]:
dfp.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [4]:
dfs.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [5]:
dfd

   first     last              email
0  Corey  Schafer       sflajf@gmail
1   Jane      Doe       adjhdj@yahoo
2   John      Doe  adsfasfd@facebook

# 6. ADDING AND REMOVING ROWS/COLUMNS

In [6]:
#Adding the column
dfd["full name"]=dfd['first']+' '+dfd['last']

dfd

   first     last              email      full name
0  Corey  Schafer       sflajf@gmail  Corey Schafer
1   Jane      Doe       adjhdj@yahoo       Jane Doe
2   John      Doe  adsfasfd@facebook       John Doe

In [7]:
#remove column

dfd.drop(columns=['first','last'],inplace=True)

dfd

               email      full name
0       sflajf@gmail  Corey Schafer
1       adjhdj@yahoo       Jane Doe
2  adsfasfd@facebook       John Doe

In [8]:
dfd['full name'].str.split(' ',expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [9]:
dfd[['first','last']]=dfd['full name'].str.split(' ',expand=True)

dfd

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe

In [79]:
dfd.append({'first':'Tony'}, ignore_index=True)

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe
3                NaN            NaN   Tony      NaN

In [10]:
avengers={
    "first":["Tony","Steve"],
    "last":["Stark","Rogers"],
    "email":["iron@gmail","captain@gamil"]
}

dfa=pd.DataFrame(avengers)

In [11]:
#Adding avengers to dfd

dfd=dfd.append(dfa, ignore_index=True)

dfd

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe
3         iron@gmail            NaN   Tony    Stark
4      captain@gamil            NaN  Steve   Rogers

In [12]:
#To remove a row
dfd.drop(index=4)

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe
3         iron@gmail            NaN   Tony    Stark

In [13]:
#To remove rows with last name Doe
dfd.drop(index=dfd[dfd['last']=="Doe"].index)

           email      full name  first     last
0   sflajf@gmail  Corey Schafer  Corey  Schafer
3     iron@gmail            NaN   Tony    Stark
4  captain@gamil            NaN  Steve   Rogers

## 7. Sorting Data

In [14]:
dfd

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe
3         iron@gmail            NaN   Tony    Stark
4      captain@gamil            NaN  Steve   Rogers

In [15]:
dfd['last'].sort_values()

1        Doe
2        Doe
4     Rogers
0    Schafer
3      Stark
Name: last, dtype: object

In [16]:
dfd.sort_values(by='last', ascending=False)

               email      full name  first     last
3         iron@gmail            NaN   Tony    Stark
0       sflajf@gmail  Corey Schafer  Corey  Schafer
4      captain@gamil            NaN  Steve   Rogers
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe

In [17]:
dfd.sort_values(by=['last','first'], ascending=False)

               email      full name  first     last
3         iron@gmail            NaN   Tony    Stark
0       sflajf@gmail  Corey Schafer  Corey  Schafer
4      captain@gamil            NaN  Steve   Rogers
2  adsfasfd@facebook       John Doe   John      Doe
1       adjhdj@yahoo       Jane Doe   Jane      Doe

In [18]:
dfd.sort_values(by=['last','first'], ascending=[False,True],inplace=True)
dfd

               email      full name  first     last
3         iron@gmail            NaN   Tony    Stark
0       sflajf@gmail  Corey Schafer  Corey  Schafer
4      captain@gamil            NaN  Steve   Rogers
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe

In [19]:
dfd.sort_index(inplace=True)
dfd

               email      full name  first     last
0       sflajf@gmail  Corey Schafer  Corey  Schafer
1       adjhdj@yahoo       Jane Doe   Jane      Doe
2  adsfasfd@facebook       John Doe   John      Doe
3         iron@gmail            NaN   Tony    Stark
4      captain@gamil            NaN  Steve   Rogers

In [20]:
dfp.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [21]:
dfs.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [22]:
dfp.sort_values(by=['Country','ConvertedComp'],ascending=[True,False],inplace=True)
dfp[['Country','ConvertedComp']].head(50)

                Country  ConvertedComp
Respondent
63129       Afghanistan      1000000.0
50499       Afghanistan       153216.0
39258       Afghanistan        19152.0
58450       Afghanistan        17556.0
7085        Afghanistan        14364.0
22450       Afghanistan         7980.0
48436       Afghanistan         4464.0
10746       Afghanistan         3996.0
8149        Afghanistan         1596.0
29736       Afghanistan         1116.0
722         Afghanistan            0.0
28638       Afghanistan            0.0
6417        Afghanistan            NaN
7353        Afghanistan            NaN
12310       Afghanistan            NaN
26340       Afghanistan            NaN
29045       Afghanistan            NaN
33178       Afghanistan            NaN
37802       Afghanistan            NaN
40000       Afghanistan            NaN
43106       Afghanistan            NaN
44403       Afghanistan            NaN
45854       Afghanistan            NaN
47110       Afghanistan            NaN
49702       Afghanistan            NaN
50767       Afghanistan            NaN
51859       Afghanistan            NaN
58760       Afghanistan            NaN
59560       Afghanistan            NaN
60569       Afghanistan            NaN
60946       Afghanistan            NaN
62168       Afghanistan            NaN
62525       Afghanistan            NaN
74386       Afghanistan            NaN
80926       Afghanistan            NaN
85715       Afghanistan            NaN
85825       Afghanistan            NaN
86362       Afghanistan            NaN
86932       Afghanistan            NaN
87091       Afghanistan            NaN
88582       Afghanistan            NaN
88731       Afghanistan            NaN
2782        Afghanistan            NaN
63019       Afghanistan            NaN
38308           Albania       187668.0
3787            Albania       114550.0
9270            Albania        74474.0
6716            Albania        60000.0
10303           Albania        57300.0
66280           Albania        41244.0

In [23]:
#To view first 10 highest values
dfp['ConvertedComp'].nlargest(10)
#.nsmallest( for smallest values)

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: ConvertedComp, dtype: float64

In [24]:
dfp.nlargest(10,'ConvertedComp')
#.nsmallest fro smallest values

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
25983,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87896,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,...,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
78151,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
80200,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
52132,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75561,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32250,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

## 9. Grouping and Aggregating Data

In [27]:
import pandas as pd

dfp=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')

dfs=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

dictionary={
    "first":["Corey","Jane","John"],
    "last":["Schafer","Doe","Doe"],
    "email":["sflajf@gmail","adjhdj@yahoo","adsfasfd@facebook"]
}

dfd=pd.DataFrame(dictionary)

In [96]:
#Aggregation means combining multiple pieces of data into a single result

In [28]:
dfp['ConvertedComp'].head(10)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
Name: ConvertedComp, dtype: float64

In [29]:
dfp['ConvertedComp'].median()

57287.0

In [30]:
dfp.median()

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [31]:
dfp.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [32]:
dfp['ConvertedComp'].count()
#.count() gives count of values except NaN

55823

In [33]:
dfp['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [34]:
dfp['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [35]:
dfp['SocialMedia']

Respondent
1          Twitter
2        Instagram
3           Reddit
4           Reddit
5         Facebook
           ...
88377      YouTube
88601          NaN
88802          NaN
88816          NaN
88863     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [36]:
dfp['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [37]:
dfs.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [39]:
dfp['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [40]:
#Group By: invloves some combination splitting up our object, applying a function and, then combining those results
dfp['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Saint Vincent and the Grenadines        1
Saint Kitts and Nevis                   1
Niger                                   1
Brunei Darussalam                       1
Timor-Leste                             1
Name: Country, Length: 179, dtype: int64

In [41]:
dfp.groupby(['Country'])

In [42]:
country_grp=dfp.groupby(['Country'])
country_grp

In [43]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [44]:
filt=dfp['Country']=='India'
dfp.loc[filt]['SocialMedia'].value_counts()
#This filters only for specified country

WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [45]:
country_grp['SocialMedia'].value_counts().head(20)
#This returns a series for all countries

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
             LinkedIn                     1
             Twitter                      1
Albania      WhatsApp                    18
             Facebook                    16
             Instagram                   13
             YouTube                     10
             Twitter                      8
             LinkedIn                     7
             Reddit                       6
             I don't use social media     4
             Snapchat                     1
             WeChat 微信                    1
Algeria      YouTube                     42
             Facebook                    41
             Twitter                     14
Name: SocialMedia, dtype: int64

In [46]:
country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [47]:
desh=input("Entr country name: ")
country_grp['SocialMedia'].value_counts().loc[desh]
#we can access any country using this

Entr country name: India

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [48]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [50]:
country_grp['ConvertedComp'].median().loc['Germany']

63016.0

In [51]:
country_grp['ConvertedComp'].agg(['median','mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [52]:
country_grp['ConvertedComp'].agg(['median','mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [53]:
filt=dfp['Country']=='India'
dfp.loc[filt]['LanguageWorkedWith'].str.contains('Python')

Respondent
8         True
10        True
15       False
50        True
65       False
         ...
77339    False
79795     True
83862    False
84299     True
86012    False
Name: LanguageWorkedWith, Length: 9061, dtype: object

In [56]:
filt=dfp['Country']=='India'
dfp.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [57]:
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

#Notice the error

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [59]:
country_grp["LanguageWorkedWith"]

In [58]:
country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("Python").sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [60]:
country_respondents=dfp['Country'].value_counts()
country_respondents

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Saint Vincent and the Grenadines        1
Saint Kitts and Nevis                   1
Niger                                   1
Brunei Darussalam                       1
Timor-Leste                             1
Name: Country, Length: 179, dtype: int64

In [61]:
#What % of people from each country know how to use python
#country_grp['LanguageWorkedWith'].apply(lambda x:xstr.contains('Python')).value_counts(normalize=True)

country_respondents=dfp['Country'].value_counts()
country_respondents

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Saint Vincent and the Grenadines        1
Saint Kitts and Nevis                   1
Niger                                   1
Brunei Darussalam                       1
Timor-Leste                             1
Name: Country, Length: 179, dtype: int64

In [62]:
country_uses_python=country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("Python").sum())
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [63]:
python_df=pd.concat([country_respondents,country_uses_python],axis='columns',sort=False)
python_df

                                  Country  LanguageWorkedWith
United States                       20949               10083
India                                9061                3105
Germany                              5866                2451
United Kingdom                       5737                2384
Canada                               3395                1558
...                                   ...                 ...
Saint Vincent and the Grenadines        1                   0
Saint Kitts and Nevis                   1                   0
Niger                                   1                   1
Brunei Darussalam                       1                   0
Timor-Leste                             1                   1

[179 rows x 2 columns]

In [64]:
python_df.rename(columns={'Country':'NumRespondents','LanguageWorkedWith':'NumKnowsPython'},inplace=True)
python_df

                                  NumRespondents  NumKnowsPython
United States                              20949           10083
India                                       9061            3105
Germany                                     5866            2451
United Kingdom                              5737            2384
Canada                                      3395            1558
...                                          ...             ...
Saint Vincent and the Grenadines               1               0
Saint Kitts and Nevis                          1               0
Niger                                          1               1
Brunei Darussalam                              1               0
Timor-Leste                                    1               1

[179 rows x 2 columns]

In [65]:
python_df['%KnowsPython']=(python_df['NumKnowsPython']/python_df['NumRespondents'
])*100
python_df

                                  NumRespondents  NumKnowsPython  %KnowsPython
United States                              20949           10083     48.131176
India                                       9061            3105     34.267741
Germany                                     5866            2451     41.783157
United Kingdom                              5737            2384     41.554820
Canada                                      3395            1558     45.891016
...                                          ...             ...           ...
Saint Vincent and the Grenadines               1               0      0.000000
Saint Kitts and Nevis                          1               0      0.000000
Niger                                          1               1    100.000000
Brunei Darussalam                              1               0      0.000000
Timor-Leste                                    1               1    100.000000

[179 rows x 3 columns]

In [66]:
python_df.sort_values('%KnowsPython',ascending=False)

                                  NumRespondents  NumKnowsPython  %KnowsPython
Timor-Leste                                    1               1    100.000000
Niger                                          1               1    100.000000
Dominica                                       1               1    100.000000
Sao Tome and Principe                          1               1    100.000000
Turkmenistan                                   7               6     85.714286
...                                          ...             ...           ...
Gabon                                          2               0      0.000000
Cape Verde                                     3               0      0.000000
Lao People's Democratic Republic               3               0      0.000000
Malawi                                         2               0      0.000000
Tajikistan                                     7               0      0.000000

[179 rows x 3 columns]

# 9. Cleaning Data: Casting datatypes and Handling missing data

In [67]:
import pandas as pd
import numpy as np

dfp=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent')

dfs=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

dictionary={
    "first":["Corey","Jane","John","Chris",np.nan,None,'NA'],
    "last":["Schafer","Doe","Doe","Schafer",np.nan,np.nan,'Missing'],
    "email":["CS@gmail","JaD@yahoo","JoD@facebook","ChS@gmail",None,np.nan,"anonymous@gmail"],
    "age":['33','33','63','36',None,None,'Missing']
}

ddf=pd.DataFrame(dictionary)

In [68]:
ddf

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
4    NaN      NaN             None     None
5   None      NaN              NaN     None
6     NA  Missing  anonymous@gmail  Missing

In [69]:
ddf.dropna()

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
6     NA  Missing  anonymous@gmail  Missing

In [70]:
ddf.dropna(axis='index',how='any')

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
6     NA  Missing  anonymous@gmail  Missing

In [71]:
ddf.dropna(axis='index',how='all')
#drops an axis only when all have na values

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
6     NA  Missing  anonymous@gmail  Missing

In [72]:
ddf.dropna(axis='columns',how='all')

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
4    NaN      NaN             None     None
5   None      NaN              NaN     None
6     NA  Missing  anonymous@gmail  Missing

In [73]:
ddf.dropna(axis='columns',how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [74]:
ddf.dropna(axis='index',how='any',subset=['email'])

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
6     NA  Missing  anonymous@gmail  Missing

In [75]:
ddf.dropna(axis='index',how='all',subset=['last','email'])

   first     last            email      age
0  Corey  Schafer         CS@gmail       33
1   Jane      Doe        JaD@yahoo       33
2   John      Doe     JoD@facebook       63
3  Chris  Schafer        ChS@gmail       36
6     NA  Missing  anonymous@gmail  Missing

In [76]:
ddf.replace('NA',np.nan,inplace=True)
ddf.replace('Missing',np.nan,inplace=True)
ddf

   first     last            email   age
0  Corey  Schafer         CS@gmail    33
1   Jane      Doe        JaD@yahoo    33
2   John      Doe     JoD@facebook    63
3  Chris  Schafer        ChS@gmail    36
4    NaN      NaN             None  None
5   None      NaN              NaN  None
6    NaN      NaN  anonymous@gmail   NaN

In [77]:
ddf.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4   True   True   True   True
5   True   True   True   True
6   True   True  False   True

In [78]:
ddf.fillna("MISSING")

     first     last            email      age
0    Corey  Schafer         CS@gmail       33
1     Jane      Doe        JaD@yahoo       33
2     John      Doe     JoD@facebook       63
3    Chris  Schafer        ChS@gmail       36
4  MISSING  MISSING          MISSING  MISSING
5  MISSING  MISSING          MISSING  MISSING
6  MISSING  MISSING  anonymous@gmail  MISSING

In [79]:
ddf.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [81]:
#ddf['age'].mean()
#Error: can only concatenate str (not "int") to str

In [80]:
type(np.nan)

float

In [82]:
#ddf['age']=ddf['age'].astype(int)
#Error: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

ddf['age']=ddf['age'].astype(float)

In [83]:
ddf.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [84]:
ddf['age'].mean()

41.25

In [85]:
import pandas as pd
na_vals=['NA','Missing']

dfp=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_public.csv'\
                     ,index_col='Respondent',na_values=na_vals)

dfs=pd.read_csv('C:\\Users\\admin\\Desktop\\Data_Science\\Data_for_ananlysis\\2019 developer survey Stackoverflow\\survey_results_schema.csv'\
                     ,index_col='Column')

In [86]:
dfp.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [87]:
dfs.head(2)

                                                 QuestionText
Column
Respondent  Randomized respondent ID number (not in order ...
MainBranch  Which of the following options best describes ...

In [88]:
dfp['YearsCode'].head(10)

Respondent
1       4
2     NaN
3       3
4       3
5      16
6      13
7       6
8       8
9      12
10     12
Name: YearsCode, dtype: object

In [89]:
dfp['YearsCode'].value_counts()

5                     7047
10                    6777
6                     6179
4                     5729
8                     5361
7                     5320
3                     5179
2                     3974
15                    3942
20                    3636
12                    3530
9                     3360
11                    2265
14                    2126
13                    2036
18                    1900
1                     1814
25                    1657
16                    1593
30                    1532
Less than 1 year      1367
17                    1349
19                    1018
22                    1016
35                     873
23                     745
21                     715
24                     693
40                     497
28                     465
32                     420
26                     409
27                     408
33                     353
38                     340
34                     327
37                     321
36                     308
29                     234
31                     202
39                     170
More than 50 years     126
42                     115
45                     113
41                      92
43                      83
44                      52
50                      51
47                      36
48                      31
46                      27
49                      25
Name: YearsCode, dtype: int64

In [90]:
dfp['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [91]:
dfp['YearsCode'].nunique()

52

In [171]:
#dfp['YearsCode'].mean()
#TypeError: can only concatenate str (not "int") to str

In [177]:
#dfp['YearsCode']=dfp['YearsCode'].mean()
#Error: TypeError: can only concatenate str (not "int") to str

In [92]:
dfp['YearsCode'].replace('Less than 1 year',0,inplace=True)

In [93]:
dfp['YearsCode'].replace('More than 50 years',51,inplace=True)

In [94]:
dfp['YearsCode'].dtypes

dtype('O')

In [95]:
dfp['YearsCode']=dfp['YearsCode'].astype(float)

In [96]:
dfp['YearsCode'].mean()

11.662114216834588

In [97]:
dfp['YearsCode'].unique()

array([ 4., nan,  3., 16., 13.,  6.,  8., 12.,  2.,  5., 17., 10., 14.,
       35.,  7.,  0., 30.,  9., 26., 40., 19., 15., 20., 28., 25.,  1.,
       22., 11., 33., 50., 41., 18., 34., 24., 23., 42., 27., 21., 36.,
       32., 39., 38., 31., 37., 51., 29., 44., 45., 48., 46., 43., 47.,
       49.])

In [189]:
#dfp['YearsCode']=dfp['YearsCode'].astype(int)
#dfp['YearsCode'].mean()

#ValueError: Cannot convert non-finite values (NA or inf) to integer
#This will give an error as na values are float type while others are intgers so